# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\HexEdit\HexEditReplaceWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HexEditReplaceWidget(object):
    def setupUi(self, HexEditReplaceWidget):
        HexEditReplaceWidget.setObjectName("HexEditReplaceWidget")
        HexEditReplaceWidget.resize(600, 58)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HexEditReplaceWidget.sizePolicy().hasHeightForWidth())
        HexEditReplaceWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(HexEditReplaceWidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(HexEditReplaceWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.findFormatCombo = QtWidgets.QComboBox(HexEditReplaceWidget)
        self.findFormatCombo.setObjectName("findFormatCombo")
        self.gridLayout.addWidget(self.findFormatCombo, 0, 2, 1, 1)
        self.findtextCombo = QtWidgets.QComboBox(HexEditReplaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findtextCombo.sizePolicy().hasHeightForWidth())
        self.findtextCombo.setSizePolicy(sizePolicy)
        self.findtextCombo.setMinimumSize(QtCore.QSize(300, 0))
        self.findtextCombo.setEditable(True)
        self.findtextCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.findtextCombo.setDuplicatesEnabled(False)
        self.findtextCombo.setObjectName("findtextCombo")
        self.gridLayout.addWidget(self.findtextCombo, 0, 3, 1, 1)
        self.findPrevButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.findPrevButton.setObjectName("findPrevButton")
        self.gridLayout.addWidget(self.findPrevButton, 0, 4, 1, 1)
        self.findNextButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.findNextButton.setObjectName("findNextButton")
        self.gridLayout.addWidget(self.findNextButton, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(HexEditReplaceWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.replaceFormatCombo = QtWidgets.QComboBox(HexEditReplaceWidget)
        self.replaceFormatCombo.setObjectName("replaceFormatCombo")
        self.gridLayout.addWidget(self.replaceFormatCombo, 1, 2, 1, 1)
        self.replacetextCombo = QtWidgets.QComboBox(HexEditReplaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replacetextCombo.sizePolicy().hasHeightForWidth())
        self.replacetextCombo.setSizePolicy(sizePolicy)
        self.replacetextCombo.setMinimumSize(QtCore.QSize(300, 0))
        self.replacetextCombo.setEditable(True)
        self.replacetextCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.replacetextCombo.setDuplicatesEnabled(False)
        self.replacetextCombo.setObjectName("replacetextCombo")
        self.gridLayout.addWidget(self.replacetextCombo, 1, 3, 1, 1)
        self.replaceButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.replaceButton.setObjectName("replaceButton")
        self.gridLayout.addWidget(self.replaceButton, 1, 4, 1, 1)
        self.replaceSearchButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.replaceSearchButton.setObjectName("replaceSearchButton")
        self.gridLayout.addWidget(self.replaceSearchButton, 1, 5, 1, 1)
        self.replaceAllButton = QtWidgets.QToolButton(HexEditReplaceWidget)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.gridLayout.addWidget(self.replaceAllButton, 1, 6, 1, 1)

        self.retranslateUi(HexEditReplaceWidget)
        QtCore.QMetaObject.connectSlotsByName(HexEditReplaceWidget)
        HexEditReplaceWidget.setTabOrder(self.findFormatCombo, self.findtextCombo)
        HexEditReplaceWidget.setTabOrder(self.findtextCombo, self.replaceFormatCombo)
        HexEditReplaceWidget.setTabOrder(self.replaceFormatCombo, self.replacetextCombo)
        HexEditReplaceWidget.setTabOrder(self.replacetextCombo, self.findPrevButton)
        HexEditReplaceWidget.setTabOrder(self.findPrevButton, self.findNextButton)
        HexEditReplaceWidget.setTabOrder(self.findNextButton, self.replaceButton)
        HexEditReplaceWidget.setTabOrder(self.replaceButton, self.replaceSearchButton)
        HexEditReplaceWidget.setTabOrder(self.replaceSearchButton, self.replaceAllButton)
        HexEditReplaceWidget.setTabOrder(self.replaceAllButton, self.closeButton)

    def retranslateUi(self, HexEditReplaceWidget):
        _translate = QtCore.QCoreApplication.translate
        HexEditReplaceWidget.setWindowTitle(_translate("HexEditReplaceWidget", "Find and Replace"))
        self.closeButton.setToolTip(_translate("HexEditReplaceWidget", "Press to close the window"))
        self.label.setText(_translate("HexEditReplaceWidget", "Find:"))
        self.findFormatCombo.setToolTip(_translate("HexEditReplaceWidget", "Select the data format of the find data field"))
        self.findPrevButton.setToolTip(_translate("HexEditReplaceWidget", "Press to find the previous occurrence"))
        self.findNextButton.setToolTip(_translate("HexEditReplaceWidget", "Press to find the next occurrence"))
        self.label_2.setText(_translate("HexEditReplaceWidget", "Replace:"))
        self.replaceFormatCombo.setToolTip(_translate("HexEditReplaceWidget", "Select the data format of the replace data field"))
        self.replaceButton.setToolTip(_translate("HexEditReplaceWidget", "Press to replace the selection"))
        self.replaceSearchButton.setToolTip(_translate("HexEditReplaceWidget", "Press to replace the selection and search for the next occurence"))
        self.replaceAllButton.setToolTip(_translate("HexEditReplaceWidget", "Press to replace all occurrences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HexEditReplaceWidget = QtWidgets.QWidget()
    ui = Ui_HexEditReplaceWidget()
    ui.setupUi(HexEditReplaceWidget)
    HexEditReplaceWidget.show()
    sys.exit(app.exec_())

