# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Project\PropertiesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PropertiesDialog(object):
    def setupUi(self, PropertiesDialog):
        PropertiesDialog.setObjectName("PropertiesDialog")
        PropertiesDialog.resize(600, 555)
        PropertiesDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        PropertiesDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropertiesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(PropertiesDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(PropertiesDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.spellPropertiesButton = QtWidgets.QPushButton(PropertiesDialog)
        self.spellPropertiesButton.setObjectName("spellPropertiesButton")
        self.gridLayout.addWidget(self.spellPropertiesButton, 1, 1, 1, 1)
        self.textLabel1 = QtWidgets.QLabel(PropertiesDialog)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout.addWidget(self.textLabel1, 2, 0, 1, 1)
        self.languageComboBox = QtWidgets.QComboBox(PropertiesDialog)
        self.languageComboBox.setObjectName("languageComboBox")
        self.gridLayout.addWidget(self.languageComboBox, 2, 1, 1, 1)
        self.mixedLanguageCheckBox = QtWidgets.QCheckBox(PropertiesDialog)
        self.mixedLanguageCheckBox.setObjectName("mixedLanguageCheckBox")
        self.gridLayout.addWidget(self.mixedLanguageCheckBox, 3, 1, 1, 1)
        self.textLabel1_2 = QtWidgets.QLabel(PropertiesDialog)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridLayout.addWidget(self.textLabel1_2, 4, 0, 1, 1)
        self.projectTypeComboBox = QtWidgets.QComboBox(PropertiesDialog)
        self.projectTypeComboBox.setObjectName("projectTypeComboBox")
        self.gridLayout.addWidget(self.projectTypeComboBox, 4, 1, 1, 1)
        self.dirLabel = QtWidgets.QLabel(PropertiesDialog)
        self.dirLabel.setObjectName("dirLabel")
        self.gridLayout.addWidget(self.dirLabel, 5, 0, 1, 1)
        self.dirPicker = E5PathPicker(PropertiesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dirPicker.sizePolicy().hasHeightForWidth())
        self.dirPicker.setSizePolicy(sizePolicy)
        self.dirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dirPicker.setObjectName("dirPicker")
        self.gridLayout.addWidget(self.dirPicker, 5, 1, 1, 1)
        self.versionLabel = QtWidgets.QLabel(PropertiesDialog)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout.addWidget(self.versionLabel, 6, 0, 1, 1)
        self.versionEdit = QtWidgets.QLineEdit(PropertiesDialog)
        self.versionEdit.setObjectName("versionEdit")
        self.gridLayout.addWidget(self.versionEdit, 6, 1, 1, 1)
        self.mainscriptLabel = QtWidgets.QLabel(PropertiesDialog)
        self.mainscriptLabel.setObjectName("mainscriptLabel")
        self.gridLayout.addWidget(self.mainscriptLabel, 7, 0, 1, 1)
        self.mainscriptPicker = E5PathPicker(PropertiesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainscriptPicker.sizePolicy().hasHeightForWidth())
        self.mainscriptPicker.setSizePolicy(sizePolicy)
        self.mainscriptPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mainscriptPicker.setObjectName("mainscriptPicker")
        self.gridLayout.addWidget(self.mainscriptPicker, 7, 1, 1, 1)
        self.transPropertiesButton = QtWidgets.QPushButton(PropertiesDialog)
        self.transPropertiesButton.setObjectName("transPropertiesButton")
        self.gridLayout.addWidget(self.transPropertiesButton, 8, 1, 1, 1)
        self.eolLabel = QtWidgets.QLabel(PropertiesDialog)
        self.eolLabel.setObjectName("eolLabel")
        self.gridLayout.addWidget(self.eolLabel, 9, 0, 1, 1)
        self.eolComboBox = QtWidgets.QComboBox(PropertiesDialog)
        self.eolComboBox.setObjectName("eolComboBox")
        self.eolComboBox.addItem("")
        self.eolComboBox.addItem("")
        self.eolComboBox.addItem("")
        self.eolComboBox.addItem("")
        self.gridLayout.addWidget(self.eolComboBox, 9, 1, 1, 1)
        self.authorLabel = QtWidgets.QLabel(PropertiesDialog)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout.addWidget(self.authorLabel, 10, 0, 1, 1)
        self.authorEdit = QtWidgets.QLineEdit(PropertiesDialog)
        self.authorEdit.setObjectName("authorEdit")
        self.gridLayout.addWidget(self.authorEdit, 10, 1, 1, 1)
        self.emailLabel = QtWidgets.QLabel(PropertiesDialog)
        self.emailLabel.setObjectName("emailLabel")
        self.gridLayout.addWidget(self.emailLabel, 11, 0, 1, 1)
        self.emailEdit = QtWidgets.QLineEdit(PropertiesDialog)
        self.emailEdit.setObjectName("emailEdit")
        self.gridLayout.addWidget(self.emailEdit, 11, 1, 1, 1)
        self.descriptionLabel = QtWidgets.QLabel(PropertiesDialog)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignTop)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 12, 0, 1, 1)
        self.descriptionEdit = QtWidgets.QTextEdit(PropertiesDialog)
        self.descriptionEdit.setTabChangesFocus(True)
        self.descriptionEdit.setAcceptRichText(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout.addWidget(self.descriptionEdit, 12, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.vcsCheckBox = QtWidgets.QCheckBox(PropertiesDialog)
        self.vcsCheckBox.setObjectName("vcsCheckBox")
        self.verticalLayout.addWidget(self.vcsCheckBox)
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.vcsLabel = QtWidgets.QLabel(PropertiesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vcsLabel.sizePolicy().hasHeightForWidth())
        self.vcsLabel.setSizePolicy(sizePolicy)
        self.vcsLabel.setText("")
        self.vcsLabel.setObjectName("vcsLabel")
        self._2.addWidget(self.vcsLabel)
        self.vcsInfoButton = QtWidgets.QPushButton(PropertiesDialog)
        self.vcsInfoButton.setObjectName("vcsInfoButton")
        self._2.addWidget(self.vcsInfoButton)
        self.verticalLayout.addLayout(self._2)
        self.buttonBox = QtWidgets.QDialogButtonBox(PropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.nameLabel.setBuddy(self.nameEdit)
        self.textLabel1.setBuddy(self.languageComboBox)
        self.textLabel1_2.setBuddy(self.projectTypeComboBox)
        self.dirLabel.setBuddy(self.dirPicker)
        self.versionLabel.setBuddy(self.versionEdit)
        self.mainscriptLabel.setBuddy(self.mainscriptPicker)
        self.eolLabel.setBuddy(self.eolComboBox)
        self.authorLabel.setBuddy(self.authorEdit)
        self.emailLabel.setBuddy(self.emailEdit)
        self.descriptionLabel.setBuddy(self.descriptionEdit)

        self.retranslateUi(PropertiesDialog)
        self.buttonBox.accepted.connect(PropertiesDialog.accept)
        self.buttonBox.rejected.connect(PropertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PropertiesDialog)
        PropertiesDialog.setTabOrder(self.nameEdit, self.spellPropertiesButton)
        PropertiesDialog.setTabOrder(self.spellPropertiesButton, self.languageComboBox)
        PropertiesDialog.setTabOrder(self.languageComboBox, self.mixedLanguageCheckBox)
        PropertiesDialog.setTabOrder(self.mixedLanguageCheckBox, self.projectTypeComboBox)
        PropertiesDialog.setTabOrder(self.projectTypeComboBox, self.dirPicker)
        PropertiesDialog.setTabOrder(self.dirPicker, self.versionEdit)
        PropertiesDialog.setTabOrder(self.versionEdit, self.mainscriptPicker)
        PropertiesDialog.setTabOrder(self.mainscriptPicker, self.transPropertiesButton)
        PropertiesDialog.setTabOrder(self.transPropertiesButton, self.eolComboBox)
        PropertiesDialog.setTabOrder(self.eolComboBox, self.authorEdit)
        PropertiesDialog.setTabOrder(self.authorEdit, self.emailEdit)
        PropertiesDialog.setTabOrder(self.emailEdit, self.descriptionEdit)
        PropertiesDialog.setTabOrder(self.descriptionEdit, self.vcsCheckBox)
        PropertiesDialog.setTabOrder(self.vcsCheckBox, self.vcsInfoButton)

    def retranslateUi(self, PropertiesDialog):
        _translate = QtCore.QCoreApplication.translate
        PropertiesDialog.setWindowTitle(_translate("PropertiesDialog", "Project Properties"))
        PropertiesDialog.setWhatsThis(_translate("PropertiesDialog", "<b>Project Properties Dialog</b>\n"
"<p>This dialog is used to show and edit the projects properties.</p>\n"
"<p>If the project is controlled by a version control system, the \"Show Repository Info\" button displays information about the repository.</p>"))
        self.nameLabel.setText(_translate("PropertiesDialog", "Project &Name:"))
        self.nameEdit.setToolTip(_translate("PropertiesDialog", "Enter the project name"))
        self.nameEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Project Name</b>\n"
"<p>Enter the project name</p>"))
        self.spellPropertiesButton.setToolTip(_translate("PropertiesDialog", "Press to edit the spell checking properties"))
        self.spellPropertiesButton.setText(_translate("PropertiesDialog", "Spell Checking Properties..."))
        self.textLabel1.setText(_translate("PropertiesDialog", "&Progr. Language:"))
        self.languageComboBox.setToolTip(_translate("PropertiesDialog", "Select the project\'s programming language"))
        self.mixedLanguageCheckBox.setToolTip(_translate("PropertiesDialog", "Select, if the project uses other programming languages as well"))
        self.mixedLanguageCheckBox.setText(_translate("PropertiesDialog", "Mi&xed programming languages"))
        self.mixedLanguageCheckBox.setShortcut(_translate("PropertiesDialog", "Alt+X"))
        self.textLabel1_2.setText(_translate("PropertiesDialog", "Project &Type:"))
        self.projectTypeComboBox.setToolTip(_translate("PropertiesDialog", "Select the type of the project"))
        self.dirLabel.setText(_translate("PropertiesDialog", "Project &Directory:"))
        self.dirPicker.setToolTip(_translate("PropertiesDialog", "Enter the project directory"))
        self.dirPicker.setWhatsThis(_translate("PropertiesDialog", "<b>Project Directory</b>\n"
"<p>Enter the project directory. You may select it\n"
" with a dialog by pressing the button to the right.</p>"))
        self.versionLabel.setText(_translate("PropertiesDialog", "&Version No.:"))
        self.versionEdit.setToolTip(_translate("PropertiesDialog", "Enter the version number"))
        self.versionEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Version No.</b>\n"
"<p>Enter the version no.</p>"))
        self.mainscriptLabel.setText(_translate("PropertiesDialog", "&Main Script:"))
        self.mainscriptPicker.setToolTip(_translate("PropertiesDialog", "Enter the main script"))
        self.mainscriptPicker.setWhatsThis(_translate("PropertiesDialog", "<b>Main Script</b>\n"
"<p>Enter the main script of the project. You may select it\n"
" with a dialog by pressing the button to the right.</p>"))
        self.transPropertiesButton.setToolTip(_translate("PropertiesDialog", "Press to edit the translations properties"))
        self.transPropertiesButton.setText(_translate("PropertiesDialog", "Translations Properties..."))
        self.eolLabel.setText(_translate("PropertiesDialog", "End of &Line Character:"))
        self.eolComboBox.setToolTip(_translate("PropertiesDialog", "Select the end of line character to be used by the project"))
        self.eolComboBox.setItemText(0, _translate("PropertiesDialog", "System"))
        self.eolComboBox.setItemText(1, _translate("PropertiesDialog", "Unix"))
        self.eolComboBox.setItemText(2, _translate("PropertiesDialog", "Macintosh"))
        self.eolComboBox.setItemText(3, _translate("PropertiesDialog", "Windows/DOS"))
        self.authorLabel.setText(_translate("PropertiesDialog", "&Author:"))
        self.authorEdit.setToolTip(_translate("PropertiesDialog", "Enter authors name"))
        self.authorEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Author</b>\n"
"<p>Enter the name of the author.</p>"))
        self.emailLabel.setText(_translate("PropertiesDialog", "&Email:"))
        self.emailEdit.setToolTip(_translate("PropertiesDialog", "Enter authors email"))
        self.emailEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Email</b>\n"
"<p>Enter the email address of the author</p>"))
        self.descriptionLabel.setText(_translate("PropertiesDialog", "&Description:"))
        self.descriptionEdit.setToolTip(_translate("PropertiesDialog", "Enter description"))
        self.descriptionEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Description</b>\n"
"<p>Enter a short description for the project.</p>"))
        self.vcsCheckBox.setToolTip(_translate("PropertiesDialog", "Select to create a version controlled project"))
        self.vcsCheckBox.setText(_translate("PropertiesDialog", "Version Controlled Project"))
        self.vcsInfoButton.setToolTip(_translate("PropertiesDialog", "Press to show information about the repository"))
        self.vcsInfoButton.setText(_translate("PropertiesDialog", "Show &Repository Info"))
        self.vcsInfoButton.setShortcut(_translate("PropertiesDialog", "Alt+R"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PropertiesDialog = QtWidgets.QDialog()
    ui = Ui_PropertiesDialog()
    ui.setupUi(PropertiesDialog)
    PropertiesDialog.show()
    sys.exit(app.exec_())

