# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\QScintilla\ReplaceWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReplaceWidget(object):
    def setupUi(self, ReplaceWidget):
        ReplaceWidget.setObjectName("ReplaceWidget")
        ReplaceWidget.resize(813, 56)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReplaceWidget.sizePolicy().hasHeightForWidth())
        ReplaceWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(ReplaceWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.closeButton = QtWidgets.QToolButton(ReplaceWidget)
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(ReplaceWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.findtextCombo = QtWidgets.QComboBox(ReplaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findtextCombo.sizePolicy().hasHeightForWidth())
        self.findtextCombo.setSizePolicy(sizePolicy)
        self.findtextCombo.setMinimumSize(QtCore.QSize(300, 0))
        self.findtextCombo.setEditable(True)
        self.findtextCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.findtextCombo.setDuplicatesEnabled(False)
        self.findtextCombo.setObjectName("findtextCombo")
        self.gridLayout.addWidget(self.findtextCombo, 0, 2, 1, 1)
        self.findPrevButton = QtWidgets.QToolButton(ReplaceWidget)
        self.findPrevButton.setObjectName("findPrevButton")
        self.gridLayout.addWidget(self.findPrevButton, 0, 3, 1, 1)
        self.findNextButton = QtWidgets.QToolButton(ReplaceWidget)
        self.findNextButton.setObjectName("findNextButton")
        self.gridLayout.addWidget(self.findNextButton, 0, 4, 1, 1)
        self.caseCheckBox = QtWidgets.QCheckBox(ReplaceWidget)
        self.caseCheckBox.setObjectName("caseCheckBox")
        self.gridLayout.addWidget(self.caseCheckBox, 0, 6, 1, 1)
        self.wordCheckBox = QtWidgets.QCheckBox(ReplaceWidget)
        self.wordCheckBox.setObjectName("wordCheckBox")
        self.gridLayout.addWidget(self.wordCheckBox, 0, 7, 1, 1)
        self.regexpCheckBox = QtWidgets.QCheckBox(ReplaceWidget)
        self.regexpCheckBox.setObjectName("regexpCheckBox")
        self.gridLayout.addWidget(self.regexpCheckBox, 0, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(ReplaceWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.replacetextCombo = QtWidgets.QComboBox(ReplaceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replacetextCombo.sizePolicy().hasHeightForWidth())
        self.replacetextCombo.setSizePolicy(sizePolicy)
        self.replacetextCombo.setMinimumSize(QtCore.QSize(300, 0))
        self.replacetextCombo.setEditable(True)
        self.replacetextCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.replacetextCombo.setDuplicatesEnabled(False)
        self.replacetextCombo.setObjectName("replacetextCombo")
        self.gridLayout.addWidget(self.replacetextCombo, 1, 2, 1, 1)
        self.replaceButton = QtWidgets.QToolButton(ReplaceWidget)
        self.replaceButton.setObjectName("replaceButton")
        self.gridLayout.addWidget(self.replaceButton, 1, 3, 1, 1)
        self.replaceSearchButton = QtWidgets.QToolButton(ReplaceWidget)
        self.replaceSearchButton.setObjectName("replaceSearchButton")
        self.gridLayout.addWidget(self.replaceSearchButton, 1, 4, 1, 1)
        self.replaceAllButton = QtWidgets.QToolButton(ReplaceWidget)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.gridLayout.addWidget(self.replaceAllButton, 1, 5, 1, 1)
        self.wrapCheckBox = QtWidgets.QCheckBox(ReplaceWidget)
        self.wrapCheckBox.setObjectName("wrapCheckBox")
        self.gridLayout.addWidget(self.wrapCheckBox, 1, 6, 1, 1)
        self.selectionCheckBox = QtWidgets.QCheckBox(ReplaceWidget)
        self.selectionCheckBox.setObjectName("selectionCheckBox")
        self.gridLayout.addWidget(self.selectionCheckBox, 1, 7, 1, 1)
        self.label.setBuddy(self.findtextCombo)
        self.label_2.setBuddy(self.replacetextCombo)

        self.retranslateUi(ReplaceWidget)
        QtCore.QMetaObject.connectSlotsByName(ReplaceWidget)
        ReplaceWidget.setTabOrder(self.findtextCombo, self.replacetextCombo)
        ReplaceWidget.setTabOrder(self.replacetextCombo, self.caseCheckBox)
        ReplaceWidget.setTabOrder(self.caseCheckBox, self.wordCheckBox)
        ReplaceWidget.setTabOrder(self.wordCheckBox, self.regexpCheckBox)
        ReplaceWidget.setTabOrder(self.regexpCheckBox, self.wrapCheckBox)
        ReplaceWidget.setTabOrder(self.wrapCheckBox, self.selectionCheckBox)
        ReplaceWidget.setTabOrder(self.selectionCheckBox, self.findNextButton)
        ReplaceWidget.setTabOrder(self.findNextButton, self.findPrevButton)
        ReplaceWidget.setTabOrder(self.findPrevButton, self.replaceButton)
        ReplaceWidget.setTabOrder(self.replaceButton, self.replaceSearchButton)
        ReplaceWidget.setTabOrder(self.replaceSearchButton, self.replaceAllButton)
        ReplaceWidget.setTabOrder(self.replaceAllButton, self.closeButton)

    def retranslateUi(self, ReplaceWidget):
        _translate = QtCore.QCoreApplication.translate
        ReplaceWidget.setWindowTitle(_translate("ReplaceWidget", "Find and Replace"))
        self.closeButton.setToolTip(_translate("ReplaceWidget", "Press to close the window"))
        self.label.setText(_translate("ReplaceWidget", "&Find:"))
        self.findPrevButton.setToolTip(_translate("ReplaceWidget", "Press to find the previous occurrence"))
        self.findNextButton.setToolTip(_translate("ReplaceWidget", "Press to find the next occurrence"))
        self.caseCheckBox.setText(_translate("ReplaceWidget", "&Match case"))
        self.wordCheckBox.setText(_translate("ReplaceWidget", "Whole &word"))
        self.regexpCheckBox.setText(_translate("ReplaceWidget", "Rege&xp"))
        self.label_2.setText(_translate("ReplaceWidget", "&Replace:"))
        self.replaceButton.setToolTip(_translate("ReplaceWidget", "Press to replace the selection"))
        self.replaceSearchButton.setToolTip(_translate("ReplaceWidget", "Press to replace the selection and search for the next occurence"))
        self.replaceAllButton.setToolTip(_translate("ReplaceWidget", "Press to replace all occurrences"))
        self.wrapCheckBox.setText(_translate("ReplaceWidget", "Wrap &around"))
        self.selectionCheckBox.setText(_translate("ReplaceWidget", "&Selection only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReplaceWidget = QtWidgets.QWidget()
    ui = Ui_ReplaceWidget()
    ui.setupUi(ReplaceWidget)
    ReplaceWidget.show()
    sys.exit(app.exec_())

