# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\E5Network\E5NetworkMonitor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_E5NetworkMonitor(object):
    def setupUi(self, E5NetworkMonitor):
        E5NetworkMonitor.setObjectName("E5NetworkMonitor")
        E5NetworkMonitor.resize(800, 600)
        E5NetworkMonitor.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(E5NetworkMonitor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(E5NetworkMonitor)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = E5ClearableLineEdit(E5NetworkMonitor)
        self.searchEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.requestsList = E5TableView(E5NetworkMonitor)
        self.requestsList.setAlternatingRowColors(True)
        self.requestsList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.requestsList.setShowGrid(False)
        self.requestsList.setSortingEnabled(False)
        self.requestsList.setObjectName("requestsList")
        self.verticalLayout_3.addWidget(self.requestsList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.removeButton = QtWidgets.QPushButton(E5NetworkMonitor)
        self.removeButton.setAutoDefault(False)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_3.addWidget(self.removeButton)
        self.removeAllButton = QtWidgets.QPushButton(E5NetworkMonitor)
        self.removeAllButton.setAutoDefault(False)
        self.removeAllButton.setObjectName("removeAllButton")
        self.horizontalLayout_3.addWidget(self.removeAllButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(E5NetworkMonitor)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.requestHeadersList = QtWidgets.QTableView(self.layoutWidget)
        self.requestHeadersList.setAlternatingRowColors(True)
        self.requestHeadersList.setShowGrid(False)
        self.requestHeadersList.setSortingEnabled(False)
        self.requestHeadersList.setObjectName("requestHeadersList")
        self.verticalLayout.addWidget(self.requestHeadersList)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.responseHeadersList = QtWidgets.QTableView(self.layoutWidget1)
        self.responseHeadersList.setAlternatingRowColors(True)
        self.responseHeadersList.setShowGrid(False)
        self.responseHeadersList.setSortingEnabled(False)
        self.responseHeadersList.setObjectName("responseHeadersList")
        self.verticalLayout_2.addWidget(self.responseHeadersList)
        self.verticalLayout_3.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(E5NetworkMonitor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(E5NetworkMonitor)
        self.buttonBox.accepted.connect(E5NetworkMonitor.accept)
        self.buttonBox.rejected.connect(E5NetworkMonitor.reject)
        QtCore.QMetaObject.connectSlotsByName(E5NetworkMonitor)
        E5NetworkMonitor.setTabOrder(self.searchEdit, self.requestsList)
        E5NetworkMonitor.setTabOrder(self.requestsList, self.removeButton)
        E5NetworkMonitor.setTabOrder(self.removeButton, self.removeAllButton)
        E5NetworkMonitor.setTabOrder(self.removeAllButton, self.requestHeadersList)
        E5NetworkMonitor.setTabOrder(self.requestHeadersList, self.responseHeadersList)
        E5NetworkMonitor.setTabOrder(self.responseHeadersList, self.buttonBox)

    def retranslateUi(self, E5NetworkMonitor):
        _translate = QtCore.QCoreApplication.translate
        E5NetworkMonitor.setWindowTitle(_translate("E5NetworkMonitor", "Network Monitor"))
        self.label.setText(_translate("E5NetworkMonitor", "Network Requests"))
        self.searchEdit.setToolTip(_translate("E5NetworkMonitor", "Enter search term for requests"))
        self.removeButton.setToolTip(_translate("E5NetworkMonitor", "Press to remove the selected requests"))
        self.removeButton.setText(_translate("E5NetworkMonitor", "&Remove"))
        self.removeAllButton.setToolTip(_translate("E5NetworkMonitor", "Press to remove all requests"))
        self.removeAllButton.setText(_translate("E5NetworkMonitor", "Remove &All"))
        self.label_2.setText(_translate("E5NetworkMonitor", "Request Headers"))
        self.label_3.setText(_translate("E5NetworkMonitor", "Response Headers"))

from E5Gui.E5LineEdit import E5ClearableLineEdit
from E5Gui.E5TableView import E5TableView

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    E5NetworkMonitor = QtWidgets.QDialog()
    ui = Ui_E5NetworkMonitor()
    ui.setupUi(E5NetworkMonitor)
    E5NetworkMonitor.show()
    sys.exit(app.exec_())

