# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\VcsPlugins\vcsMercurial\GpgExtension\HgGpgSignaturesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HgGpgSignaturesDialog(object):
    def setupUi(self, HgGpgSignaturesDialog):
        HgGpgSignaturesDialog.setObjectName("HgGpgSignaturesDialog")
        HgGpgSignaturesDialog.resize(700, 600)
        HgGpgSignaturesDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(HgGpgSignaturesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.categoryCombo = QtWidgets.QComboBox(HgGpgSignaturesDialog)
        self.categoryCombo.setObjectName("categoryCombo")
        self.categoryCombo.addItem("")
        self.categoryCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.categoryCombo)
        self.rxEdit = E5ClearableLineEdit(HgGpgSignaturesDialog)
        self.rxEdit.setObjectName("rxEdit")
        self.horizontalLayout_2.addWidget(self.rxEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.signaturesList = QtWidgets.QTreeWidget(HgGpgSignaturesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.signaturesList.sizePolicy().hasHeightForWidth())
        self.signaturesList.setSizePolicy(sizePolicy)
        self.signaturesList.setAlternatingRowColors(True)
        self.signaturesList.setRootIsDecorated(False)
        self.signaturesList.setHeaderHidden(True)
        self.signaturesList.setObjectName("signaturesList")
        self.signaturesList.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.signaturesList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verifyButton = QtWidgets.QPushButton(HgGpgSignaturesDialog)
        self.verifyButton.setEnabled(False)
        self.verifyButton.setObjectName("verifyButton")
        self.horizontalLayout.addWidget(self.verifyButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.errorGroup = QtWidgets.QGroupBox(HgGpgSignaturesDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.errorGroup.sizePolicy().hasHeightForWidth())
        self.errorGroup.setSizePolicy(sizePolicy)
        self.errorGroup.setObjectName("errorGroup")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.errorGroup)
        self.vboxlayout.setObjectName("vboxlayout")
        self.errors = QtWidgets.QTextEdit(self.errorGroup)
        self.errors.setReadOnly(True)
        self.errors.setAcceptRichText(False)
        self.errors.setObjectName("errors")
        self.vboxlayout.addWidget(self.errors)
        self.verticalLayout.addWidget(self.errorGroup)
        self.inputGroup = QtWidgets.QGroupBox(HgGpgSignaturesDialog)
        self.inputGroup.setObjectName("inputGroup")
        self._2 = QtWidgets.QGridLayout(self.inputGroup)
        self._2.setObjectName("_2")
        spacerItem3 = QtWidgets.QSpacerItem(327, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem3, 1, 1, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.inputGroup)
        self.sendButton.setObjectName("sendButton")
        self._2.addWidget(self.sendButton, 1, 2, 1, 1)
        self.input = QtWidgets.QLineEdit(self.inputGroup)
        self.input.setObjectName("input")
        self._2.addWidget(self.input, 0, 0, 1, 3)
        self.passwordCheckBox = QtWidgets.QCheckBox(self.inputGroup)
        self.passwordCheckBox.setObjectName("passwordCheckBox")
        self._2.addWidget(self.passwordCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.inputGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(HgGpgSignaturesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HgGpgSignaturesDialog)
        QtCore.QMetaObject.connectSlotsByName(HgGpgSignaturesDialog)
        HgGpgSignaturesDialog.setTabOrder(self.categoryCombo, self.rxEdit)
        HgGpgSignaturesDialog.setTabOrder(self.rxEdit, self.signaturesList)
        HgGpgSignaturesDialog.setTabOrder(self.signaturesList, self.verifyButton)
        HgGpgSignaturesDialog.setTabOrder(self.verifyButton, self.errors)
        HgGpgSignaturesDialog.setTabOrder(self.errors, self.input)
        HgGpgSignaturesDialog.setTabOrder(self.input, self.passwordCheckBox)
        HgGpgSignaturesDialog.setTabOrder(self.passwordCheckBox, self.sendButton)
        HgGpgSignaturesDialog.setTabOrder(self.sendButton, self.buttonBox)

    def retranslateUi(self, HgGpgSignaturesDialog):
        _translate = QtCore.QCoreApplication.translate
        HgGpgSignaturesDialog.setWindowTitle(_translate("HgGpgSignaturesDialog", "Signed Changesets"))
        self.categoryCombo.setToolTip(_translate("HgGpgSignaturesDialog", "Select the category to filter on"))
        self.categoryCombo.setItemText(0, _translate("HgGpgSignaturesDialog", "Revision"))
        self.categoryCombo.setItemText(1, _translate("HgGpgSignaturesDialog", "Signature"))
        self.rxEdit.setToolTip(_translate("HgGpgSignaturesDialog", "Enter the regular expression to filter on"))
        self.verifyButton.setToolTip(_translate("HgGpgSignaturesDialog", "Press to verify the signatures of the selected revision"))
        self.verifyButton.setText(_translate("HgGpgSignaturesDialog", "&Verify..."))
        self.errorGroup.setTitle(_translate("HgGpgSignaturesDialog", "Errors"))
        self.errors.setWhatsThis(_translate("HgGpgSignaturesDialog", "<b>Mercurial errors</b><p>This shows possible error messages.</p>"))
        self.inputGroup.setTitle(_translate("HgGpgSignaturesDialog", "Input"))
        self.sendButton.setToolTip(_translate("HgGpgSignaturesDialog", "Press to send the input to the hg process"))
        self.sendButton.setText(_translate("HgGpgSignaturesDialog", "&Send"))
        self.sendButton.setShortcut(_translate("HgGpgSignaturesDialog", "Alt+S"))
        self.input.setToolTip(_translate("HgGpgSignaturesDialog", "Enter data to be sent to the hg process"))
        self.passwordCheckBox.setToolTip(_translate("HgGpgSignaturesDialog", "Select to switch the input field to password mode"))
        self.passwordCheckBox.setText(_translate("HgGpgSignaturesDialog", "&Password Mode"))
        self.passwordCheckBox.setShortcut(_translate("HgGpgSignaturesDialog", "Alt+P"))

from E5Gui.E5LineEdit import E5ClearableLineEdit

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HgGpgSignaturesDialog = QtWidgets.QDialog()
    ui = Ui_HgGpgSignaturesDialog()
    ui.setupUi(HgGpgSignaturesDialog)
    HgGpgSignaturesDialog.show()
    sys.exit(app.exec_())

