# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\WebBrowser\WebBrowserClearPrivateDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WebBrowserClearPrivateDataDialog(object):
    def setupUi(self, WebBrowserClearPrivateDataDialog):
        WebBrowserClearPrivateDataDialog.setObjectName("WebBrowserClearPrivateDataDialog")
        WebBrowserClearPrivateDataDialog.resize(305, 380)
        WebBrowserClearPrivateDataDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WebBrowserClearPrivateDataDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.historyCheckBox.setChecked(True)
        self.historyCheckBox.setObjectName("historyCheckBox")
        self.verticalLayout.addWidget(self.historyCheckBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.historyCombo = QtWidgets.QComboBox(WebBrowserClearPrivateDataDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyCombo.sizePolicy().hasHeightForWidth())
        self.historyCombo.setSizePolicy(sizePolicy)
        self.historyCombo.setObjectName("historyCombo")
        self.historyCombo.addItem("")
        self.historyCombo.addItem("")
        self.historyCombo.addItem("")
        self.historyCombo.addItem("")
        self.historyCombo.addItem("")
        self.horizontalLayout.addWidget(self.historyCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.searchCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.searchCheckBox.setChecked(True)
        self.searchCheckBox.setObjectName("searchCheckBox")
        self.verticalLayout.addWidget(self.searchCheckBox)
        self.downloadsCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.downloadsCheckBox.setChecked(True)
        self.downloadsCheckBox.setObjectName("downloadsCheckBox")
        self.verticalLayout.addWidget(self.downloadsCheckBox)
        self.cookiesCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.cookiesCheckBox.setChecked(True)
        self.cookiesCheckBox.setObjectName("cookiesCheckBox")
        self.verticalLayout.addWidget(self.cookiesCheckBox)
        self.cacheCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.cacheCheckBox.setChecked(True)
        self.cacheCheckBox.setObjectName("cacheCheckBox")
        self.verticalLayout.addWidget(self.cacheCheckBox)
        self.iconsCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.iconsCheckBox.setChecked(True)
        self.iconsCheckBox.setObjectName("iconsCheckBox")
        self.verticalLayout.addWidget(self.iconsCheckBox)
        self.passwordsCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.passwordsCheckBox.setChecked(False)
        self.passwordsCheckBox.setObjectName("passwordsCheckBox")
        self.verticalLayout.addWidget(self.passwordsCheckBox)
        self.databasesCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.databasesCheckBox.setObjectName("databasesCheckBox")
        self.verticalLayout.addWidget(self.databasesCheckBox)
        self.zoomCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.zoomCheckBox.setChecked(True)
        self.zoomCheckBox.setObjectName("zoomCheckBox")
        self.verticalLayout.addWidget(self.zoomCheckBox)
        self.sslExceptionsCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.sslExceptionsCheckBox.setChecked(True)
        self.sslExceptionsCheckBox.setObjectName("sslExceptionsCheckBox")
        self.verticalLayout.addWidget(self.sslExceptionsCheckBox)
        self.line = QtWidgets.QFrame(WebBrowserClearPrivateDataDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.flashCookiesCheckBox = QtWidgets.QCheckBox(WebBrowserClearPrivateDataDialog)
        self.flashCookiesCheckBox.setObjectName("flashCookiesCheckBox")
        self.verticalLayout.addWidget(self.flashCookiesCheckBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(WebBrowserClearPrivateDataDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(WebBrowserClearPrivateDataDialog)
        self.buttonBox.accepted.connect(WebBrowserClearPrivateDataDialog.accept)
        self.buttonBox.rejected.connect(WebBrowserClearPrivateDataDialog.reject)
        self.historyCheckBox.toggled['bool'].connect(self.historyCombo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(WebBrowserClearPrivateDataDialog)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.historyCheckBox, self.historyCombo)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.historyCombo, self.searchCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.searchCheckBox, self.downloadsCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.downloadsCheckBox, self.cookiesCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.cookiesCheckBox, self.cacheCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.cacheCheckBox, self.iconsCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.iconsCheckBox, self.passwordsCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.passwordsCheckBox, self.databasesCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.databasesCheckBox, self.zoomCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.zoomCheckBox, self.sslExceptionsCheckBox)
        WebBrowserClearPrivateDataDialog.setTabOrder(self.sslExceptionsCheckBox, self.flashCookiesCheckBox)

    def retranslateUi(self, WebBrowserClearPrivateDataDialog):
        _translate = QtCore.QCoreApplication.translate
        WebBrowserClearPrivateDataDialog.setWindowTitle(_translate("WebBrowserClearPrivateDataDialog", "Clear Private Data"))
        self.historyCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the browsing history"))
        self.historyCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "&Browsing History"))
        self.historyCombo.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select the history period to be deleted"))
        self.historyCombo.setItemText(0, _translate("WebBrowserClearPrivateDataDialog", "Last Hour"))
        self.historyCombo.setItemText(1, _translate("WebBrowserClearPrivateDataDialog", "Last Day"))
        self.historyCombo.setItemText(2, _translate("WebBrowserClearPrivateDataDialog", "Last Week"))
        self.historyCombo.setItemText(3, _translate("WebBrowserClearPrivateDataDialog", "Last 4 Weeks"))
        self.historyCombo.setItemText(4, _translate("WebBrowserClearPrivateDataDialog", "Whole Period"))
        self.searchCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the search history"))
        self.searchCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "&Search History"))
        self.downloadsCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the download history"))
        self.downloadsCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Download &History"))
        self.cookiesCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the cookies"))
        self.cookiesCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "&Cookies"))
        self.cacheCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the disk cache"))
        self.cacheCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Cached &Web Pages"))
        self.iconsCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the website icons"))
        self.iconsCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Website &Icons"))
        self.passwordsCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear the saved passwords"))
        self.passwordsCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Saved &Passwords"))
        self.databasesCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to delete all web databases"))
        self.databasesCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Web &Databases"))
        self.zoomCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to delete all remembered zoom settings"))
        self.zoomCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "&Zoom Settings"))
        self.sslExceptionsCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "SSL Certificate Error Exceptions"))
        self.flashCookiesCheckBox.setToolTip(_translate("WebBrowserClearPrivateDataDialog", "Select to clear cookies set by the Adobe Flash Player"))
        self.flashCookiesCheckBox.setText(_translate("WebBrowserClearPrivateDataDialog", "Cookies from Adobe &Flash Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WebBrowserClearPrivateDataDialog = QtWidgets.QDialog()
    ui = Ui_WebBrowserClearPrivateDataDialog()
    ui.setupUi(WebBrowserClearPrivateDataDialog)
    WebBrowserClearPrivateDataDialog.show()
    sys.exit(app.exec_())

