# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\PyUnit\UnittestDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UnittestDialog(object):
    def setupUi(self, UnittestDialog):
        UnittestDialog.setObjectName("UnittestDialog")
        UnittestDialog.resize(650, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(UnittestDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(UnittestDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.testsuiteLabel = QtWidgets.QLabel(self.groupBox)
        self.testsuiteLabel.setObjectName("testsuiteLabel")
        self.gridLayout.addWidget(self.testsuiteLabel, 0, 0, 1, 1)
        self.testsuitePicker = E5ComboPathPicker(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testsuitePicker.sizePolicy().hasHeightForWidth())
        self.testsuitePicker.setSizePolicy(sizePolicy)
        self.testsuitePicker.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.testsuitePicker.setObjectName("testsuitePicker")
        self.gridLayout.addWidget(self.testsuitePicker, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.testComboBox = QtWidgets.QComboBox(self.groupBox)
        self.testComboBox.setEditable(True)
        self.testComboBox.setObjectName("testComboBox")
        self.gridLayout.addWidget(self.testComboBox, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.optionsGroup = QtWidgets.QGroupBox(UnittestDialog)
        self.optionsGroup.setObjectName("optionsGroup")
        self._5 = QtWidgets.QHBoxLayout(self.optionsGroup)
        self._5.setObjectName("_5")
        self.localCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.localCheckBox.setObjectName("localCheckBox")
        self._5.addWidget(self.localCheckBox)
        self.coverageCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.coverageCheckBox.setObjectName("coverageCheckBox")
        self._5.addWidget(self.coverageCheckBox)
        self.coverageEraseCheckBox = QtWidgets.QCheckBox(self.optionsGroup)
        self.coverageEraseCheckBox.setEnabled(False)
        self.coverageEraseCheckBox.setObjectName("coverageEraseCheckBox")
        self._5.addWidget(self.coverageEraseCheckBox)
        self.verticalLayout_2.addWidget(self.optionsGroup)
        self.progressGroupBox = QtWidgets.QGroupBox(UnittestDialog)
        self.progressGroupBox.setObjectName("progressGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.progressGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self._8 = QtWidgets.QHBoxLayout()
        self._8.setObjectName("_8")
        self.progressTextLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressTextLabel.setObjectName("progressTextLabel")
        self._8.addWidget(self.progressTextLabel)
        spacerItem = QtWidgets.QSpacerItem(371, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._8.addItem(spacerItem)
        self.progressLed = E5Led(self.progressGroupBox)
        self.progressLed.setObjectName("progressLed")
        self._8.addWidget(self.progressLed)
        self.verticalLayout.addLayout(self._8)
        self.progressProgressBar = QtWidgets.QProgressBar(self.progressGroupBox)
        self.progressProgressBar.setProperty("value", 0)
        self.progressProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressProgressBar.setObjectName("progressProgressBar")
        self.verticalLayout.addWidget(self.progressProgressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressCounterRunLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterRunLabel.setObjectName("progressCounterRunLabel")
        self.horizontalLayout_2.addWidget(self.progressCounterRunLabel)
        self.progressCounterRunCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterRunCount.setText("0")
        self.progressCounterRunCount.setObjectName("progressCounterRunCount")
        self.horizontalLayout_2.addWidget(self.progressCounterRunCount)
        self.progressCounterRemLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterRemLabel.setObjectName("progressCounterRemLabel")
        self.horizontalLayout_2.addWidget(self.progressCounterRemLabel)
        self.progressCounterRemCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterRemCount.setText("0")
        self.progressCounterRemCount.setObjectName("progressCounterRemCount")
        self.horizontalLayout_2.addWidget(self.progressCounterRemCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressCounterFailureLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterFailureLabel.setObjectName("progressCounterFailureLabel")
        self.horizontalLayout.addWidget(self.progressCounterFailureLabel)
        self.progressCounterFailureCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterFailureCount.setText("0")
        self.progressCounterFailureCount.setObjectName("progressCounterFailureCount")
        self.horizontalLayout.addWidget(self.progressCounterFailureCount)
        self.progressCounterErrorLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterErrorLabel.setObjectName("progressCounterErrorLabel")
        self.horizontalLayout.addWidget(self.progressCounterErrorLabel)
        self.progressCounterErrorCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterErrorCount.setText("0")
        self.progressCounterErrorCount.setObjectName("progressCounterErrorCount")
        self.horizontalLayout.addWidget(self.progressCounterErrorCount)
        self.progressCounterSkippedLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterSkippedLabel.setObjectName("progressCounterSkippedLabel")
        self.horizontalLayout.addWidget(self.progressCounterSkippedLabel)
        self.progressCounterSkippedCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterSkippedCount.setText("0")
        self.progressCounterSkippedCount.setObjectName("progressCounterSkippedCount")
        self.horizontalLayout.addWidget(self.progressCounterSkippedCount)
        self.progressCounterExpectedFailureLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterExpectedFailureLabel.setObjectName("progressCounterExpectedFailureLabel")
        self.horizontalLayout.addWidget(self.progressCounterExpectedFailureLabel)
        self.progressCounterExpectedFailureCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterExpectedFailureCount.setText("0")
        self.progressCounterExpectedFailureCount.setObjectName("progressCounterExpectedFailureCount")
        self.horizontalLayout.addWidget(self.progressCounterExpectedFailureCount)
        self.progressCounterUnexpectedSuccessLabel = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterUnexpectedSuccessLabel.setObjectName("progressCounterUnexpectedSuccessLabel")
        self.horizontalLayout.addWidget(self.progressCounterUnexpectedSuccessLabel)
        self.progressCounterUnexpectedSuccessCount = QtWidgets.QLabel(self.progressGroupBox)
        self.progressCounterUnexpectedSuccessCount.setText("0")
        self.progressCounterUnexpectedSuccessCount.setObjectName("progressCounterUnexpectedSuccessCount")
        self.horizontalLayout.addWidget(self.progressCounterUnexpectedSuccessCount)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.progressGroupBox)
        self.textLabel1 = QtWidgets.QLabel(UnittestDialog)
        self.textLabel1.setObjectName("textLabel1")
        self.verticalLayout_2.addWidget(self.textLabel1)
        self.testsListWidget = QtWidgets.QListWidget(UnittestDialog)
        self.testsListWidget.setObjectName("testsListWidget")
        self.verticalLayout_2.addWidget(self.testsListWidget)
        self.listboxLabel = QtWidgets.QLabel(UnittestDialog)
        self.listboxLabel.setObjectName("listboxLabel")
        self.verticalLayout_2.addWidget(self.listboxLabel)
        self.errorsListWidget = QtWidgets.QListWidget(UnittestDialog)
        self.errorsListWidget.setObjectName("errorsListWidget")
        self.verticalLayout_2.addWidget(self.errorsListWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(UnittestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.sbLabel = QtWidgets.QLabel(UnittestDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbLabel.sizePolicy().hasHeightForWidth())
        self.sbLabel.setSizePolicy(sizePolicy)
        self.sbLabel.setObjectName("sbLabel")
        self._3.addWidget(self.sbLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self._3)
        self.testsuiteLabel.setBuddy(self.testsuitePicker)
        self.label.setBuddy(self.testComboBox)

        self.retranslateUi(UnittestDialog)
        self.coverageCheckBox.toggled['bool'].connect(self.coverageEraseCheckBox.setEnabled)
        self.buttonBox.accepted.connect(UnittestDialog.close)
        self.buttonBox.rejected.connect(UnittestDialog.close)
        QtCore.QMetaObject.connectSlotsByName(UnittestDialog)
        UnittestDialog.setTabOrder(self.testsuitePicker, self.testComboBox)
        UnittestDialog.setTabOrder(self.testComboBox, self.localCheckBox)
        UnittestDialog.setTabOrder(self.localCheckBox, self.coverageCheckBox)
        UnittestDialog.setTabOrder(self.coverageCheckBox, self.coverageEraseCheckBox)
        UnittestDialog.setTabOrder(self.coverageEraseCheckBox, self.testsListWidget)
        UnittestDialog.setTabOrder(self.testsListWidget, self.errorsListWidget)

    def retranslateUi(self, UnittestDialog):
        _translate = QtCore.QCoreApplication.translate
        UnittestDialog.setWindowTitle(_translate("UnittestDialog", "Unittest"))
        self.groupBox.setTitle(_translate("UnittestDialog", "Test Parameters"))
        self.testsuiteLabel.setText(_translate("UnittestDialog", "Enter test &filename:"))
        self.testsuitePicker.setToolTip(_translate("UnittestDialog", "Enter name of file defining the testsuite"))
        self.testsuitePicker.setWhatsThis(_translate("UnittestDialog", "<b>Testsuite</b>\n"
"<p>Enter the name of the file defining the testsuite.\n"
"It should have a method with a name given below. If no name is given, the suite() method will be tried. If no such method can be\n"
"found, the module will be inspected for proper test\n"
"cases.</p>"))
        self.label.setText(_translate("UnittestDialog", "Enter &test name:"))
        self.testComboBox.setToolTip(_translate("UnittestDialog", "Enter the test name. Leave empty to use the default name \"suite\"."))
        self.testComboBox.setWhatsThis(_translate("UnittestDialog", "<b>Testname</b><p>Enter the name of the test to be performed. This name must follow the rules given by Python\'s unittest module. If this field is empty, the default name of \"suite\" will be used.</p>"))
        self.optionsGroup.setTitle(_translate("UnittestDialog", "Run Parameters"))
        self.localCheckBox.setToolTip(_translate("UnittestDialog", "Select whether you want to run the test locally"))
        self.localCheckBox.setText(_translate("UnittestDialog", "Run &local"))
        self.coverageCheckBox.setToolTip(_translate("UnittestDialog", "Select whether coverage data should be collected"))
        self.coverageCheckBox.setText(_translate("UnittestDialog", "C&ollect coverage data"))
        self.coverageEraseCheckBox.setToolTip(_translate("UnittestDialog", "Select whether old coverage data should be erased"))
        self.coverageEraseCheckBox.setText(_translate("UnittestDialog", "&Erase coverage data"))
        self.progressGroupBox.setTitle(_translate("UnittestDialog", "Progress"))
        self.progressTextLabel.setText(_translate("UnittestDialog", "Progress:"))
        self.progressProgressBar.setFormat(_translate("UnittestDialog", "%v/%m Tests"))
        self.progressCounterRunLabel.setText(_translate("UnittestDialog", "Run:"))
        self.progressCounterRunCount.setToolTip(_translate("UnittestDialog", "Number of tests run"))
        self.progressCounterRemLabel.setText(_translate("UnittestDialog", "Remaining:"))
        self.progressCounterRemCount.setToolTip(_translate("UnittestDialog", "Number of tests to be run"))
        self.progressCounterFailureLabel.setText(_translate("UnittestDialog", "Failures:"))
        self.progressCounterFailureCount.setToolTip(_translate("UnittestDialog", "Number of test failures"))
        self.progressCounterErrorLabel.setText(_translate("UnittestDialog", "Errors:"))
        self.progressCounterErrorCount.setToolTip(_translate("UnittestDialog", "Number of test errors"))
        self.progressCounterSkippedLabel.setText(_translate("UnittestDialog", "Skipped:"))
        self.progressCounterSkippedCount.setToolTip(_translate("UnittestDialog", "Number of tests skipped"))
        self.progressCounterExpectedFailureLabel.setText(_translate("UnittestDialog", "Expected Failures:"))
        self.progressCounterExpectedFailureCount.setToolTip(_translate("UnittestDialog", "Number of tests with expected failure"))
        self.progressCounterUnexpectedSuccessLabel.setText(_translate("UnittestDialog", "Unexpected Successes:"))
        self.progressCounterUnexpectedSuccessCount.setToolTip(_translate("UnittestDialog", "Number of tests with unexpected success"))
        self.textLabel1.setText(_translate("UnittestDialog", "Tests performed:"))
        self.listboxLabel.setText(_translate("UnittestDialog", "Failures and errors:"))
        self.errorsListWidget.setToolTip(_translate("UnittestDialog", "Failures and Errors list"))
        self.errorsListWidget.setWhatsThis(_translate("UnittestDialog", "<b>Failures and Errors list</b>\n"
"<p>This list shows all failed and errored tests.\n"
"Double clicking on an entry will show the respective traceback.</p>"))
        self.sbLabel.setText(_translate("UnittestDialog", "Idle"))

from E5Gui.E5Led import E5Led
from E5Gui.E5PathPicker import E5ComboPathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UnittestDialog = QtWidgets.QWidget()
    ui = Ui_UnittestDialog()
    ui.setupUi(UnittestDialog)
    UnittestDialog.show()
    sys.exit(app.exec_())

