# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Helpviewer\FlashCookieManager\FlashCookieManagerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlashCookieManagerDialog(object):
    def setupUi(self, FlashCookieManagerDialog):
        FlashCookieManagerDialog.setObjectName("FlashCookieManagerDialog")
        FlashCookieManagerDialog.resize(550, 500)
        FlashCookieManagerDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(FlashCookieManagerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cookiesTabWidget = QtWidgets.QTabWidget(FlashCookieManagerDialog)
        self.cookiesTabWidget.setObjectName("cookiesTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.filterEdit = QtWidgets.QLineEdit(self.tab)
        self.filterEdit.setObjectName("filterEdit")
        self.gridLayout.addWidget(self.filterEdit, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 0, 1, 2)
        self.cookiesList = QtWidgets.QTreeWidget(self.tab)
        self.cookiesList.setAlternatingRowColors(True)
        self.cookiesList.setObjectName("cookiesList")
        self.gridLayout.addWidget(self.cookiesList, 2, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.reloadButton = QtWidgets.QPushButton(self.tab)
        self.reloadButton.setObjectName("reloadButton")
        self.gridLayout_3.addWidget(self.reloadButton, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.tab)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 0, 1, 1, 1)
        self.labelSize_2 = QtWidgets.QLabel(self.tab)
        self.labelSize_2.setObjectName("labelSize_2")
        self.gridLayout_2.addWidget(self.labelSize_2, 1, 0, 1, 1)
        self.sizeLabel = QtWidgets.QLabel(self.tab)
        self.sizeLabel.setObjectName("sizeLabel")
        self.gridLayout_2.addWidget(self.sizeLabel, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.originLabel = QtWidgets.QLabel(self.tab)
        self.originLabel.setObjectName("originLabel")
        self.gridLayout_2.addWidget(self.originLabel, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        self.modifiedLabel = QtWidgets.QLabel(self.tab)
        self.modifiedLabel.setObjectName("modifiedLabel")
        self.gridLayout_2.addWidget(self.modifiedLabel, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 2)
        self.contentsEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.contentsEdit.setTabChangesFocus(True)
        self.contentsEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.contentsEdit.setReadOnly(True)
        self.contentsEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.contentsEdit.setObjectName("contentsEdit")
        self.gridLayout_3.addWidget(self.contentsEdit, 3, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pathEdit = QtWidgets.QLineEdit(self.tab)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.horizontalLayout_2.addWidget(self.pathEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.removeAllButton = QtWidgets.QPushButton(self.tab)
        self.removeAllButton.setObjectName("removeAllButton")
        self.horizontalLayout.addWidget(self.removeAllButton)
        self.removeButton = QtWidgets.QPushButton(self.tab)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.cookiesTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 1, 1, 1)
        self.whiteList = QtWidgets.QListWidget(self.tab_2)
        self.whiteList.setAlternatingRowColors(True)
        self.whiteList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.whiteList.setObjectName("whiteList")
        self.gridLayout_5.addWidget(self.whiteList, 2, 0, 1, 1)
        self.blackList = QtWidgets.QListWidget(self.tab_2)
        self.blackList.setAlternatingRowColors(True)
        self.blackList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.blackList.setObjectName("blackList")
        self.gridLayout_5.addWidget(self.blackList, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.removeWhiteButton = QtWidgets.QPushButton(self.tab_2)
        self.removeWhiteButton.setObjectName("removeWhiteButton")
        self.horizontalLayout_3.addWidget(self.removeWhiteButton)
        self.addWhiteButton = QtWidgets.QPushButton(self.tab_2)
        self.addWhiteButton.setObjectName("addWhiteButton")
        self.horizontalLayout_3.addWidget(self.addWhiteButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.removeBlackButton = QtWidgets.QPushButton(self.tab_2)
        self.removeBlackButton.setObjectName("removeBlackButton")
        self.horizontalLayout_4.addWidget(self.removeBlackButton)
        self.addBlackButton = QtWidgets.QPushButton(self.tab_2)
        self.addBlackButton.setObjectName("addBlackButton")
        self.horizontalLayout_4.addWidget(self.addBlackButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.cookiesTabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.cookiesTabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(FlashCookieManagerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FlashCookieManagerDialog)
        self.cookiesTabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FlashCookieManagerDialog.accept)
        self.buttonBox.rejected.connect(FlashCookieManagerDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FlashCookieManagerDialog)
        FlashCookieManagerDialog.setTabOrder(self.cookiesTabWidget, self.filterEdit)
        FlashCookieManagerDialog.setTabOrder(self.filterEdit, self.cookiesList)
        FlashCookieManagerDialog.setTabOrder(self.cookiesList, self.reloadButton)
        FlashCookieManagerDialog.setTabOrder(self.reloadButton, self.contentsEdit)
        FlashCookieManagerDialog.setTabOrder(self.contentsEdit, self.pathEdit)
        FlashCookieManagerDialog.setTabOrder(self.pathEdit, self.removeAllButton)
        FlashCookieManagerDialog.setTabOrder(self.removeAllButton, self.removeButton)
        FlashCookieManagerDialog.setTabOrder(self.removeButton, self.whiteList)
        FlashCookieManagerDialog.setTabOrder(self.whiteList, self.removeWhiteButton)
        FlashCookieManagerDialog.setTabOrder(self.removeWhiteButton, self.addWhiteButton)
        FlashCookieManagerDialog.setTabOrder(self.addWhiteButton, self.blackList)
        FlashCookieManagerDialog.setTabOrder(self.blackList, self.removeBlackButton)
        FlashCookieManagerDialog.setTabOrder(self.removeBlackButton, self.addBlackButton)

    def retranslateUi(self, FlashCookieManagerDialog):
        _translate = QtCore.QCoreApplication.translate
        FlashCookieManagerDialog.setWindowTitle(_translate("FlashCookieManagerDialog", "Flash Cookie Management"))
        self.label_4.setText(_translate("FlashCookieManagerDialog", "Filter:"))
        self.filterEdit.setToolTip(_translate("FlashCookieManagerDialog", "Enter cookie filter string"))
        self.label_24.setText(_translate("FlashCookieManagerDialog", "Stored Flash Cookies:"))
        self.cookiesList.headerItem().setText(0, _translate("FlashCookieManagerDialog", "Origin"))
        self.reloadButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to reload Flash cookies from disk"))
        self.reloadButton.setText(_translate("FlashCookieManagerDialog", "Reload"))
        self.label_6.setText(_translate("FlashCookieManagerDialog", "Name:"))
        self.nameLabel.setText(_translate("FlashCookieManagerDialog", "<no flash cookie selected>"))
        self.labelSize_2.setText(_translate("FlashCookieManagerDialog", "Size:"))
        self.sizeLabel.setText(_translate("FlashCookieManagerDialog", "<no flash cookie selected>"))
        self.label_7.setText(_translate("FlashCookieManagerDialog", "Origin:"))
        self.originLabel.setText(_translate("FlashCookieManagerDialog", "<no flash cookie selected>"))
        self.label_22.setText(_translate("FlashCookieManagerDialog", "Last Modified:"))
        self.modifiedLabel.setText(_translate("FlashCookieManagerDialog", "<no flash cookie selected>"))
        self.label.setText(_translate("FlashCookieManagerDialog", "Contents:"))
        self.label_2.setText(_translate("FlashCookieManagerDialog", "Path:"))
        self.removeAllButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to remove all flash cookies"))
        self.removeAllButton.setText(_translate("FlashCookieManagerDialog", "Remove All Cookies"))
        self.removeButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to remove selected flash cookies"))
        self.removeButton.setText(_translate("FlashCookieManagerDialog", "Remove Cookie"))
        self.cookiesTabWidget.setTabText(self.cookiesTabWidget.indexOf(self.tab), _translate("FlashCookieManagerDialog", "Stored Flash Cookies"))
        self.label_3.setText(_translate("FlashCookieManagerDialog", "<b>Flash cookie whitelist</b>"))
        self.label_5.setText(_translate("FlashCookieManagerDialog", "<b>Flash cookie blacklist</b>"))
        self.label_17.setText(_translate("FlashCookieManagerDialog", "Flash cookies from these origins will not be deleted automatically. (Also detection of them will not be notified to user.)"))
        self.label_18.setText(_translate("FlashCookieManagerDialog", "Flash cookies from these origins will be deleted without any notification."))
        self.whiteList.setSortingEnabled(True)
        self.blackList.setSortingEnabled(True)
        self.removeWhiteButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to remove selected origins from the whitelist"))
        self.removeWhiteButton.setText(_translate("FlashCookieManagerDialog", "Remove"))
        self.addWhiteButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to add an origin to the whitelist"))
        self.addWhiteButton.setText(_translate("FlashCookieManagerDialog", "Add..."))
        self.removeBlackButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to remove selected origins from the blacklist"))
        self.removeBlackButton.setText(_translate("FlashCookieManagerDialog", "Remove"))
        self.addBlackButton.setToolTip(_translate("FlashCookieManagerDialog", "Press to add an origin to the blacklist"))
        self.addBlackButton.setText(_translate("FlashCookieManagerDialog", "Add..."))
        self.cookiesTabWidget.setTabText(self.cookiesTabWidget.indexOf(self.tab_2), _translate("FlashCookieManagerDialog", "Flash Cookies Lists"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FlashCookieManagerDialog = QtWidgets.QDialog()
    ui = Ui_FlashCookieManagerDialog()
    ui.setupUi(FlashCookieManagerDialog)
    FlashCookieManagerDialog.show()
    sys.exit(app.exec_())

