# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\WizardPlugins\FontDialogWizard\FontDialogWizardDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FontDialogWizardDialog(object):
    def setupUi(self, FontDialogWizardDialog):
        FontDialogWizardDialog.setObjectName("FontDialogWizardDialog")
        FontDialogWizardDialog.resize(377, 291)
        FontDialogWizardDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(FontDialogWizardDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FontDialogWizardDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.eResultVar = QtWidgets.QLineEdit(FontDialogWizardDialog)
        self.eResultVar.setObjectName("eResultVar")
        self.verticalLayout.addWidget(self.eResultVar)
        self.textLabel1 = QtWidgets.QLabel(FontDialogWizardDialog)
        self.textLabel1.setObjectName("textLabel1")
        self.verticalLayout.addWidget(self.textLabel1)
        self.eCaption = QtWidgets.QLineEdit(FontDialogWizardDialog)
        self.eCaption.setObjectName("eCaption")
        self.verticalLayout.addWidget(self.eCaption)
        self.parentGroup = QtWidgets.QGroupBox(FontDialogWizardDialog)
        self.parentGroup.setObjectName("parentGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.parentGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parentSelf = QtWidgets.QRadioButton(self.parentGroup)
        self.parentSelf.setChecked(True)
        self.parentSelf.setObjectName("parentSelf")
        self.gridLayout_3.addWidget(self.parentSelf, 0, 0, 1, 1)
        self.parentNone = QtWidgets.QRadioButton(self.parentGroup)
        self.parentNone.setObjectName("parentNone")
        self.gridLayout_3.addWidget(self.parentNone, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.parentOther = QtWidgets.QRadioButton(self.parentGroup)
        self.parentOther.setObjectName("parentOther")
        self.horizontalLayout_2.addWidget(self.parentOther)
        self.parentEdit = QtWidgets.QLineEdit(self.parentGroup)
        self.parentEdit.setEnabled(False)
        self.parentEdit.setObjectName("parentEdit")
        self.horizontalLayout_2.addWidget(self.parentEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.parentGroup)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.fontButton = QtWidgets.QPushButton(FontDialogWizardDialog)
        self.fontButton.setObjectName("fontButton")
        self.hboxlayout.addWidget(self.fontButton)
        spacerItem1 = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.TextLabel1 = QtWidgets.QLabel(FontDialogWizardDialog)
        self.TextLabel1.setObjectName("TextLabel1")
        self.verticalLayout.addWidget(self.TextLabel1)
        self.eVariable = QtWidgets.QLineEdit(FontDialogWizardDialog)
        self.eVariable.setObjectName("eVariable")
        self.verticalLayout.addWidget(self.eVariable)
        self.buttonBox = QtWidgets.QDialogButtonBox(FontDialogWizardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FontDialogWizardDialog)
        self.buttonBox.accepted.connect(FontDialogWizardDialog.accept)
        self.buttonBox.rejected.connect(FontDialogWizardDialog.reject)
        self.parentOther.toggled['bool'].connect(self.parentEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FontDialogWizardDialog)
        FontDialogWizardDialog.setTabOrder(self.eResultVar, self.eCaption)
        FontDialogWizardDialog.setTabOrder(self.eCaption, self.parentSelf)
        FontDialogWizardDialog.setTabOrder(self.parentSelf, self.parentNone)
        FontDialogWizardDialog.setTabOrder(self.parentNone, self.parentOther)
        FontDialogWizardDialog.setTabOrder(self.parentOther, self.parentEdit)
        FontDialogWizardDialog.setTabOrder(self.parentEdit, self.fontButton)
        FontDialogWizardDialog.setTabOrder(self.fontButton, self.eVariable)
        FontDialogWizardDialog.setTabOrder(self.eVariable, self.buttonBox)

    def retranslateUi(self, FontDialogWizardDialog):
        _translate = QtCore.QCoreApplication.translate
        FontDialogWizardDialog.setWindowTitle(_translate("FontDialogWizardDialog", "QFontDialog Wizard"))
        self.label.setText(_translate("FontDialogWizardDialog", "Result:"))
        self.eResultVar.setToolTip(_translate("FontDialogWizardDialog", "Enter the result variable name"))
        self.textLabel1.setText(_translate("FontDialogWizardDialog", "Title:"))
        self.eCaption.setToolTip(_translate("FontDialogWizardDialog", "Enter the title for the message box"))
        self.parentGroup.setTitle(_translate("FontDialogWizardDialog", "Parent"))
        self.parentSelf.setToolTip(_translate("FontDialogWizardDialog", "Select \"self\" as parent"))
        self.parentSelf.setText(_translate("FontDialogWizardDialog", "self"))
        self.parentNone.setToolTip(_translate("FontDialogWizardDialog", "Select \"None\" as parent"))
        self.parentNone.setText(_translate("FontDialogWizardDialog", "None"))
        self.parentOther.setToolTip(_translate("FontDialogWizardDialog", "Select to enter a parent expression"))
        self.parentOther.setText(_translate("FontDialogWizardDialog", "Expression:"))
        self.parentEdit.setToolTip(_translate("FontDialogWizardDialog", "Enter the parent expression"))
        self.fontButton.setToolTip(_translate("FontDialogWizardDialog", "Press to select a font via a dialog"))
        self.fontButton.setText(_translate("FontDialogWizardDialog", "Select Font ..."))
        self.TextLabel1.setText(_translate("FontDialogWizardDialog", "Font Variable:"))
        self.eVariable.setToolTip(_translate("FontDialogWizardDialog", "Enter a variable name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FontDialogWizardDialog = QtWidgets.QDialog()
    ui = Ui_FontDialogWizardDialog()
    ui.setupUi(FontDialogWizardDialog)
    FontDialogWizardDialog.show()
    sys.exit(app.exec_())

