# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\VcsPlugins\vcsMercurial\ShelveExtension\HgShelveBrowserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HgShelveBrowserDialog(object):
    def setupUi(self, HgShelveBrowserDialog):
        HgShelveBrowserDialog.setObjectName("HgShelveBrowserDialog")
        HgShelveBrowserDialog.resize(650, 574)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(HgShelveBrowserDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.shelveList = QtWidgets.QTreeWidget(HgShelveBrowserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.shelveList.sizePolicy().hasHeightForWidth())
        self.shelveList.setSizePolicy(sizePolicy)
        self.shelveList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.shelveList.setAlternatingRowColors(True)
        self.shelveList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.shelveList.setRootIsDecorated(False)
        self.shelveList.setItemsExpandable(False)
        self.shelveList.setObjectName("shelveList")
        self.verticalLayout_2.addWidget(self.shelveList)
        self.groupBox = QtWidgets.QGroupBox(HgShelveBrowserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statisticsList = QtWidgets.QTreeWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.statisticsList.sizePolicy().hasHeightForWidth())
        self.statisticsList.setSizePolicy(sizePolicy)
        self.statisticsList.setAlternatingRowColors(True)
        self.statisticsList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.statisticsList.setRootIsDecorated(False)
        self.statisticsList.setItemsExpandable(False)
        self.statisticsList.setObjectName("statisticsList")
        self.verticalLayout.addWidget(self.statisticsList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filesLabel = QtWidgets.QLabel(self.groupBox)
        self.filesLabel.setText("")
        self.filesLabel.setObjectName("filesLabel")
        self.horizontalLayout.addWidget(self.filesLabel)
        self.insertionsLabel = QtWidgets.QLabel(self.groupBox)
        self.insertionsLabel.setText("")
        self.insertionsLabel.setObjectName("insertionsLabel")
        self.horizontalLayout.addWidget(self.insertionsLabel)
        self.deletionsLabel = QtWidgets.QLabel(self.groupBox)
        self.deletionsLabel.setText("")
        self.deletionsLabel.setObjectName("deletionsLabel")
        self.horizontalLayout.addWidget(self.deletionsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.errorGroup = QtWidgets.QGroupBox(HgShelveBrowserDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.errorGroup.sizePolicy().hasHeightForWidth())
        self.errorGroup.setSizePolicy(sizePolicy)
        self.errorGroup.setObjectName("errorGroup")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.errorGroup)
        self.vboxlayout.setObjectName("vboxlayout")
        self.errors = QtWidgets.QTextEdit(self.errorGroup)
        self.errors.setReadOnly(True)
        self.errors.setAcceptRichText(False)
        self.errors.setObjectName("errors")
        self.vboxlayout.addWidget(self.errors)
        self.verticalLayout_2.addWidget(self.errorGroup)
        self.inputGroup = QtWidgets.QGroupBox(HgShelveBrowserDialog)
        self.inputGroup.setObjectName("inputGroup")
        self._2 = QtWidgets.QGridLayout(self.inputGroup)
        self._2.setObjectName("_2")
        spacerItem = QtWidgets.QSpacerItem(327, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem, 1, 1, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.inputGroup)
        self.sendButton.setObjectName("sendButton")
        self._2.addWidget(self.sendButton, 1, 2, 1, 1)
        self.input = QtWidgets.QLineEdit(self.inputGroup)
        self.input.setObjectName("input")
        self._2.addWidget(self.input, 0, 0, 1, 3)
        self.passwordCheckBox = QtWidgets.QCheckBox(self.inputGroup)
        self.passwordCheckBox.setObjectName("passwordCheckBox")
        self._2.addWidget(self.passwordCheckBox, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.inputGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(HgShelveBrowserDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(HgShelveBrowserDialog)
        QtCore.QMetaObject.connectSlotsByName(HgShelveBrowserDialog)
        HgShelveBrowserDialog.setTabOrder(self.shelveList, self.statisticsList)
        HgShelveBrowserDialog.setTabOrder(self.statisticsList, self.errors)
        HgShelveBrowserDialog.setTabOrder(self.errors, self.input)
        HgShelveBrowserDialog.setTabOrder(self.input, self.passwordCheckBox)
        HgShelveBrowserDialog.setTabOrder(self.passwordCheckBox, self.sendButton)
        HgShelveBrowserDialog.setTabOrder(self.sendButton, self.buttonBox)

    def retranslateUi(self, HgShelveBrowserDialog):
        _translate = QtCore.QCoreApplication.translate
        HgShelveBrowserDialog.setWindowTitle(_translate("HgShelveBrowserDialog", "Mercurial Shelve Browser"))
        self.shelveList.setSortingEnabled(True)
        self.shelveList.headerItem().setText(0, _translate("HgShelveBrowserDialog", "Name"))
        self.shelveList.headerItem().setText(1, _translate("HgShelveBrowserDialog", "Age"))
        self.shelveList.headerItem().setText(2, _translate("HgShelveBrowserDialog", "Message"))
        self.groupBox.setTitle(_translate("HgShelveBrowserDialog", "Statistics"))
        self.statisticsList.headerItem().setText(0, _translate("HgShelveBrowserDialog", "File"))
        self.statisticsList.headerItem().setText(1, _translate("HgShelveBrowserDialog", "Changes"))
        self.statisticsList.headerItem().setText(2, _translate("HgShelveBrowserDialog", "Lines added"))
        self.statisticsList.headerItem().setText(3, _translate("HgShelveBrowserDialog", "Lines deleted"))
        self.errorGroup.setTitle(_translate("HgShelveBrowserDialog", "Errors"))
        self.errors.setWhatsThis(_translate("HgShelveBrowserDialog", "<b>Mercurial shelve errors</b><p>This shows possible error messages of the hg shelve command.</p>"))
        self.inputGroup.setTitle(_translate("HgShelveBrowserDialog", "Input"))
        self.sendButton.setToolTip(_translate("HgShelveBrowserDialog", "Press to send the input to the hg process"))
        self.sendButton.setText(_translate("HgShelveBrowserDialog", "&Send"))
        self.sendButton.setShortcut(_translate("HgShelveBrowserDialog", "Alt+S"))
        self.input.setToolTip(_translate("HgShelveBrowserDialog", "Enter data to be sent to the hg process"))
        self.passwordCheckBox.setToolTip(_translate("HgShelveBrowserDialog", "Select to switch the input field to password mode"))
        self.passwordCheckBox.setText(_translate("HgShelveBrowserDialog", "&Password Mode"))
        self.passwordCheckBox.setShortcut(_translate("HgShelveBrowserDialog", "Alt+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HgShelveBrowserDialog = QtWidgets.QWidget()
    ui = Ui_HgShelveBrowserDialog()
    ui.setupUi(HgShelveBrowserDialog)
    HgShelveBrowserDialog.show()
    sys.exit(app.exec_())

