# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\ApplicationPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ApplicationPage(object):
    def setupUi(self, ApplicationPage):
        ApplicationPage.setObjectName("ApplicationPage")
        ApplicationPage.resize(591, 989)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ApplicationPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerLabel = QtWidgets.QLabel(ApplicationPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_4.addWidget(self.headerLabel)
        self.line9_3 = QtWidgets.QFrame(ApplicationPage)
        self.line9_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_3.setObjectName("line9_3")
        self.verticalLayout_4.addWidget(self.line9_3)
        self.singleApplicationCheckBox = QtWidgets.QCheckBox(ApplicationPage)
        self.singleApplicationCheckBox.setObjectName("singleApplicationCheckBox")
        self.verticalLayout_4.addWidget(self.singleApplicationCheckBox)
        self.splashScreenCheckBox = QtWidgets.QCheckBox(ApplicationPage)
        self.splashScreenCheckBox.setObjectName("splashScreenCheckBox")
        self.verticalLayout_4.addWidget(self.splashScreenCheckBox)
        self.crashSessionEnabledCheckBox = QtWidgets.QCheckBox(ApplicationPage)
        self.crashSessionEnabledCheckBox.setObjectName("crashSessionEnabledCheckBox")
        self.verticalLayout_4.addWidget(self.crashSessionEnabledCheckBox)
        self.groupBox_3 = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridlayout.setObjectName("gridlayout")
        self.noOpenRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.noOpenRadioButton.setObjectName("noOpenRadioButton")
        self.gridlayout.addWidget(self.noOpenRadioButton, 0, 0, 1, 1)
        self.lastFileRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.lastFileRadioButton.setObjectName("lastFileRadioButton")
        self.gridlayout.addWidget(self.lastFileRadioButton, 0, 1, 1, 1)
        self.lastProjectRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.lastProjectRadioButton.setObjectName("lastProjectRadioButton")
        self.gridlayout.addWidget(self.lastProjectRadioButton, 1, 0, 1, 1)
        self.lastMultiprojectRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.lastMultiprojectRadioButton.setObjectName("lastMultiprojectRadioButton")
        self.gridlayout.addWidget(self.lastMultiprojectRadioButton, 1, 1, 1, 1)
        self.globalSessionRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.globalSessionRadioButton.setObjectName("globalSessionRadioButton")
        self.gridlayout.addWidget(self.globalSessionRadioButton, 2, 0, 1, 1)
        self.openCrashSessionCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.openCrashSessionCheckBox.setEnabled(False)
        self.openCrashSessionCheckBox.setObjectName("openCrashSessionCheckBox")
        self.gridlayout.addWidget(self.openCrashSessionCheckBox, 3, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.hboxlayout.setObjectName("hboxlayout")
        self.noCheckRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.noCheckRadioButton.setObjectName("noCheckRadioButton")
        self.hboxlayout.addWidget(self.noCheckRadioButton)
        self.alwaysCheckRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.alwaysCheckRadioButton.setObjectName("alwaysCheckRadioButton")
        self.hboxlayout.addWidget(self.alwaysCheckRadioButton)
        self.dailyCheckRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.dailyCheckRadioButton.setObjectName("dailyCheckRadioButton")
        self.hboxlayout.addWidget(self.dailyCheckRadioButton)
        self.weeklyCheckRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.weeklyCheckRadioButton.setObjectName("weeklyCheckRadioButton")
        self.hboxlayout.addWidget(self.weeklyCheckRadioButton)
        self.monthlyCheckRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.monthlyCheckRadioButton.setObjectName("monthlyCheckRadioButton")
        self.hboxlayout.addWidget(self.monthlyCheckRadioButton)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.systemEmailClientCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.systemEmailClientCheckBox.setObjectName("systemEmailClientCheckBox")
        self.verticalLayout_2.addWidget(self.systemEmailClientCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.errorlogCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.errorlogCheckBox.setObjectName("errorlogCheckBox")
        self.verticalLayout.addWidget(self.errorlogCheckBox)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.intervalSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.intervalSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.intervalSpinBox.setMaximum(2000)
        self.intervalSpinBox.setSingleStep(100)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.gridLayout.addWidget(self.intervalSpinBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(453, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(ApplicationPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.backgroundServicesLabel = QtWidgets.QLabel(self.groupBox_6)
        self.backgroundServicesLabel.setText("")
        self.backgroundServicesLabel.setWordWrap(True)
        self.backgroundServicesLabel.setObjectName("backgroundServicesLabel")
        self.verticalLayout_3.addWidget(self.backgroundServicesLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.backgroundServicesSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.backgroundServicesSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.backgroundServicesSpinBox.setObjectName("backgroundServicesSpinBox")
        self.horizontalLayout.addWidget(self.backgroundServicesSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        spacerItem2 = QtWidgets.QSpacerItem(571, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)

        self.retranslateUi(ApplicationPage)
        self.crashSessionEnabledCheckBox.toggled['bool'].connect(self.openCrashSessionCheckBox.setEnabled)
        self.crashSessionEnabledCheckBox.toggled['bool'].connect(self.openCrashSessionCheckBox.setChecked)
        QtCore.QMetaObject.connectSlotsByName(ApplicationPage)
        ApplicationPage.setTabOrder(self.singleApplicationCheckBox, self.splashScreenCheckBox)
        ApplicationPage.setTabOrder(self.splashScreenCheckBox, self.crashSessionEnabledCheckBox)
        ApplicationPage.setTabOrder(self.crashSessionEnabledCheckBox, self.noOpenRadioButton)
        ApplicationPage.setTabOrder(self.noOpenRadioButton, self.lastFileRadioButton)
        ApplicationPage.setTabOrder(self.lastFileRadioButton, self.lastProjectRadioButton)
        ApplicationPage.setTabOrder(self.lastProjectRadioButton, self.lastMultiprojectRadioButton)
        ApplicationPage.setTabOrder(self.lastMultiprojectRadioButton, self.globalSessionRadioButton)
        ApplicationPage.setTabOrder(self.globalSessionRadioButton, self.openCrashSessionCheckBox)
        ApplicationPage.setTabOrder(self.openCrashSessionCheckBox, self.noCheckRadioButton)
        ApplicationPage.setTabOrder(self.noCheckRadioButton, self.alwaysCheckRadioButton)
        ApplicationPage.setTabOrder(self.alwaysCheckRadioButton, self.dailyCheckRadioButton)
        ApplicationPage.setTabOrder(self.dailyCheckRadioButton, self.weeklyCheckRadioButton)
        ApplicationPage.setTabOrder(self.weeklyCheckRadioButton, self.monthlyCheckRadioButton)
        ApplicationPage.setTabOrder(self.monthlyCheckRadioButton, self.systemEmailClientCheckBox)
        ApplicationPage.setTabOrder(self.systemEmailClientCheckBox, self.errorlogCheckBox)
        ApplicationPage.setTabOrder(self.errorlogCheckBox, self.intervalSpinBox)

    def retranslateUi(self, ApplicationPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("ApplicationPage", "<b>Configure the application</b>"))
        self.singleApplicationCheckBox.setToolTip(_translate("ApplicationPage", "Select, if only one instance of the application should be running"))
        self.singleApplicationCheckBox.setText(_translate("ApplicationPage", "Single Application Mode"))
        self.splashScreenCheckBox.setToolTip(_translate("ApplicationPage", "Select to show the startup splash screen"))
        self.splashScreenCheckBox.setText(_translate("ApplicationPage", "Show Splash Screen at startup"))
        self.crashSessionEnabledCheckBox.setToolTip(_translate("ApplicationPage", "Select to enable the generation of a crash session file"))
        self.crashSessionEnabledCheckBox.setText(_translate("ApplicationPage", "Enable Crash Session"))
        self.groupBox_3.setTitle(_translate("ApplicationPage", "Open at startup"))
        self.noOpenRadioButton.setToolTip(_translate("ApplicationPage", "Select to not open anything"))
        self.noOpenRadioButton.setText(_translate("ApplicationPage", "None"))
        self.lastFileRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened file"))
        self.lastFileRadioButton.setText(_translate("ApplicationPage", "Last File"))
        self.lastProjectRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened project"))
        self.lastProjectRadioButton.setText(_translate("ApplicationPage", "Last Project"))
        self.lastMultiprojectRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened multiproject"))
        self.lastMultiprojectRadioButton.setText(_translate("ApplicationPage", "Last Multiproject"))
        self.globalSessionRadioButton.setToolTip(_translate("ApplicationPage", "Select to restore the global session"))
        self.globalSessionRadioButton.setText(_translate("ApplicationPage", "Global Session"))
        self.openCrashSessionCheckBox.setToolTip(_translate("ApplicationPage", "Select to look for a crash session file first"))
        self.openCrashSessionCheckBox.setText(_translate("ApplicationPage", "Load Crash Session"))
        self.groupBox_2.setTitle(_translate("ApplicationPage", "Check for updates"))
        self.noCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to disable update checking"))
        self.noCheckRadioButton.setText(_translate("ApplicationPage", "None"))
        self.alwaysCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates at every startup"))
        self.alwaysCheckRadioButton.setText(_translate("ApplicationPage", "Always"))
        self.dailyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a day"))
        self.dailyCheckRadioButton.setText(_translate("ApplicationPage", "Daily"))
        self.weeklyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a week"))
        self.weeklyCheckRadioButton.setText(_translate("ApplicationPage", "Weekly"))
        self.monthlyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a month"))
        self.monthlyCheckRadioButton.setText(_translate("ApplicationPage", "Monthly"))
        self.groupBox_4.setTitle(_translate("ApplicationPage", "Reporting"))
        self.systemEmailClientCheckBox.setToolTip(_translate("ApplicationPage", "Select to use the system email client to send reports"))
        self.systemEmailClientCheckBox.setText(_translate("ApplicationPage", "Use System Email Client"))
        self.groupBox.setTitle(_translate("ApplicationPage", "Error Log"))
        self.errorlogCheckBox.setToolTip(_translate("ApplicationPage", "Select to check the existence of an error log upon startup"))
        self.errorlogCheckBox.setText(_translate("ApplicationPage", "Check for Error Log at Startup"))
        self.groupBox_5.setTitle(_translate("ApplicationPage", "Keyboard Input Interval"))
        self.intervalSpinBox.setToolTip(_translate("ApplicationPage", "Enter the keyboard input interval, \'0\' for default"))
        self.intervalSpinBox.setSpecialValueText(_translate("ApplicationPage", "System Default"))
        self.intervalSpinBox.setSuffix(_translate("ApplicationPage", " ms"))
        self.groupBox_6.setTitle(_translate("ApplicationPage", "Background Services"))
        self.label.setText(_translate("ApplicationPage", "max. Processes:"))
        self.backgroundServicesSpinBox.setSpecialValueText(_translate("ApplicationPage", "Automatic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationPage = QtWidgets.QWidget()
    ui = Ui_ApplicationPage()
    ui.setupUi(ApplicationPage)
    ApplicationPage.show()
    sys.exit(app.exec_())

