# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\EditorHighlightingStylesPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorHighlightingStylesPage(object):
    def setupUi(self, EditorHighlightingStylesPage):
        EditorHighlightingStylesPage.setObjectName("EditorHighlightingStylesPage")
        EditorHighlightingStylesPage.resize(550, 592)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorHighlightingStylesPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(EditorHighlightingStylesPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line1 = QtWidgets.QFrame(EditorHighlightingStylesPage)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.verticalLayout.addWidget(self.line1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.TextLabel1_3 = QtWidgets.QLabel(EditorHighlightingStylesPage)
        self.TextLabel1_3.setToolTip("")
        self.TextLabel1_3.setObjectName("TextLabel1_3")
        self.hboxlayout.addWidget(self.TextLabel1_3)
        self.lexerLanguageComboBox = QtWidgets.QComboBox(EditorHighlightingStylesPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lexerLanguageComboBox.sizePolicy().hasHeightForWidth())
        self.lexerLanguageComboBox.setSizePolicy(sizePolicy)
        self.lexerLanguageComboBox.setObjectName("lexerLanguageComboBox")
        self.hboxlayout.addWidget(self.lexerLanguageComboBox)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.styleGroup = QtWidgets.QGroupBox(EditorHighlightingStylesPage)
        self.styleGroup.setObjectName("styleGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.styleGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.styleElementList = QtWidgets.QListWidget(self.styleGroup)
        self.styleElementList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.styleElementList.setObjectName("styleElementList")
        self.gridLayout.addWidget(self.styleElementList, 0, 0, 14, 1)
        self.foregroundButton = QtWidgets.QPushButton(self.styleGroup)
        self.foregroundButton.setObjectName("foregroundButton")
        self.gridLayout.addWidget(self.foregroundButton, 0, 1, 1, 1)
        self.backgroundButton = QtWidgets.QPushButton(self.styleGroup)
        self.backgroundButton.setObjectName("backgroundButton")
        self.gridLayout.addWidget(self.backgroundButton, 1, 1, 1, 1)
        self.fontButton = QtWidgets.QPushButton(self.styleGroup)
        self.fontButton.setObjectName("fontButton")
        self.gridLayout.addWidget(self.fontButton, 2, 1, 1, 1)
        self.eolfillCheckBox = QtWidgets.QCheckBox(self.styleGroup)
        self.eolfillCheckBox.setObjectName("eolfillCheckBox")
        self.gridLayout.addWidget(self.eolfillCheckBox, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.styleGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.defaultButton = QtWidgets.QPushButton(self.styleGroup)
        self.defaultButton.setObjectName("defaultButton")
        self.gridLayout.addWidget(self.defaultButton, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.monospacedButton = QtWidgets.QPushButton(self.styleGroup)
        self.monospacedButton.setCheckable(True)
        self.monospacedButton.setChecked(True)
        self.monospacedButton.setObjectName("monospacedButton")
        self.gridLayout.addWidget(self.monospacedButton, 7, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        self.allBackgroundColoursButton = QtWidgets.QPushButton(self.styleGroup)
        self.allBackgroundColoursButton.setObjectName("allBackgroundColoursButton")
        self.gridLayout.addWidget(self.allBackgroundColoursButton, 9, 1, 1, 1)
        self.allFontsButton = QtWidgets.QPushButton(self.styleGroup)
        self.allFontsButton.setObjectName("allFontsButton")
        self.gridLayout.addWidget(self.allFontsButton, 10, 1, 1, 1)
        self.allEolFillButton = QtWidgets.QPushButton(self.styleGroup)
        self.allEolFillButton.setObjectName("allEolFillButton")
        self.gridLayout.addWidget(self.allEolFillButton, 11, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.styleGroup)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 12, 1, 1, 1)
        self.allDefaultButton = QtWidgets.QPushButton(self.styleGroup)
        self.allDefaultButton.setObjectName("allDefaultButton")
        self.gridLayout.addWidget(self.allDefaultButton, 13, 1, 1, 1)
        self.sampleText = QtWidgets.QLineEdit(self.styleGroup)
        self.sampleText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sampleText.setAlignment(QtCore.Qt.AlignHCenter)
        self.sampleText.setReadOnly(True)
        self.sampleText.setObjectName("sampleText")
        self.gridLayout.addWidget(self.sampleText, 14, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.styleGroup)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 15, 0, 1, 2)
        self.verticalLayout.addWidget(self.styleGroup)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importCurrentButton = QtWidgets.QPushButton(EditorHighlightingStylesPage)
        self.importCurrentButton.setEnabled(False)
        self.importCurrentButton.setObjectName("importCurrentButton")
        self.horizontalLayout.addWidget(self.importCurrentButton)
        self.exportCurrentButton = QtWidgets.QPushButton(EditorHighlightingStylesPage)
        self.exportCurrentButton.setEnabled(False)
        self.exportCurrentButton.setObjectName("exportCurrentButton")
        self.horizontalLayout.addWidget(self.exportCurrentButton)
        self.importAllButton = QtWidgets.QPushButton(EditorHighlightingStylesPage)
        self.importAllButton.setObjectName("importAllButton")
        self.horizontalLayout.addWidget(self.importAllButton)
        self.exportAllButton = QtWidgets.QPushButton(EditorHighlightingStylesPage)
        self.exportAllButton.setObjectName("exportAllButton")
        self.horizontalLayout.addWidget(self.exportAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EditorHighlightingStylesPage)
        QtCore.QMetaObject.connectSlotsByName(EditorHighlightingStylesPage)
        EditorHighlightingStylesPage.setTabOrder(self.lexerLanguageComboBox, self.styleElementList)
        EditorHighlightingStylesPage.setTabOrder(self.styleElementList, self.foregroundButton)
        EditorHighlightingStylesPage.setTabOrder(self.foregroundButton, self.backgroundButton)
        EditorHighlightingStylesPage.setTabOrder(self.backgroundButton, self.fontButton)
        EditorHighlightingStylesPage.setTabOrder(self.fontButton, self.eolfillCheckBox)
        EditorHighlightingStylesPage.setTabOrder(self.eolfillCheckBox, self.defaultButton)
        EditorHighlightingStylesPage.setTabOrder(self.defaultButton, self.monospacedButton)
        EditorHighlightingStylesPage.setTabOrder(self.monospacedButton, self.allBackgroundColoursButton)
        EditorHighlightingStylesPage.setTabOrder(self.allBackgroundColoursButton, self.allFontsButton)
        EditorHighlightingStylesPage.setTabOrder(self.allFontsButton, self.allEolFillButton)
        EditorHighlightingStylesPage.setTabOrder(self.allEolFillButton, self.allDefaultButton)
        EditorHighlightingStylesPage.setTabOrder(self.allDefaultButton, self.importCurrentButton)
        EditorHighlightingStylesPage.setTabOrder(self.importCurrentButton, self.exportCurrentButton)
        EditorHighlightingStylesPage.setTabOrder(self.exportCurrentButton, self.importAllButton)
        EditorHighlightingStylesPage.setTabOrder(self.importAllButton, self.exportAllButton)

    def retranslateUi(self, EditorHighlightingStylesPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("EditorHighlightingStylesPage", "<b>Configure syntax highlighting</b>"))
        self.TextLabel1_3.setText(_translate("EditorHighlightingStylesPage", "Lexer Language:"))
        self.lexerLanguageComboBox.setToolTip(_translate("EditorHighlightingStylesPage", "Select the lexer language to be configured."))
        self.styleGroup.setTitle(_translate("EditorHighlightingStylesPage", "Style Element"))
        self.foregroundButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the foreground colour."))
        self.foregroundButton.setText(_translate("EditorHighlightingStylesPage", "Foreground Colour"))
        self.backgroundButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the background colour."))
        self.backgroundButton.setText(_translate("EditorHighlightingStylesPage", "Background Colour"))
        self.fontButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the font."))
        self.fontButton.setText(_translate("EditorHighlightingStylesPage", "Font"))
        self.eolfillCheckBox.setToolTip(_translate("EditorHighlightingStylesPage", "Select end of line fill."))
        self.eolfillCheckBox.setText(_translate("EditorHighlightingStylesPage", "Fill to end of line"))
        self.defaultButton.setToolTip(_translate("EditorHighlightingStylesPage", "Press to set the current style to its default values"))
        self.defaultButton.setText(_translate("EditorHighlightingStylesPage", "to Default"))
        self.monospacedButton.setToolTip(_translate("EditorHighlightingStylesPage", "Press to show only monospaced fonts"))
        self.monospacedButton.setText(_translate("EditorHighlightingStylesPage", "Monospaced Fonts Only"))
        self.allBackgroundColoursButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the background colour for all styles"))
        self.allBackgroundColoursButton.setText(_translate("EditorHighlightingStylesPage", "All Background Colours"))
        self.allFontsButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the font for all styles."))
        self.allFontsButton.setText(_translate("EditorHighlightingStylesPage", "All Fonts"))
        self.allEolFillButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the eol fill for all styles"))
        self.allEolFillButton.setText(_translate("EditorHighlightingStylesPage", "All Fill to end of line"))
        self.allDefaultButton.setToolTip(_translate("EditorHighlightingStylesPage", "Press to set all styles to their default values"))
        self.allDefaultButton.setText(_translate("EditorHighlightingStylesPage", "All to Default"))
        self.sampleText.setText(_translate("EditorHighlightingStylesPage", "Sample Text"))
        self.label.setText(_translate("EditorHighlightingStylesPage", "<b>Note:</b> The tick in the list above indicates the entrie\'s \'fill to end of line\' setting."))
        self.importCurrentButton.setToolTip(_translate("EditorHighlightingStylesPage", "Imports all styles of the currently selected language"))
        self.importCurrentButton.setText(_translate("EditorHighlightingStylesPage", "Import styles"))
        self.exportCurrentButton.setToolTip(_translate("EditorHighlightingStylesPage", "Exports all styles of the currently selected language"))
        self.exportCurrentButton.setText(_translate("EditorHighlightingStylesPage", "Export styles"))
        self.importAllButton.setToolTip(_translate("EditorHighlightingStylesPage", "Imports all styles of all languages"))
        self.importAllButton.setText(_translate("EditorHighlightingStylesPage", "Import all styles"))
        self.exportAllButton.setToolTip(_translate("EditorHighlightingStylesPage", "Exports all styles of all languages"))
        self.exportAllButton.setText(_translate("EditorHighlightingStylesPage", "Export all styles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditorHighlightingStylesPage = QtWidgets.QWidget()
    ui = Ui_EditorHighlightingStylesPage()
    ui.setupUi(EditorHighlightingStylesPage)
    EditorHighlightingStylesPage.show()
    sys.exit(app.exec_())

