# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\EditorCalltipsPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorCalltipsPage(object):
    def setupUi(self, EditorCalltipsPage):
        EditorCalltipsPage.setObjectName("EditorCalltipsPage")
        EditorCalltipsPage.resize(408, 373)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(EditorCalltipsPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerLabel = QtWidgets.QLabel(EditorCalltipsPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line18 = QtWidgets.QFrame(EditorCalltipsPage)
        self.line18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line18.setObjectName("line18")
        self.verticalLayout_3.addWidget(self.line18)
        self.ctEnabledCheckBox = QtWidgets.QCheckBox(EditorCalltipsPage)
        self.ctEnabledCheckBox.setObjectName("ctEnabledCheckBox")
        self.verticalLayout_3.addWidget(self.ctEnabledCheckBox)
        self.frame = QtWidgets.QFrame(EditorCalltipsPage)
        self.frame.setEnabled(False)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3.addWidget(self.frame)
        self.groupBox_4 = QtWidgets.QGroupBox(EditorCalltipsPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ctVisibleSlider = QtWidgets.QSlider(self.groupBox_4)
        self.ctVisibleSlider.setMaximum(20)
        self.ctVisibleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ctVisibleSlider.setTickInterval(1)
        self.ctVisibleSlider.setObjectName("ctVisibleSlider")
        self.horizontalLayout_2.addWidget(self.ctVisibleSlider)
        self.lCDNumber5 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lCDNumber5.setDigitCount(2)
        self.lCDNumber5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lCDNumber5.setObjectName("lCDNumber5")
        self.horizontalLayout_2.addWidget(self.lCDNumber5)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.calltipsPositionBox = QtWidgets.QGroupBox(EditorCalltipsPage)
        self.calltipsPositionBox.setObjectName("calltipsPositionBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.calltipsPositionBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.positionComboBox = QtWidgets.QComboBox(self.calltipsPositionBox)
        self.positionComboBox.setObjectName("positionComboBox")
        self.verticalLayout_2.addWidget(self.positionComboBox)
        self.verticalLayout_3.addWidget(self.calltipsPositionBox)
        self.groupBox_2 = QtWidgets.QGroupBox(EditorCalltipsPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.hboxlayout.setObjectName("hboxlayout")
        self.TextLabel2_2_2_2 = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabel2_2_2_2.setObjectName("TextLabel2_2_2_2")
        self.hboxlayout.addWidget(self.TextLabel2_2_2_2)
        self.calltipsBackgroundButton = QtWidgets.QPushButton(self.groupBox_2)
        self.calltipsBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.calltipsBackgroundButton.setText("")
        self.calltipsBackgroundButton.setObjectName("calltipsBackgroundButton")
        self.hboxlayout.addWidget(self.calltipsBackgroundButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(EditorCalltipsPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ctScintillaCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.ctScintillaCheckBox.setObjectName("ctScintillaCheckBox")
        self.verticalLayout.addWidget(self.ctScintillaCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(EditorCalltipsPage)
        self.ctVisibleSlider.valueChanged['int'].connect(self.lCDNumber5.display)
        QtCore.QMetaObject.connectSlotsByName(EditorCalltipsPage)
        EditorCalltipsPage.setTabOrder(self.ctEnabledCheckBox, self.calltipsBackgroundButton)
        EditorCalltipsPage.setTabOrder(self.calltipsBackgroundButton, self.ctScintillaCheckBox)

    def retranslateUi(self, EditorCalltipsPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("EditorCalltipsPage", "<b>Configure Calltips</b>"))
        self.ctEnabledCheckBox.setToolTip(_translate("EditorCalltipsPage", "Select this to enable calltips"))
        self.ctEnabledCheckBox.setText(_translate("EditorCalltipsPage", "Automatic Calltips Enabled"))
        self.groupBox_4.setTitle(_translate("EditorCalltipsPage", "Visible Calltips"))
        self.ctVisibleSlider.setToolTip(_translate("EditorCalltipsPage", "Move to set the maximum number of calltips shown (0 = all available)"))
        self.lCDNumber5.setToolTip(_translate("EditorCalltipsPage", "Displays the maximum number of calltips to be shown"))
        self.calltipsPositionBox.setTitle(_translate("EditorCalltipsPage", "Calltips Position"))
        self.positionComboBox.setToolTip(_translate("EditorCalltipsPage", "Select the position for the calltips"))
        self.groupBox_2.setTitle(_translate("EditorCalltipsPage", "Colours"))
        self.TextLabel2_2_2_2.setText(_translate("EditorCalltipsPage", "Background colour:"))
        self.calltipsBackgroundButton.setToolTip(_translate("EditorCalltipsPage", "Select the background colour for calltips."))
        self.groupBox.setTitle(_translate("EditorCalltipsPage", "Plug-In Behavior"))
        self.ctScintillaCheckBox.setToolTip(_translate("EditorCalltipsPage", "Select to show QScintilla provided calltips, if the selected plug-ins fail"))
        self.ctScintillaCheckBox.setWhatsThis(_translate("EditorCalltipsPage", "Qscintilla provided calltips are shown, if this option is enabled and calltips shall be provided by plug-ins (see calltips sub-page of the plug-in) and the plugin-ins don\'t deliver any calltips."))
        self.ctScintillaCheckBox.setText(_translate("EditorCalltipsPage", "Show QScintilla calltips, if plug-ins fail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditorCalltipsPage = QtWidgets.QWidget()
    ui = Ui_EditorCalltipsPage()
    ui.setupUi(EditorCalltipsPage)
    EditorCalltipsPage.show()
    sys.exit(app.exec_())

