# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\EditorStylesPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorStylesPage(object):
    def setupUi(self, EditorStylesPage):
        EditorStylesPage.setObjectName("EditorStylesPage")
        EditorStylesPage.resize(655, 2530)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(EditorStylesPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.headerLabel = QtWidgets.QLabel(EditorStylesPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_8.addWidget(self.headerLabel)
        self.line3 = QtWidgets.QFrame(EditorStylesPage)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setObjectName("line3")
        self.verticalLayout_8.addWidget(self.line3)
        self.label_3 = QtWidgets.QLabel(EditorStylesPage)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.groupBox_12 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.editAreaOverrideCheckBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.editAreaOverrideCheckBox.setObjectName("editAreaOverrideCheckBox")
        self.gridLayout_6.addWidget(self.editAreaOverrideCheckBox, 0, 0, 1, 4)
        self.TextLabel2_2_2_2_2_12 = QtWidgets.QLabel(self.groupBox_12)
        self.TextLabel2_2_2_2_2_12.setEnabled(False)
        self.TextLabel2_2_2_2_2_12.setObjectName("TextLabel2_2_2_2_2_12")
        self.gridLayout_6.addWidget(self.TextLabel2_2_2_2_2_12, 1, 0, 1, 1)
        self.editAreaForegroundButton = QtWidgets.QPushButton(self.groupBox_12)
        self.editAreaForegroundButton.setEnabled(False)
        self.editAreaForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.editAreaForegroundButton.setText("")
        self.editAreaForegroundButton.setObjectName("editAreaForegroundButton")
        self.gridLayout_6.addWidget(self.editAreaForegroundButton, 1, 1, 1, 1)
        self.TextLabel2_2_2_2_2_11 = QtWidgets.QLabel(self.groupBox_12)
        self.TextLabel2_2_2_2_2_11.setEnabled(False)
        self.TextLabel2_2_2_2_2_11.setObjectName("TextLabel2_2_2_2_2_11")
        self.gridLayout_6.addWidget(self.TextLabel2_2_2_2_2_11, 1, 2, 1, 1)
        self.editAreaBackgroundButton = QtWidgets.QPushButton(self.groupBox_12)
        self.editAreaBackgroundButton.setEnabled(False)
        self.editAreaBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.editAreaBackgroundButton.setText("")
        self.editAreaBackgroundButton.setObjectName("editAreaBackgroundButton")
        self.gridLayout_6.addWidget(self.editAreaBackgroundButton, 1, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_12)
        self.groupBox_5 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridlayout.setObjectName("gridlayout")
        self.monospacedCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.monospacedCheckBox.setObjectName("monospacedCheckBox")
        self.gridlayout.addWidget(self.monospacedCheckBox, 1, 2, 1, 1)
        self.defaultFontSample = QtWidgets.QLineEdit(self.groupBox_5)
        self.defaultFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.defaultFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.defaultFontSample.setReadOnly(True)
        self.defaultFontSample.setObjectName("defaultFontSample")
        self.gridlayout.addWidget(self.defaultFontSample, 0, 1, 1, 1)
        self.defaultFontButton = QtWidgets.QPushButton(self.groupBox_5)
        self.defaultFontButton.setObjectName("defaultFontButton")
        self.gridlayout.addWidget(self.defaultFontButton, 0, 0, 1, 1)
        self.monospacedFontButton = QtWidgets.QPushButton(self.groupBox_5)
        self.monospacedFontButton.setObjectName("monospacedFontButton")
        self.gridlayout.addWidget(self.monospacedFontButton, 1, 0, 1, 1)
        self.monospacedFontSample = QtWidgets.QLineEdit(self.groupBox_5)
        self.monospacedFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.monospacedFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.monospacedFontSample.setReadOnly(True)
        self.monospacedFontSample.setObjectName("monospacedFontSample")
        self.gridlayout.addWidget(self.monospacedFontSample, 1, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.groupBox = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.linenoCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.linenoCheckBox.setObjectName("linenoCheckBox")
        self.gridLayout_2.addWidget(self.linenoCheckBox, 0, 0, 1, 1)
        self.foldingCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.foldingCheckBox.setObjectName("foldingCheckBox")
        self.gridLayout_2.addWidget(self.foldingCheckBox, 0, 1, 1, 1)
        self.unifiedMarginsCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.unifiedMarginsCheckBox.setObjectName("unifiedMarginsCheckBox")
        self.gridLayout_2.addWidget(self.unifiedMarginsCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.TextLabel1_4_2_2 = QtWidgets.QLabel(self.groupBox)
        self.TextLabel1_4_2_2.setObjectName("TextLabel1_4_2_2")
        self.hboxlayout.addWidget(self.TextLabel1_4_2_2)
        self.foldingStyleComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foldingStyleComboBox.sizePolicy().hasHeightForWidth())
        self.foldingStyleComboBox.setSizePolicy(sizePolicy)
        self.foldingStyleComboBox.setObjectName("foldingStyleComboBox")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.foldingStyleComboBox.addItem("")
        self.hboxlayout.addWidget(self.foldingStyleComboBox)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TextLabel2_2_2_2_2_6 = QtWidgets.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_6.setObjectName("TextLabel2_2_2_2_2_6")
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_6, 0, 0, 1, 1)
        self.marginsForegroundButton = QtWidgets.QPushButton(self.groupBox)
        self.marginsForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.marginsForegroundButton.setText("")
        self.marginsForegroundButton.setObjectName("marginsForegroundButton")
        self.gridLayout.addWidget(self.marginsForegroundButton, 0, 1, 1, 1)
        self.TextLabel2_2_2_2_2_7 = QtWidgets.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_7.setObjectName("TextLabel2_2_2_2_2_7")
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_7, 0, 2, 1, 1)
        self.marginsBackgroundButton = QtWidgets.QPushButton(self.groupBox)
        self.marginsBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.marginsBackgroundButton.setText("")
        self.marginsBackgroundButton.setObjectName("marginsBackgroundButton")
        self.gridLayout.addWidget(self.marginsBackgroundButton, 0, 3, 1, 1)
        self.TextLabel2_2_2_2_2_8 = QtWidgets.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_8.setObjectName("TextLabel2_2_2_2_2_8")
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_8, 1, 0, 1, 1)
        self.foldmarginBackgroundButton = QtWidgets.QPushButton(self.groupBox)
        self.foldmarginBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.foldmarginBackgroundButton.setText("")
        self.foldmarginBackgroundButton.setObjectName("foldmarginBackgroundButton")
        self.gridLayout.addWidget(self.foldmarginBackgroundButton, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.foldmarkersForegroundButton = QtWidgets.QPushButton(self.groupBox)
        self.foldmarkersForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.foldmarkersForegroundButton.setText("")
        self.foldmarkersForegroundButton.setObjectName("foldmarkersForegroundButton")
        self.gridLayout.addWidget(self.foldmarkersForegroundButton, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.foldmarkersBackgroundButton = QtWidgets.QPushButton(self.groupBox)
        self.foldmarkersBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.foldmarkersBackgroundButton.setText("")
        self.foldmarkersBackgroundButton.setObjectName("foldmarkersBackgroundButton")
        self.gridLayout.addWidget(self.foldmarkersBackgroundButton, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linenumbersFontButton = QtWidgets.QPushButton(self.groupBox)
        self.linenumbersFontButton.setObjectName("linenumbersFontButton")
        self.horizontalLayout.addWidget(self.linenumbersFontButton)
        self.marginsFontSample = QtWidgets.QLineEdit(self.groupBox)
        self.marginsFontSample.setMinimumSize(QtCore.QSize(200, 0))
        self.marginsFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.marginsFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.marginsFontSample.setReadOnly(True)
        self.marginsFontSample.setObjectName("marginsFontSample")
        self.horizontalLayout.addWidget(self.marginsFontSample)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self._2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self._2.setObjectName("_2")
        self._3 = QtWidgets.QGridLayout()
        self._3.setObjectName("_3")
        self.customSelColourCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.customSelColourCheckBox.setObjectName("customSelColourCheckBox")
        self._3.addWidget(self.customSelColourCheckBox, 0, 0, 1, 1)
        self.colourizeSelTextCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.colourizeSelTextCheckBox.setObjectName("colourizeSelTextCheckBox")
        self._3.addWidget(self.colourizeSelTextCheckBox, 0, 1, 1, 1)
        self.extentSelEolCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.extentSelEolCheckBox.setObjectName("extentSelEolCheckBox")
        self._3.addWidget(self.extentSelEolCheckBox, 1, 0, 1, 1)
        self._2.addLayout(self._3)
        self._4 = QtWidgets.QHBoxLayout()
        self._4.setObjectName("_4")
        self.TextLabel2_2_2_2_2_4 = QtWidgets.QLabel(self.groupBox_3)
        self.TextLabel2_2_2_2_2_4.setObjectName("TextLabel2_2_2_2_2_4")
        self._4.addWidget(self.TextLabel2_2_2_2_2_4)
        self.selectionForegroundButton = QtWidgets.QPushButton(self.groupBox_3)
        self.selectionForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.selectionForegroundButton.setText("")
        self.selectionForegroundButton.setObjectName("selectionForegroundButton")
        self._4.addWidget(self.selectionForegroundButton)
        self.TextLabel2_2_2_2_2_5 = QtWidgets.QLabel(self.groupBox_3)
        self.TextLabel2_2_2_2_2_5.setObjectName("TextLabel2_2_2_2_2_5")
        self._4.addWidget(self.TextLabel2_2_2_2_2_5)
        self.selectionBackgroundButton = QtWidgets.QPushButton(self.groupBox_3)
        self.selectionBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.selectionBackgroundButton.setText("")
        self.selectionBackgroundButton.setObjectName("selectionBackgroundButton")
        self._4.addWidget(self.selectionBackgroundButton)
        self._2.addLayout(self._4)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.caretlineVisibleCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.caretlineVisibleCheckBox.setObjectName("caretlineVisibleCheckBox")
        self.horizontalLayout_4.addWidget(self.caretlineVisibleCheckBox)
        self.caretlineAlwaysVisibleCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.caretlineAlwaysVisibleCheckBox.setObjectName("caretlineAlwaysVisibleCheckBox")
        self.horizontalLayout_4.addWidget(self.caretlineAlwaysVisibleCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self._6 = QtWidgets.QHBoxLayout()
        self._6.setObjectName("_6")
        self.textLabel1_7 = QtWidgets.QLabel(self.groupBox_4)
        self.textLabel1_7.setObjectName("textLabel1_7")
        self._6.addWidget(self.textLabel1_7)
        self.caretWidthSpinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.caretWidthSpinBox.setMinimum(1)
        self.caretWidthSpinBox.setMaximum(3)
        self.caretWidthSpinBox.setObjectName("caretWidthSpinBox")
        self._6.addWidget(self.caretWidthSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._6.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self._6)
        self._7 = QtWidgets.QHBoxLayout()
        self._7.setObjectName("_7")
        self.TextLabel2_2_2_2_2_2 = QtWidgets.QLabel(self.groupBox_4)
        self.TextLabel2_2_2_2_2_2.setObjectName("TextLabel2_2_2_2_2_2")
        self._7.addWidget(self.TextLabel2_2_2_2_2_2)
        self.caretForegroundButton = QtWidgets.QPushButton(self.groupBox_4)
        self.caretForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.caretForegroundButton.setText("")
        self.caretForegroundButton.setObjectName("caretForegroundButton")
        self._7.addWidget(self.caretForegroundButton)
        self.TextLabel2_2_2_2_2_3 = QtWidgets.QLabel(self.groupBox_4)
        self.TextLabel2_2_2_2_2_3.setObjectName("TextLabel2_2_2_2_2_3")
        self._7.addWidget(self.TextLabel2_2_2_2_2_3)
        self.caretlineBackgroundButton = QtWidgets.QPushButton(self.groupBox_4)
        self.caretlineBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.caretlineBackgroundButton.setText("")
        self.caretlineBackgroundButton.setObjectName("caretlineBackgroundButton")
        self._7.addWidget(self.caretlineBackgroundButton)
        self.verticalLayout_6.addLayout(self._7)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.debugMarkerBackgroundCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.debugMarkerBackgroundCheckBox.setObjectName("debugMarkerBackgroundCheckBox")
        self.gridLayout_10.addWidget(self.debugMarkerBackgroundCheckBox, 0, 0, 1, 4)
        self.TextLabel3_2_2 = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabel3_2_2.setObjectName("TextLabel3_2_2")
        self.gridLayout_10.addWidget(self.TextLabel3_2_2, 1, 0, 1, 1)
        self.currentLineMarkerButton = QtWidgets.QPushButton(self.groupBox_2)
        self.currentLineMarkerButton.setMinimumSize(QtCore.QSize(100, 0))
        self.currentLineMarkerButton.setText("")
        self.currentLineMarkerButton.setObjectName("currentLineMarkerButton")
        self.gridLayout_10.addWidget(self.currentLineMarkerButton, 1, 1, 1, 1)
        self.TextLabel4_2_2 = QtWidgets.QLabel(self.groupBox_2)
        self.TextLabel4_2_2.setObjectName("TextLabel4_2_2")
        self.gridLayout_10.addWidget(self.TextLabel4_2_2, 1, 2, 1, 1)
        self.errorMarkerButton = QtWidgets.QPushButton(self.groupBox_2)
        self.errorMarkerButton.setMinimumSize(QtCore.QSize(100, 0))
        self.errorMarkerButton.setText("")
        self.errorMarkerButton.setObjectName("errorMarkerButton")
        self.gridLayout_10.addWidget(self.errorMarkerButton, 1, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_6 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self._9 = QtWidgets.QGridLayout(self.groupBox_6)
        self._9.setObjectName("_9")
        self.bracehighlightingCheckBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.bracehighlightingCheckBox.setObjectName("bracehighlightingCheckBox")
        self._9.addWidget(self.bracehighlightingCheckBox, 0, 0, 1, 2)
        self.TextLabel1_3_2 = QtWidgets.QLabel(self.groupBox_6)
        self.TextLabel1_3_2.setObjectName("TextLabel1_3_2")
        self._9.addWidget(self.TextLabel1_3_2, 1, 0, 1, 1)
        self.matchingBracesButton = QtWidgets.QPushButton(self.groupBox_6)
        self.matchingBracesButton.setMinimumSize(QtCore.QSize(100, 0))
        self.matchingBracesButton.setText("")
        self.matchingBracesButton.setObjectName("matchingBracesButton")
        self._9.addWidget(self.matchingBracesButton, 1, 1, 1, 1)
        self.TextLabel1_3_2_2 = QtWidgets.QLabel(self.groupBox_6)
        self.TextLabel1_3_2_2.setObjectName("TextLabel1_3_2_2")
        self._9.addWidget(self.TextLabel1_3_2_2, 1, 2, 1, 1)
        self.matchingBracesBackButton = QtWidgets.QPushButton(self.groupBox_6)
        self.matchingBracesBackButton.setMinimumSize(QtCore.QSize(100, 0))
        self.matchingBracesBackButton.setText("")
        self.matchingBracesBackButton.setObjectName("matchingBracesBackButton")
        self._9.addWidget(self.matchingBracesBackButton, 1, 3, 1, 1)
        self.TextLabel2_2_2 = QtWidgets.QLabel(self.groupBox_6)
        self.TextLabel2_2_2.setMinimumSize(QtCore.QSize(100, 0))
        self.TextLabel2_2_2.setObjectName("TextLabel2_2_2")
        self._9.addWidget(self.TextLabel2_2_2, 2, 0, 1, 1)
        self.nonmatchingBracesButton = QtWidgets.QPushButton(self.groupBox_6)
        self.nonmatchingBracesButton.setText("")
        self.nonmatchingBracesButton.setObjectName("nonmatchingBracesButton")
        self._9.addWidget(self.nonmatchingBracesButton, 2, 1, 1, 1)
        self.TextLabel2_2_2_3 = QtWidgets.QLabel(self.groupBox_6)
        self.TextLabel2_2_2_3.setMinimumSize(QtCore.QSize(100, 0))
        self.TextLabel2_2_2_3.setObjectName("TextLabel2_2_2_3")
        self._9.addWidget(self.TextLabel2_2_2_3, 2, 2, 1, 1)
        self.nonmatchingBracesBackButton = QtWidgets.QPushButton(self.groupBox_6)
        self.nonmatchingBracesBackButton.setText("")
        self.nonmatchingBracesBackButton.setObjectName("nonmatchingBracesBackButton")
        self._9.addWidget(self.nonmatchingBracesBackButton, 2, 3, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eolCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.eolCheckBox.setObjectName("eolCheckBox")
        self.verticalLayout_4.addWidget(self.eolCheckBox)
        self.wrapLongLinesGroup = QtWidgets.QGroupBox(self.groupBox_7)
        self.wrapLongLinesGroup.setToolTip("")
        self.wrapLongLinesGroup.setCheckable(False)
        self.wrapLongLinesGroup.setObjectName("wrapLongLinesGroup")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.wrapLongLinesGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textLabel1_15 = QtWidgets.QLabel(self.wrapLongLinesGroup)
        self.textLabel1_15.setObjectName("textLabel1_15")
        self.gridLayout_7.addWidget(self.textLabel1_15, 0, 0, 1, 1)
        self.wrapModeComboBox = QtWidgets.QComboBox(self.wrapLongLinesGroup)
        self.wrapModeComboBox.setObjectName("wrapModeComboBox")
        self.gridLayout_7.addWidget(self.wrapModeComboBox, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.wrapLongLinesGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.wrapVisualComboBox = QtWidgets.QComboBox(self.wrapLongLinesGroup)
        self.wrapVisualComboBox.setObjectName("wrapVisualComboBox")
        self.gridLayout_7.addWidget(self.wrapVisualComboBox, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.wrapLongLinesGroup)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName("groupBox_9")
        self._13 = QtWidgets.QGridLayout(self.groupBox_9)
        self._13.setObjectName("_13")
        spacerItem4 = QtWidgets.QSpacerItem(211, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._13.addItem(spacerItem4, 0, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(201, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._13.addItem(spacerItem5, 2, 2, 1, 2)
        self.edgeBackgroundColorButton = QtWidgets.QPushButton(self.groupBox_9)
        self.edgeBackgroundColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.edgeBackgroundColorButton.setText("")
        self.edgeBackgroundColorButton.setObjectName("edgeBackgroundColorButton")
        self._13.addWidget(self.edgeBackgroundColorButton, 2, 1, 1, 1)
        self.TextLabel13_3_2_2 = QtWidgets.QLabel(self.groupBox_9)
        self.TextLabel13_3_2_2.setObjectName("TextLabel13_3_2_2")
        self._13.addWidget(self.TextLabel13_3_2_2, 2, 0, 1, 1)
        self.edgeLineColumnSlider = QtWidgets.QSlider(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeLineColumnSlider.sizePolicy().hasHeightForWidth())
        self.edgeLineColumnSlider.setSizePolicy(sizePolicy)
        self.edgeLineColumnSlider.setMinimum(0)
        self.edgeLineColumnSlider.setMaximum(160)
        self.edgeLineColumnSlider.setProperty("value", 80)
        self.edgeLineColumnSlider.setOrientation(QtCore.Qt.Horizontal)
        self.edgeLineColumnSlider.setTickInterval(10)
        self.edgeLineColumnSlider.setObjectName("edgeLineColumnSlider")
        self._13.addWidget(self.edgeLineColumnSlider, 1, 1, 1, 2)
        self.edgeLineColumnLCD = QtWidgets.QLCDNumber(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeLineColumnLCD.sizePolicy().hasHeightForWidth())
        self.edgeLineColumnLCD.setSizePolicy(sizePolicy)
        self.edgeLineColumnLCD.setDigitCount(3)
        self.edgeLineColumnLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.edgeLineColumnLCD.setProperty("value", 80.0)
        self.edgeLineColumnLCD.setObjectName("edgeLineColumnLCD")
        self._13.addWidget(self.edgeLineColumnLCD, 1, 3, 1, 1)
        self.TextLabel13_3_2 = QtWidgets.QLabel(self.groupBox_9)
        self.TextLabel13_3_2.setObjectName("TextLabel13_3_2")
        self._13.addWidget(self.TextLabel13_3_2, 1, 0, 1, 1)
        self.textLabel1_14 = QtWidgets.QLabel(self.groupBox_9)
        self.textLabel1_14.setObjectName("textLabel1_14")
        self._13.addWidget(self.textLabel1_14, 0, 0, 1, 1)
        self.edgeModeCombo = QtWidgets.QComboBox(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeModeCombo.sizePolicy().hasHeightForWidth())
        self.edgeModeCombo.setSizePolicy(sizePolicy)
        self.edgeModeCombo.setObjectName("edgeModeCombo")
        self.edgeModeCombo.addItem("")
        self.edgeModeCombo.addItem("")
        self.edgeModeCombo.addItem("")
        self._13.addWidget(self.edgeModeCombo, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TextLabel13_2_2_3 = QtWidgets.QLabel(self.groupBox_8)
        self.TextLabel13_2_2_3.setObjectName("TextLabel13_2_2_3")
        self.horizontalLayout_2.addWidget(self.TextLabel13_2_2_3)
        self.zoomfactorSlider = QtWidgets.QSlider(self.groupBox_8)
        self.zoomfactorSlider.setMinimum(-10)
        self.zoomfactorSlider.setMaximum(20)
        self.zoomfactorSlider.setProperty("value", 0)
        self.zoomfactorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomfactorSlider.setTickInterval(5)
        self.zoomfactorSlider.setObjectName("zoomfactorSlider")
        self.horizontalLayout_2.addWidget(self.zoomfactorSlider)
        self.zoomfactorLCD = QtWidgets.QLCDNumber(self.groupBox_8)
        self.zoomfactorLCD.setDigitCount(3)
        self.zoomfactorLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.zoomfactorLCD.setProperty("value", 0.0)
        self.zoomfactorLCD.setObjectName("zoomfactorLCD")
        self.horizontalLayout_2.addWidget(self.zoomfactorLCD)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.annotationsGroup = QtWidgets.QGroupBox(EditorStylesPage)
        self.annotationsGroup.setObjectName("annotationsGroup")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.annotationsGroup)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.enableAnnotationsCheckBox = QtWidgets.QCheckBox(self.annotationsGroup)
        self.enableAnnotationsCheckBox.setObjectName("enableAnnotationsCheckBox")
        self.gridLayout_8.addWidget(self.enableAnnotationsCheckBox, 0, 0, 1, 2)
        self.annotationsWarningGroup = QtWidgets.QGroupBox(self.annotationsGroup)
        self.annotationsWarningGroup.setObjectName("annotationsWarningGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.annotationsWarningGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.annotationsWarningFgButton = QtWidgets.QPushButton(self.annotationsWarningGroup)
        self.annotationsWarningFgButton.setObjectName("annotationsWarningFgButton")
        self.gridLayout_3.addWidget(self.annotationsWarningFgButton, 0, 0, 1, 1)
        self.annotationsWarningBgButton = QtWidgets.QPushButton(self.annotationsWarningGroup)
        self.annotationsWarningBgButton.setObjectName("annotationsWarningBgButton")
        self.gridLayout_3.addWidget(self.annotationsWarningBgButton, 0, 1, 1, 1)
        self.annotationsWarningSample = QtWidgets.QLineEdit(self.annotationsWarningGroup)
        self.annotationsWarningSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.annotationsWarningSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.annotationsWarningSample.setReadOnly(True)
        self.annotationsWarningSample.setObjectName("annotationsWarningSample")
        self.gridLayout_3.addWidget(self.annotationsWarningSample, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.annotationsWarningGroup, 1, 0, 1, 1)
        self.annotationsErrorGroup = QtWidgets.QGroupBox(self.annotationsGroup)
        self.annotationsErrorGroup.setObjectName("annotationsErrorGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.annotationsErrorGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.annotationsErrorFgButton = QtWidgets.QPushButton(self.annotationsErrorGroup)
        self.annotationsErrorFgButton.setObjectName("annotationsErrorFgButton")
        self.gridLayout_4.addWidget(self.annotationsErrorFgButton, 0, 0, 1, 1)
        self.annotationsErrorBgButton = QtWidgets.QPushButton(self.annotationsErrorGroup)
        self.annotationsErrorBgButton.setObjectName("annotationsErrorBgButton")
        self.gridLayout_4.addWidget(self.annotationsErrorBgButton, 0, 1, 1, 1)
        self.annotationsErrorSample = QtWidgets.QLineEdit(self.annotationsErrorGroup)
        self.annotationsErrorSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.annotationsErrorSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.annotationsErrorSample.setReadOnly(True)
        self.annotationsErrorSample.setObjectName("annotationsErrorSample")
        self.gridLayout_4.addWidget(self.annotationsErrorSample, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.annotationsErrorGroup, 1, 1, 1, 1)
        self.annotationsStyleWarningGroup = QtWidgets.QGroupBox(self.annotationsGroup)
        self.annotationsStyleWarningGroup.setObjectName("annotationsStyleWarningGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.annotationsStyleWarningGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.annotationsStyleWarningFgButton = QtWidgets.QPushButton(self.annotationsStyleWarningGroup)
        self.annotationsStyleWarningFgButton.setObjectName("annotationsStyleWarningFgButton")
        self.gridLayout_5.addWidget(self.annotationsStyleWarningFgButton, 0, 0, 1, 1)
        self.annotationsStyleWarningBgButton = QtWidgets.QPushButton(self.annotationsStyleWarningGroup)
        self.annotationsStyleWarningBgButton.setObjectName("annotationsStyleWarningBgButton")
        self.gridLayout_5.addWidget(self.annotationsStyleWarningBgButton, 0, 1, 1, 1)
        self.annotationsStyleWarningSample = QtWidgets.QLineEdit(self.annotationsStyleWarningGroup)
        self.annotationsStyleWarningSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.annotationsStyleWarningSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.annotationsStyleWarningSample.setReadOnly(True)
        self.annotationsStyleWarningSample.setObjectName("annotationsStyleWarningSample")
        self.gridLayout_5.addWidget(self.annotationsStyleWarningSample, 1, 0, 1, 2)
        self.gridLayout_8.addWidget(self.annotationsStyleWarningGroup, 2, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.annotationsGroup)
        self.groupBox_13 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.enableChangeTraceCheckBox = QtWidgets.QCheckBox(self.groupBox_13)
        self.enableChangeTraceCheckBox.setObjectName("enableChangeTraceCheckBox")
        self.verticalLayout_3.addWidget(self.enableChangeTraceCheckBox)
        self._16 = QtWidgets.QHBoxLayout()
        self._16.setObjectName("_16")
        self.label_4 = QtWidgets.QLabel(self.groupBox_13)
        self.label_4.setObjectName("label_4")
        self._16.addWidget(self.label_4)
        self.changeTraceTimeoutSpinBox = QtWidgets.QSpinBox(self.groupBox_13)
        self.changeTraceTimeoutSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.changeTraceTimeoutSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.changeTraceTimeoutSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.changeTraceTimeoutSpinBox.setMinimum(100)
        self.changeTraceTimeoutSpinBox.setMaximum(5000)
        self.changeTraceTimeoutSpinBox.setSingleStep(100)
        self.changeTraceTimeoutSpinBox.setObjectName("changeTraceTimeoutSpinBox")
        self._16.addWidget(self.changeTraceTimeoutSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._16.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self._16)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TextLabel13_3_2_3 = QtWidgets.QLabel(self.groupBox_13)
        self.TextLabel13_3_2_3.setObjectName("TextLabel13_3_2_3")
        self.horizontalLayout_3.addWidget(self.TextLabel13_3_2_3)
        self.changeMarkerUnsavedColorButton = QtWidgets.QPushButton(self.groupBox_13)
        self.changeMarkerUnsavedColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.changeMarkerUnsavedColorButton.setText("")
        self.changeMarkerUnsavedColorButton.setObjectName("changeMarkerUnsavedColorButton")
        self.horizontalLayout_3.addWidget(self.changeMarkerUnsavedColorButton)
        self.TextLabel13_3_2_4 = QtWidgets.QLabel(self.groupBox_13)
        self.TextLabel13_3_2_4.setObjectName("TextLabel13_3_2_4")
        self.horizontalLayout_3.addWidget(self.TextLabel13_3_2_4)
        self.changeMarkerSavedColorButton = QtWidgets.QPushButton(self.groupBox_13)
        self.changeMarkerSavedColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.changeMarkerSavedColorButton.setText("")
        self.changeMarkerSavedColorButton.setObjectName("changeMarkerSavedColorButton")
        self.horizontalLayout_3.addWidget(self.changeMarkerSavedColorButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.groupBox_13)
        self.groupBox_11 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.whitespaceCheckBox = QtWidgets.QCheckBox(self.groupBox_11)
        self.whitespaceCheckBox.setObjectName("whitespaceCheckBox")
        self.verticalLayout_2.addWidget(self.whitespaceCheckBox)
        self._12 = QtWidgets.QHBoxLayout()
        self._12.setObjectName("_12")
        self.textLabel1_8 = QtWidgets.QLabel(self.groupBox_11)
        self.textLabel1_8.setObjectName("textLabel1_8")
        self._12.addWidget(self.textLabel1_8)
        self.whitespaceSizeSpinBox = QtWidgets.QSpinBox(self.groupBox_11)
        self.whitespaceSizeSpinBox.setMinimum(1)
        self.whitespaceSizeSpinBox.setMaximum(10)
        self.whitespaceSizeSpinBox.setObjectName("whitespaceSizeSpinBox")
        self._12.addWidget(self.whitespaceSizeSpinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._12.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self._12)
        self._15 = QtWidgets.QHBoxLayout()
        self._15.setObjectName("_15")
        self.TextLabel2_2_2_2_2_9 = QtWidgets.QLabel(self.groupBox_11)
        self.TextLabel2_2_2_2_2_9.setObjectName("TextLabel2_2_2_2_2_9")
        self._15.addWidget(self.TextLabel2_2_2_2_2_9)
        self.whitespaceForegroundButton = QtWidgets.QPushButton(self.groupBox_11)
        self.whitespaceForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.whitespaceForegroundButton.setText("")
        self.whitespaceForegroundButton.setObjectName("whitespaceForegroundButton")
        self._15.addWidget(self.whitespaceForegroundButton)
        self.TextLabel2_2_2_2_2_10 = QtWidgets.QLabel(self.groupBox_11)
        self.TextLabel2_2_2_2_2_10.setObjectName("TextLabel2_2_2_2_2_10")
        self._15.addWidget(self.TextLabel2_2_2_2_2_10)
        self.whitespaceBackgroundButton = QtWidgets.QPushButton(self.groupBox_11)
        self.whitespaceBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.whitespaceBackgroundButton.setText("")
        self.whitespaceBackgroundButton.setObjectName("whitespaceBackgroundButton")
        self._15.addWidget(self.whitespaceBackgroundButton)
        self.verticalLayout_2.addLayout(self._15)
        self.verticalLayout_8.addWidget(self.groupBox_11)
        self.groupBox_15 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.indentguidesCheckBox = QtWidgets.QCheckBox(self.groupBox_15)
        self.indentguidesCheckBox.setObjectName("indentguidesCheckBox")
        self.verticalLayout_5.addWidget(self.indentguidesCheckBox)
        self._18 = QtWidgets.QHBoxLayout()
        self._18.setObjectName("_18")
        self.TextLabel2_2_2_2_2_13 = QtWidgets.QLabel(self.groupBox_15)
        self.TextLabel2_2_2_2_2_13.setObjectName("TextLabel2_2_2_2_2_13")
        self._18.addWidget(self.TextLabel2_2_2_2_2_13)
        self.indentationGuidesForegroundButton = QtWidgets.QPushButton(self.groupBox_15)
        self.indentationGuidesForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.indentationGuidesForegroundButton.setText("")
        self.indentationGuidesForegroundButton.setObjectName("indentationGuidesForegroundButton")
        self._18.addWidget(self.indentationGuidesForegroundButton)
        self.TextLabel2_2_2_2_2_14 = QtWidgets.QLabel(self.groupBox_15)
        self.TextLabel2_2_2_2_2_14.setObjectName("TextLabel2_2_2_2_2_14")
        self._18.addWidget(self.TextLabel2_2_2_2_2_14)
        self.indentationGuidesBackgroundButton = QtWidgets.QPushButton(self.groupBox_15)
        self.indentationGuidesBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.indentationGuidesBackgroundButton.setText("")
        self.indentationGuidesBackgroundButton.setObjectName("indentationGuidesBackgroundButton")
        self._18.addWidget(self.indentationGuidesBackgroundButton)
        self.verticalLayout_5.addLayout(self._18)
        self.verticalLayout_8.addWidget(self.groupBox_15)
        self.groupBox_14 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox_14)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.errorsMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.errorsMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.errorsMapButton.setText("")
        self.errorsMapButton.setObjectName("errorsMapButton")
        self.gridLayout_9.addWidget(self.errorsMapButton, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_14)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 2, 1, 1)
        self.warningsMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.warningsMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.warningsMapButton.setText("")
        self.warningsMapButton.setObjectName("warningsMapButton")
        self.gridLayout_9.addWidget(self.warningsMapButton, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_14)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 1, 0, 1, 1)
        self.bookmarksMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.bookmarksMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.bookmarksMapButton.setText("")
        self.bookmarksMapButton.setObjectName("bookmarksMapButton")
        self.gridLayout_9.addWidget(self.bookmarksMapButton, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_14)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 2, 1, 1)
        self.breakpointsMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.breakpointsMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.breakpointsMapButton.setText("")
        self.breakpointsMapButton.setObjectName("breakpointsMapButton")
        self.gridLayout_9.addWidget(self.breakpointsMapButton, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_14)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.tasksMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.tasksMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.tasksMapButton.setText("")
        self.tasksMapButton.setObjectName("tasksMapButton")
        self.gridLayout_9.addWidget(self.tasksMapButton, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_14)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 2, 2, 1, 1)
        self.changesMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.changesMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.changesMapButton.setText("")
        self.changesMapButton.setObjectName("changesMapButton")
        self.gridLayout_9.addWidget(self.changesMapButton, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_14)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 3, 0, 1, 1)
        self.coverageMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.coverageMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.coverageMapButton.setText("")
        self.coverageMapButton.setObjectName("coverageMapButton")
        self.gridLayout_9.addWidget(self.coverageMapButton, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_14)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 3, 2, 1, 1)
        self.currentMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.currentMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.currentMapButton.setText("")
        self.currentMapButton.setObjectName("currentMapButton")
        self.gridLayout_9.addWidget(self.currentMapButton, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_14)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 4, 0, 1, 1)
        self.searchMarkerMapButton = QtWidgets.QPushButton(self.groupBox_14)
        self.searchMarkerMapButton.setMinimumSize(QtCore.QSize(100, 0))
        self.searchMarkerMapButton.setText("")
        self.searchMarkerMapButton.setObjectName("searchMarkerMapButton")
        self.gridLayout_9.addWidget(self.searchMarkerMapButton, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_14)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 5, 0, 1, 1)
        self.markerMapBackgroundButton = QtWidgets.QPushButton(self.groupBox_14)
        self.markerMapBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.markerMapBackgroundButton.setText("")
        self.markerMapBackgroundButton.setObjectName("markerMapBackgroundButton")
        self.gridLayout_9.addWidget(self.markerMapBackgroundButton, 5, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_14)
        self.groupBox_10 = QtWidgets.QGroupBox(EditorStylesPage)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.miniMenuCheckBox = QtWidgets.QCheckBox(self.groupBox_10)
        self.miniMenuCheckBox.setObjectName("miniMenuCheckBox")
        self.verticalLayout_7.addWidget(self.miniMenuCheckBox)
        self.hideFormatButtonsCheckBox = QtWidgets.QCheckBox(self.groupBox_10)
        self.hideFormatButtonsCheckBox.setObjectName("hideFormatButtonsCheckBox")
        self.verticalLayout_7.addWidget(self.hideFormatButtonsCheckBox)
        self.verticalLayout_8.addWidget(self.groupBox_10)
        spacerItem8 = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem8)

        self.retranslateUi(EditorStylesPage)
        self.edgeLineColumnSlider.valueChanged['int'].connect(self.edgeLineColumnLCD.display)
        self.zoomfactorSlider.valueChanged['int'].connect(self.zoomfactorLCD.display)
        self.editAreaOverrideCheckBox.toggled['bool'].connect(self.TextLabel2_2_2_2_2_12.setEnabled)
        self.editAreaOverrideCheckBox.toggled['bool'].connect(self.editAreaForegroundButton.setEnabled)
        self.editAreaOverrideCheckBox.toggled['bool'].connect(self.TextLabel2_2_2_2_2_11.setEnabled)
        self.editAreaOverrideCheckBox.toggled['bool'].connect(self.editAreaBackgroundButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EditorStylesPage)
        EditorStylesPage.setTabOrder(self.editAreaOverrideCheckBox, self.editAreaForegroundButton)
        EditorStylesPage.setTabOrder(self.editAreaForegroundButton, self.editAreaBackgroundButton)
        EditorStylesPage.setTabOrder(self.editAreaBackgroundButton, self.defaultFontButton)
        EditorStylesPage.setTabOrder(self.defaultFontButton, self.monospacedFontButton)
        EditorStylesPage.setTabOrder(self.monospacedFontButton, self.monospacedCheckBox)
        EditorStylesPage.setTabOrder(self.monospacedCheckBox, self.linenoCheckBox)
        EditorStylesPage.setTabOrder(self.linenoCheckBox, self.foldingCheckBox)
        EditorStylesPage.setTabOrder(self.foldingCheckBox, self.unifiedMarginsCheckBox)
        EditorStylesPage.setTabOrder(self.unifiedMarginsCheckBox, self.foldingStyleComboBox)
        EditorStylesPage.setTabOrder(self.foldingStyleComboBox, self.marginsForegroundButton)
        EditorStylesPage.setTabOrder(self.marginsForegroundButton, self.marginsBackgroundButton)
        EditorStylesPage.setTabOrder(self.marginsBackgroundButton, self.foldmarginBackgroundButton)
        EditorStylesPage.setTabOrder(self.foldmarginBackgroundButton, self.foldmarkersForegroundButton)
        EditorStylesPage.setTabOrder(self.foldmarkersForegroundButton, self.foldmarkersBackgroundButton)
        EditorStylesPage.setTabOrder(self.foldmarkersBackgroundButton, self.linenumbersFontButton)
        EditorStylesPage.setTabOrder(self.linenumbersFontButton, self.customSelColourCheckBox)
        EditorStylesPage.setTabOrder(self.customSelColourCheckBox, self.colourizeSelTextCheckBox)
        EditorStylesPage.setTabOrder(self.colourizeSelTextCheckBox, self.extentSelEolCheckBox)
        EditorStylesPage.setTabOrder(self.extentSelEolCheckBox, self.selectionForegroundButton)
        EditorStylesPage.setTabOrder(self.selectionForegroundButton, self.selectionBackgroundButton)
        EditorStylesPage.setTabOrder(self.selectionBackgroundButton, self.caretlineVisibleCheckBox)
        EditorStylesPage.setTabOrder(self.caretlineVisibleCheckBox, self.caretlineAlwaysVisibleCheckBox)
        EditorStylesPage.setTabOrder(self.caretlineAlwaysVisibleCheckBox, self.caretWidthSpinBox)
        EditorStylesPage.setTabOrder(self.caretWidthSpinBox, self.caretForegroundButton)
        EditorStylesPage.setTabOrder(self.caretForegroundButton, self.caretlineBackgroundButton)
        EditorStylesPage.setTabOrder(self.caretlineBackgroundButton, self.debugMarkerBackgroundCheckBox)
        EditorStylesPage.setTabOrder(self.debugMarkerBackgroundCheckBox, self.currentLineMarkerButton)
        EditorStylesPage.setTabOrder(self.currentLineMarkerButton, self.errorMarkerButton)
        EditorStylesPage.setTabOrder(self.errorMarkerButton, self.bracehighlightingCheckBox)
        EditorStylesPage.setTabOrder(self.bracehighlightingCheckBox, self.matchingBracesButton)
        EditorStylesPage.setTabOrder(self.matchingBracesButton, self.matchingBracesBackButton)
        EditorStylesPage.setTabOrder(self.matchingBracesBackButton, self.nonmatchingBracesButton)
        EditorStylesPage.setTabOrder(self.nonmatchingBracesButton, self.nonmatchingBracesBackButton)
        EditorStylesPage.setTabOrder(self.nonmatchingBracesBackButton, self.eolCheckBox)
        EditorStylesPage.setTabOrder(self.eolCheckBox, self.wrapModeComboBox)
        EditorStylesPage.setTabOrder(self.wrapModeComboBox, self.wrapVisualComboBox)
        EditorStylesPage.setTabOrder(self.wrapVisualComboBox, self.edgeModeCombo)
        EditorStylesPage.setTabOrder(self.edgeModeCombo, self.edgeLineColumnSlider)
        EditorStylesPage.setTabOrder(self.edgeLineColumnSlider, self.edgeBackgroundColorButton)
        EditorStylesPage.setTabOrder(self.edgeBackgroundColorButton, self.zoomfactorSlider)
        EditorStylesPage.setTabOrder(self.zoomfactorSlider, self.enableAnnotationsCheckBox)
        EditorStylesPage.setTabOrder(self.enableAnnotationsCheckBox, self.annotationsWarningFgButton)
        EditorStylesPage.setTabOrder(self.annotationsWarningFgButton, self.annotationsWarningBgButton)
        EditorStylesPage.setTabOrder(self.annotationsWarningBgButton, self.annotationsErrorFgButton)
        EditorStylesPage.setTabOrder(self.annotationsErrorFgButton, self.annotationsErrorBgButton)
        EditorStylesPage.setTabOrder(self.annotationsErrorBgButton, self.annotationsStyleWarningFgButton)
        EditorStylesPage.setTabOrder(self.annotationsStyleWarningFgButton, self.annotationsStyleWarningBgButton)
        EditorStylesPage.setTabOrder(self.annotationsStyleWarningBgButton, self.enableChangeTraceCheckBox)
        EditorStylesPage.setTabOrder(self.enableChangeTraceCheckBox, self.changeTraceTimeoutSpinBox)
        EditorStylesPage.setTabOrder(self.changeTraceTimeoutSpinBox, self.changeMarkerUnsavedColorButton)
        EditorStylesPage.setTabOrder(self.changeMarkerUnsavedColorButton, self.changeMarkerSavedColorButton)
        EditorStylesPage.setTabOrder(self.changeMarkerSavedColorButton, self.whitespaceCheckBox)
        EditorStylesPage.setTabOrder(self.whitespaceCheckBox, self.whitespaceSizeSpinBox)
        EditorStylesPage.setTabOrder(self.whitespaceSizeSpinBox, self.whitespaceForegroundButton)
        EditorStylesPage.setTabOrder(self.whitespaceForegroundButton, self.whitespaceBackgroundButton)
        EditorStylesPage.setTabOrder(self.whitespaceBackgroundButton, self.indentguidesCheckBox)
        EditorStylesPage.setTabOrder(self.indentguidesCheckBox, self.indentationGuidesForegroundButton)
        EditorStylesPage.setTabOrder(self.indentationGuidesForegroundButton, self.indentationGuidesBackgroundButton)
        EditorStylesPage.setTabOrder(self.indentationGuidesBackgroundButton, self.errorsMapButton)
        EditorStylesPage.setTabOrder(self.errorsMapButton, self.warningsMapButton)
        EditorStylesPage.setTabOrder(self.warningsMapButton, self.bookmarksMapButton)
        EditorStylesPage.setTabOrder(self.bookmarksMapButton, self.breakpointsMapButton)
        EditorStylesPage.setTabOrder(self.breakpointsMapButton, self.tasksMapButton)
        EditorStylesPage.setTabOrder(self.tasksMapButton, self.changesMapButton)
        EditorStylesPage.setTabOrder(self.changesMapButton, self.coverageMapButton)
        EditorStylesPage.setTabOrder(self.coverageMapButton, self.currentMapButton)
        EditorStylesPage.setTabOrder(self.currentMapButton, self.searchMarkerMapButton)
        EditorStylesPage.setTabOrder(self.searchMarkerMapButton, self.markerMapBackgroundButton)
        EditorStylesPage.setTabOrder(self.markerMapBackgroundButton, self.miniMenuCheckBox)
        EditorStylesPage.setTabOrder(self.miniMenuCheckBox, self.hideFormatButtonsCheckBox)

    def retranslateUi(self, EditorStylesPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("EditorStylesPage", "<b>Configure editor styles</b>"))
        self.label_3.setText(_translate("EditorStylesPage", "<b>Note:</b> Fonts and colors of the syntax highlighters have to be configured on the syntax highlighter styles page."))
        self.groupBox_12.setTitle(_translate("EditorStylesPage", "Colours"))
        self.editAreaOverrideCheckBox.setToolTip(_translate("EditorStylesPage", "Select to set the colour of the edit area different to the default style"))
        self.editAreaOverrideCheckBox.setText(_translate("EditorStylesPage", "Override edit area colours"))
        self.TextLabel2_2_2_2_2_12.setText(_translate("EditorStylesPage", "Edit area foreground:"))
        self.editAreaForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the edit area."))
        self.TextLabel2_2_2_2_2_11.setText(_translate("EditorStylesPage", "Edit area background:"))
        self.editAreaBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the edit area."))
        self.groupBox_5.setTitle(_translate("EditorStylesPage", "Fonts"))
        self.monospacedCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether the monospaced font should be used as default"))
        self.monospacedCheckBox.setText(_translate("EditorStylesPage", "Use monospaced as default"))
        self.defaultFontSample.setText(_translate("EditorStylesPage", "Default Text"))
        self.defaultFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the default font for the editor\'s text"))
        self.defaultFontButton.setText(_translate("EditorStylesPage", "Default Text Font"))
        self.monospacedFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the font to be used as the monospaced font"))
        self.monospacedFontButton.setText(_translate("EditorStylesPage", "Monospaced Font"))
        self.monospacedFontSample.setText(_translate("EditorStylesPage", "Monospaced Text"))
        self.groupBox.setTitle(_translate("EditorStylesPage", "Margins"))
        self.linenoCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether line numbers margin should be shown."))
        self.linenoCheckBox.setText(_translate("EditorStylesPage", "Show Line Numbers Margin"))
        self.foldingCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether the fold margin should be shown."))
        self.foldingCheckBox.setText(_translate("EditorStylesPage", "Show Fold Margin"))
        self.unifiedMarginsCheckBox.setToolTip(_translate("EditorStylesPage", "Select to show unified margins (like eric4 < 4.3.0)"))
        self.unifiedMarginsCheckBox.setText(_translate("EditorStylesPage", "Show unified margins"))
        self.TextLabel1_4_2_2.setText(_translate("EditorStylesPage", "Folding style:"))
        self.foldingStyleComboBox.setToolTip(_translate("EditorStylesPage", "Select the folding style to be used in the folding margin"))
        self.foldingStyleComboBox.setWhatsThis(_translate("EditorStylesPage", "<b>Folding style</b>\n"
"<p>Select the desired folding style to be used in the folding margin.</p>\n"
"<p>The available styles are:\n"
"<ul>\n"
"<li>Plain - simple plus and minus symbols</li>\n"
"<li>Circled - circled plus and minus symbols</li>\n"
"<li>Boxed - boxed plus and minus symbols</li>\n"
"<li>Circled Tree - circled plus and minus symbols and flattened tree with rounded corners</li>\n"
"<li>Boxed Tree - boxed plus and minus symbols and flattened tree with rectangled corners</li>\n"
"</ul>\n"
"</p>"))
        self.foldingStyleComboBox.setItemText(0, _translate("EditorStylesPage", "Plain"))
        self.foldingStyleComboBox.setItemText(1, _translate("EditorStylesPage", "Circled"))
        self.foldingStyleComboBox.setItemText(2, _translate("EditorStylesPage", "Boxed"))
        self.foldingStyleComboBox.setItemText(3, _translate("EditorStylesPage", "Circled Tree"))
        self.foldingStyleComboBox.setItemText(4, _translate("EditorStylesPage", "Boxed Tree"))
        self.foldingStyleComboBox.setItemText(5, _translate("EditorStylesPage", "Arrow"))
        self.foldingStyleComboBox.setItemText(6, _translate("EditorStylesPage", "Arrow Tree"))
        self.TextLabel2_2_2_2_2_6.setText(_translate("EditorStylesPage", "Margins foreground:"))
        self.marginsForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the margins"))
        self.TextLabel2_2_2_2_2_7.setText(_translate("EditorStylesPage", "Margins background:"))
        self.marginsBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the margins"))
        self.TextLabel2_2_2_2_2_8.setText(_translate("EditorStylesPage", "Foldmargin background:"))
        self.foldmarginBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the foldmargin"))
        self.label.setText(_translate("EditorStylesPage", "Foldmarkers foreground:"))
        self.foldmarkersForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour of the foldmarkers"))
        self.label_2.setText(_translate("EditorStylesPage", "Foldmarkers background:"))
        self.foldmarkersBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour of the foldmarkers"))
        self.linenumbersFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the font for the editor line numbers"))
        self.linenumbersFontButton.setText(_translate("EditorStylesPage", "Line Numbers Font"))
        self.marginsFontSample.setText(_translate("EditorStylesPage", "2345"))
        self.groupBox_3.setTitle(_translate("EditorStylesPage", "Selection"))
        self.customSelColourCheckBox.setToolTip(_translate("EditorStylesPage", "Select to use custom selection colours"))
        self.customSelColourCheckBox.setWhatsThis(_translate("EditorStylesPage", "<b>Use custom selection colours</b><p>Select this entry in order to use custom selection colours in the editor and shell windows. The colours for the selection foreground and background are defined on the colours page.</p>"))
        self.customSelColourCheckBox.setText(_translate("EditorStylesPage", "Use custom selection colours"))
        self.colourizeSelTextCheckBox.setToolTip(_translate("EditorStylesPage", "Select, if selected text should be colourized by the lexer."))
        self.colourizeSelTextCheckBox.setText(_translate("EditorStylesPage", "Colourize selected text"))
        self.extentSelEolCheckBox.setToolTip(_translate("EditorStylesPage", "Select to extend selection to end of line"))
        self.extentSelEolCheckBox.setText(_translate("EditorStylesPage", "Extend selection to end of line"))
        self.TextLabel2_2_2_2_2_4.setText(_translate("EditorStylesPage", "Selection foreground:"))
        self.selectionForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the selection."))
        self.TextLabel2_2_2_2_2_5.setText(_translate("EditorStylesPage", "Selection background:"))
        self.selectionBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the selection."))
        self.groupBox_4.setTitle(_translate("EditorStylesPage", "Caret"))
        self.caretlineVisibleCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether the caretline should be highlighted"))
        self.caretlineVisibleCheckBox.setText(_translate("EditorStylesPage", "Caretline visible"))
        self.caretlineAlwaysVisibleCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether the caretline should be highlighted even if the editor doesn\'t have the focus"))
        self.caretlineAlwaysVisibleCheckBox.setText(_translate("EditorStylesPage", "Caretline always visible"))
        self.textLabel1_7.setText(_translate("EditorStylesPage", "Caret width:"))
        self.caretWidthSpinBox.setToolTip(_translate("EditorStylesPage", "Select caret width (1, 2 or 3 pixels)"))
        self.TextLabel2_2_2_2_2_2.setText(_translate("EditorStylesPage", "Caret foreground:"))
        self.caretForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the caret."))
        self.TextLabel2_2_2_2_2_3.setText(_translate("EditorStylesPage", "Caretline background:"))
        self.caretlineBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the line containing the caret."))
        self.groupBox_2.setTitle(_translate("EditorStylesPage", "Debugging Line Markers"))
        self.debugMarkerBackgroundCheckBox.setToolTip(_translate("EditorStylesPage", "Select to indicate the debug markers using coloured line backgrounds, arrow indicators otherwise"))
        self.debugMarkerBackgroundCheckBox.setText(_translate("EditorStylesPage", "Use background colours"))
        self.TextLabel3_2_2.setText(_translate("EditorStylesPage", "Current line marker:"))
        self.currentLineMarkerButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the current line marker."))
        self.TextLabel4_2_2.setText(_translate("EditorStylesPage", "Error line marker:"))
        self.errorMarkerButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the error line marker."))
        self.groupBox_6.setTitle(_translate("EditorStylesPage", "Braces"))
        self.bracehighlightingCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether matching and bad braces shall be highlighted."))
        self.bracehighlightingCheckBox.setText(_translate("EditorStylesPage", "Highlight braces"))
        self.TextLabel1_3_2.setText(_translate("EditorStylesPage", "Matched braces:"))
        self.matchingBracesButton.setToolTip(_translate("EditorStylesPage", "Select the colour for highlighting matching braces."))
        self.TextLabel1_3_2_2.setText(_translate("EditorStylesPage", "Matched braces background:"))
        self.matchingBracesBackButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for highlighting matching braces."))
        self.TextLabel2_2_2.setText(_translate("EditorStylesPage", "Unmatched brace:"))
        self.nonmatchingBracesButton.setToolTip(_translate("EditorStylesPage", "Select the colour for  highlighting nonmatching braces."))
        self.TextLabel2_2_2_3.setText(_translate("EditorStylesPage", "Unmatched brace background:"))
        self.nonmatchingBracesBackButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for  highlighting nonmatching braces."))
        self.groupBox_7.setTitle(_translate("EditorStylesPage", "End of Line"))
        self.eolCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether end of line shall be shown"))
        self.eolCheckBox.setText(_translate("EditorStylesPage", "Show End of Line"))
        self.wrapLongLinesGroup.setTitle(_translate("EditorStylesPage", "Wrap long lines"))
        self.textLabel1_15.setText(_translate("EditorStylesPage", "Mode:"))
        self.wrapModeComboBox.setToolTip(_translate("EditorStylesPage", "Select the wrap mode for long lines"))
        self.label_5.setText(_translate("EditorStylesPage", "Indication:"))
        self.wrapVisualComboBox.setToolTip(_translate("EditorStylesPage", "Select, how wrapped lines are indicated"))
        self.groupBox_9.setTitle(_translate("EditorStylesPage", "Edge Mode"))
        self.edgeBackgroundColorButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the edge marker."))
        self.TextLabel13_3_2_2.setText(_translate("EditorStylesPage", "Background colour:"))
        self.edgeLineColumnSlider.setToolTip(_translate("EditorStylesPage", "Move to set the edge column."))
        self.edgeLineColumnLCD.setToolTip(_translate("EditorStylesPage", "Displays the selected tab width."))
        self.TextLabel13_3_2.setText(_translate("EditorStylesPage", "Column number:"))
        self.textLabel1_14.setText(_translate("EditorStylesPage", "Mode:"))
        self.edgeModeCombo.setItemText(0, _translate("EditorStylesPage", "Disabled"))
        self.edgeModeCombo.setItemText(1, _translate("EditorStylesPage", "Draw Line"))
        self.edgeModeCombo.setItemText(2, _translate("EditorStylesPage", "Change Background Colour"))
        self.groupBox_8.setTitle(_translate("EditorStylesPage", "Zoom"))
        self.TextLabel13_2_2_3.setText(_translate("EditorStylesPage", "Initial zoom factor:"))
        self.zoomfactorSlider.setToolTip(_translate("EditorStylesPage", "Move to set the initial zoom factor"))
        self.zoomfactorLCD.setToolTip(_translate("EditorStylesPage", "Displays the selected initial zoom factor"))
        self.annotationsGroup.setTitle(_translate("EditorStylesPage", "Annotations"))
        self.enableAnnotationsCheckBox.setStatusTip(_translate("EditorStylesPage", "Select to enable the display of annotations"))
        self.enableAnnotationsCheckBox.setText(_translate("EditorStylesPage", "Show annotations"))
        self.annotationsWarningGroup.setTitle(_translate("EditorStylesPage", "Warnings"))
        self.annotationsWarningFgButton.setToolTip(_translate("EditorStylesPage", "Press to select the foreground colour"))
        self.annotationsWarningFgButton.setText(_translate("EditorStylesPage", "Foreground"))
        self.annotationsWarningBgButton.setToolTip(_translate("EditorStylesPage", "Press to select the background colour"))
        self.annotationsWarningBgButton.setText(_translate("EditorStylesPage", "Background"))
        self.annotationsWarningSample.setText(_translate("EditorStylesPage", "Warning: There might be an issue."))
        self.annotationsErrorGroup.setTitle(_translate("EditorStylesPage", "Errors"))
        self.annotationsErrorFgButton.setToolTip(_translate("EditorStylesPage", "Press to select the foreground colour"))
        self.annotationsErrorFgButton.setText(_translate("EditorStylesPage", "Foreground"))
        self.annotationsErrorBgButton.setToolTip(_translate("EditorStylesPage", "Press to select the background colour"))
        self.annotationsErrorBgButton.setText(_translate("EditorStylesPage", "Background"))
        self.annotationsErrorSample.setText(_translate("EditorStylesPage", "Error: There is an issue."))
        self.annotationsStyleWarningGroup.setTitle(_translate("EditorStylesPage", "Style"))
        self.annotationsStyleWarningFgButton.setToolTip(_translate("EditorStylesPage", "Press to select the foreground colour"))
        self.annotationsStyleWarningFgButton.setText(_translate("EditorStylesPage", "Foreground"))
        self.annotationsStyleWarningBgButton.setToolTip(_translate("EditorStylesPage", "Press to select the background colour"))
        self.annotationsStyleWarningBgButton.setText(_translate("EditorStylesPage", "Background"))
        self.annotationsStyleWarningSample.setText(_translate("EditorStylesPage", "Style: There is a style issue."))
        self.groupBox_13.setTitle(_translate("EditorStylesPage", "Change Tracing"))
        self.enableChangeTraceCheckBox.setToolTip(_translate("EditorStylesPage", "Select to mark changed lines"))
        self.enableChangeTraceCheckBox.setText(_translate("EditorStylesPage", "Mark changed lines"))
        self.label_4.setText(_translate("EditorStylesPage", "Timeout for marking changed lines:"))
        self.changeTraceTimeoutSpinBox.setToolTip(_translate("EditorStylesPage", "Enter the time in milliseconds after which changed lines will be marked"))
        self.changeTraceTimeoutSpinBox.setSuffix(_translate("EditorStylesPage", " ms"))
        self.TextLabel13_3_2_3.setText(_translate("EditorStylesPage", "Unsaved changes colour:"))
        self.changeMarkerUnsavedColorButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the change marker for unsaved changes."))
        self.TextLabel13_3_2_4.setText(_translate("EditorStylesPage", "Saved changes colour:"))
        self.changeMarkerSavedColorButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the change marker for saved changes."))
        self.groupBox_11.setTitle(_translate("EditorStylesPage", "Whitespace"))
        self.whitespaceCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether whitspace characters shall be shown"))
        self.whitespaceCheckBox.setText(_translate("EditorStylesPage", "Show Whitespace"))
        self.textLabel1_8.setText(_translate("EditorStylesPage", "Whitespace size:"))
        self.whitespaceSizeSpinBox.setToolTip(_translate("EditorStylesPage", "Select the size of the dots used to represent visible whitespace"))
        self.TextLabel2_2_2_2_2_9.setText(_translate("EditorStylesPage", "Whitespace foreground:"))
        self.whitespaceForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for visible whitespace"))
        self.TextLabel2_2_2_2_2_10.setText(_translate("EditorStylesPage", "Whitespace background:"))
        self.whitespaceBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for visible whitespace"))
        self.groupBox_15.setTitle(_translate("EditorStylesPage", "Indentation Guides"))
        self.indentguidesCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether indentation guides should be shown."))
        self.indentguidesCheckBox.setText(_translate("EditorStylesPage", "Show Indentation Guides"))
        self.TextLabel2_2_2_2_2_13.setText(_translate("EditorStylesPage", "Indentation Guides foreground:"))
        self.indentationGuidesForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for indentation guides"))
        self.TextLabel2_2_2_2_2_14.setText(_translate("EditorStylesPage", "Indentation Guides background:"))
        self.indentationGuidesBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for indentation guides"))
        self.groupBox_14.setTitle(_translate("EditorStylesPage", "Marker Map"))
        self.label_6.setText(_translate("EditorStylesPage", "Errors:"))
        self.errorsMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for error markers"))
        self.label_7.setText(_translate("EditorStylesPage", "Warnings:"))
        self.warningsMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for warning markers"))
        self.label_8.setText(_translate("EditorStylesPage", "Bookmarks:"))
        self.bookmarksMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for bookmark markers"))
        self.label_9.setText(_translate("EditorStylesPage", "Breakpoints:"))
        self.breakpointsMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for breakpoint markers"))
        self.label_10.setText(_translate("EditorStylesPage", "Tasks:"))
        self.tasksMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for task markers"))
        self.label_11.setText(_translate("EditorStylesPage", "Changes:"))
        self.changesMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for change markers"))
        self.label_12.setText(_translate("EditorStylesPage", "Coverage:"))
        self.coverageMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for coverage markers"))
        self.label_13.setText(_translate("EditorStylesPage", "Current Line:"))
        self.currentMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the current line marker"))
        self.label_15.setText(_translate("EditorStylesPage", "Search Markers:"))
        self.searchMarkerMapButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the search marker"))
        self.label_14.setText(_translate("EditorStylesPage", "Background:"))
        self.markerMapBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the marker map"))
        self.groupBox_10.setTitle(_translate("EditorStylesPage", "Various"))
        self.miniMenuCheckBox.setToolTip(_translate("EditorStylesPage", "Select to show a minimalistic context menu"))
        self.miniMenuCheckBox.setText(_translate("EditorStylesPage", "Show minimal context menu"))
        self.hideFormatButtonsCheckBox.setToolTip(_translate("EditorStylesPage", "Select to hide the Format Buttons bar when formatting is not supported"))
        self.hideFormatButtonsCheckBox.setText(_translate("EditorStylesPage", "Hide Format Buttons bar when not supported"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditorStylesPage = QtWidgets.QWidget()
    ui = Ui_EditorStylesPage()
    ui.setupUi(EditorStylesPage)
    EditorStylesPage.show()
    sys.exit(app.exec_())

