# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\EditorAPIsPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditorAPIsPage(object):
    def setupUi(self, EditorAPIsPage):
        EditorAPIsPage.setObjectName("EditorAPIsPage")
        EditorAPIsPage.resize(462, 539)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditorAPIsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(EditorAPIsPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line5 = QtWidgets.QFrame(EditorAPIsPage)
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setObjectName("line5")
        self.verticalLayout.addWidget(self.line5)
        self.apiAutoPrepareCheckBox = QtWidgets.QCheckBox(EditorAPIsPage)
        self.apiAutoPrepareCheckBox.setObjectName("apiAutoPrepareCheckBox")
        self.verticalLayout.addWidget(self.apiAutoPrepareCheckBox)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextLabel1_3_3 = QtWidgets.QLabel(EditorAPIsPage)
        self.TextLabel1_3_3.setToolTip("")
        self.TextLabel1_3_3.setObjectName("TextLabel1_3_3")
        self.gridLayout_2.addWidget(self.TextLabel1_3_3, 0, 0, 1, 1)
        self.apiLanguageComboBox = QtWidgets.QComboBox(EditorAPIsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiLanguageComboBox.sizePolicy().hasHeightForWidth())
        self.apiLanguageComboBox.setSizePolicy(sizePolicy)
        self.apiLanguageComboBox.setObjectName("apiLanguageComboBox")
        self.gridLayout_2.addWidget(self.apiLanguageComboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(EditorAPIsPage)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.projectTypeComboBox = QtWidgets.QComboBox(EditorAPIsPage)
        self.projectTypeComboBox.setObjectName("projectTypeComboBox")
        self.gridLayout_2.addWidget(self.projectTypeComboBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.apiGroup = QtWidgets.QGroupBox(EditorAPIsPage)
        self.apiGroup.setEnabled(False)
        self.apiGroup.setObjectName("apiGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.apiGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.apiList = QtWidgets.QListWidget(self.apiGroup)
        self.apiList.setAlternatingRowColors(True)
        self.apiList.setObjectName("apiList")
        self.gridLayout.addWidget(self.apiList, 0, 0, 1, 3)
        self.deleteApiFileButton = QtWidgets.QPushButton(self.apiGroup)
        self.deleteApiFileButton.setObjectName("deleteApiFileButton")
        self.gridLayout.addWidget(self.deleteApiFileButton, 1, 0, 1, 1)
        self.addApiFileButton = QtWidgets.QPushButton(self.apiGroup)
        self.addApiFileButton.setObjectName("addApiFileButton")
        self.gridLayout.addWidget(self.addApiFileButton, 1, 1, 1, 1)
        self.apiFilePicker = E5PathPicker(self.apiGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiFilePicker.sizePolicy().hasHeightForWidth())
        self.apiFilePicker.setSizePolicy(sizePolicy)
        self.apiFilePicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.apiFilePicker.setObjectName("apiFilePicker")
        self.gridLayout.addWidget(self.apiFilePicker, 1, 2, 1, 1)
        self.addInstalledApiFileButton = QtWidgets.QPushButton(self.apiGroup)
        self.addInstalledApiFileButton.setObjectName("addInstalledApiFileButton")
        self.gridLayout.addWidget(self.addInstalledApiFileButton, 2, 1, 1, 2)
        self.addPluginApiFileButton = QtWidgets.QPushButton(self.apiGroup)
        self.addPluginApiFileButton.setObjectName("addPluginApiFileButton")
        self.gridLayout.addWidget(self.addPluginApiFileButton, 3, 1, 1, 2)
        self.line = QtWidgets.QFrame(self.apiGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 3)
        self.prepareApiButton = QtWidgets.QPushButton(self.apiGroup)
        self.prepareApiButton.setObjectName("prepareApiButton")
        self.gridLayout.addWidget(self.prepareApiButton, 5, 0, 1, 1)
        self.prepareApiProgressBar = QtWidgets.QProgressBar(self.apiGroup)
        self.prepareApiProgressBar.setProperty("value", 0)
        self.prepareApiProgressBar.setTextVisible(False)
        self.prepareApiProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.prepareApiProgressBar.setObjectName("prepareApiProgressBar")
        self.gridLayout.addWidget(self.prepareApiProgressBar, 5, 1, 1, 2)
        self.verticalLayout.addWidget(self.apiGroup)

        self.retranslateUi(EditorAPIsPage)
        QtCore.QMetaObject.connectSlotsByName(EditorAPIsPage)
        EditorAPIsPage.setTabOrder(self.apiAutoPrepareCheckBox, self.apiLanguageComboBox)
        EditorAPIsPage.setTabOrder(self.apiLanguageComboBox, self.projectTypeComboBox)
        EditorAPIsPage.setTabOrder(self.projectTypeComboBox, self.apiList)
        EditorAPIsPage.setTabOrder(self.apiList, self.deleteApiFileButton)
        EditorAPIsPage.setTabOrder(self.deleteApiFileButton, self.addApiFileButton)
        EditorAPIsPage.setTabOrder(self.addApiFileButton, self.apiFilePicker)
        EditorAPIsPage.setTabOrder(self.apiFilePicker, self.addInstalledApiFileButton)
        EditorAPIsPage.setTabOrder(self.addInstalledApiFileButton, self.addPluginApiFileButton)
        EditorAPIsPage.setTabOrder(self.addPluginApiFileButton, self.prepareApiButton)

    def retranslateUi(self, EditorAPIsPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("EditorAPIsPage", "<b>Configure API files</b>"))
        self.apiAutoPrepareCheckBox.setToolTip(_translate("EditorAPIsPage", "Select to compile the APIs automatically upon loading"))
        self.apiAutoPrepareCheckBox.setText(_translate("EditorAPIsPage", "Compile APIs automatically"))
        self.TextLabel1_3_3.setText(_translate("EditorAPIsPage", "Language:"))
        self.apiLanguageComboBox.setToolTip(_translate("EditorAPIsPage", "Select the language to be configured."))
        self.label.setText(_translate("EditorAPIsPage", "Project Type:"))
        self.projectTypeComboBox.setToolTip(_translate("EditorAPIsPage", "Select the project type to be configured"))
        self.apiGroup.setTitle(_translate("EditorAPIsPage", "APIs"))
        self.apiList.setToolTip(_translate("EditorAPIsPage", "List of API files"))
        self.deleteApiFileButton.setToolTip(_translate("EditorAPIsPage", "Press to delete the selected file from the list"))
        self.deleteApiFileButton.setText(_translate("EditorAPIsPage", "Delete"))
        self.addApiFileButton.setToolTip(_translate("EditorAPIsPage", "Press to add the entered file to the list"))
        self.addApiFileButton.setText(_translate("EditorAPIsPage", "Add"))
        self.addInstalledApiFileButton.setToolTip(_translate("EditorAPIsPage", "Press to select an API file from the list of installed API files"))
        self.addInstalledApiFileButton.setText(_translate("EditorAPIsPage", "Add from installed APIs"))
        self.addPluginApiFileButton.setToolTip(_translate("EditorAPIsPage", "Press to select an API file from the list of API files installed by plugins"))
        self.addPluginApiFileButton.setText(_translate("EditorAPIsPage", "Add from Plugin APIs"))
        self.prepareApiButton.setToolTip(_translate("EditorAPIsPage", "Press to compile the selected APIs definition"))
        self.prepareApiButton.setText(_translate("EditorAPIsPage", "Compile APIs"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditorAPIsPage = QtWidgets.QWidget()
    ui = Ui_EditorAPIsPage()
    ui.setupUi(EditorAPIsPage)
    EditorAPIsPage.show()
    sys.exit(app.exec_())

