# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\HelpAppearancePage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpAppearancePage(object):
    def setupUi(self, HelpAppearancePage):
        HelpAppearancePage.setObjectName("HelpAppearancePage")
        HelpAppearancePage.resize(499, 547)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(HelpAppearancePage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerLabel = QtWidgets.QLabel(HelpAppearancePage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line17 = QtWidgets.QFrame(HelpAppearancePage)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setObjectName("line17")
        self.verticalLayout_3.addWidget(self.line17)
        self.groupBox_5 = QtWidgets.QGroupBox(HelpAppearancePage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.standardFontButton = QtWidgets.QPushButton(self.groupBox_5)
        self.standardFontButton.setObjectName("standardFontButton")
        self.gridLayout.addWidget(self.standardFontButton, 0, 0, 1, 1)
        self.standardFontSample = QtWidgets.QLineEdit(self.groupBox_5)
        self.standardFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.standardFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.standardFontSample.setReadOnly(True)
        self.standardFontSample.setObjectName("standardFontSample")
        self.gridLayout.addWidget(self.standardFontSample, 0, 1, 1, 1)
        self.fixedFontButton = QtWidgets.QPushButton(self.groupBox_5)
        self.fixedFontButton.setObjectName("fixedFontButton")
        self.gridLayout.addWidget(self.fixedFontButton, 1, 0, 1, 1)
        self.fixedFontSample = QtWidgets.QLineEdit(self.groupBox_5)
        self.fixedFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fixedFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.fixedFontSample.setReadOnly(True)
        self.fixedFontSample.setObjectName("fixedFontSample")
        self.gridLayout.addWidget(self.fixedFontSample, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(HelpAppearancePage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel1_3 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.gridLayout_2.addWidget(self.textLabel1_3, 0, 0, 1, 1)
        self.secureURLsColourButton = QtWidgets.QPushButton(self.groupBox_3)
        self.secureURLsColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.secureURLsColourButton.setText("")
        self.secureURLsColourButton.setObjectName("secureURLsColourButton")
        self.gridLayout_2.addWidget(self.secureURLsColourButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(HelpAppearancePage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autoLoadImagesCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.autoLoadImagesCheckBox.setObjectName("autoLoadImagesCheckBox")
        self.verticalLayout.addWidget(self.autoLoadImagesCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(HelpAppearancePage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.styleSheetPicker = E5PathPicker(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleSheetPicker.sizePolicy().hasHeightForWidth())
        self.styleSheetPicker.setSizePolicy(sizePolicy)
        self.styleSheetPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.styleSheetPicker.setObjectName("styleSheetPicker")
        self.horizontalLayout.addWidget(self.styleSheetPicker)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabsGroupBox = QtWidgets.QGroupBox(HelpAppearancePage)
        self.tabsGroupBox.setObjectName("tabsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabsCloseButtonCheckBox = QtWidgets.QCheckBox(self.tabsGroupBox)
        self.tabsCloseButtonCheckBox.setObjectName("tabsCloseButtonCheckBox")
        self.verticalLayout_2.addWidget(self.tabsCloseButtonCheckBox)
        self.warnOnMultipleCloseCheckBox = QtWidgets.QCheckBox(self.tabsGroupBox)
        self.warnOnMultipleCloseCheckBox.setObjectName("warnOnMultipleCloseCheckBox")
        self.verticalLayout_2.addWidget(self.warnOnMultipleCloseCheckBox)
        self.verticalLayout_3.addWidget(self.tabsGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(479, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(HelpAppearancePage)
        QtCore.QMetaObject.connectSlotsByName(HelpAppearancePage)
        HelpAppearancePage.setTabOrder(self.standardFontButton, self.fixedFontButton)
        HelpAppearancePage.setTabOrder(self.fixedFontButton, self.secureURLsColourButton)
        HelpAppearancePage.setTabOrder(self.secureURLsColourButton, self.autoLoadImagesCheckBox)
        HelpAppearancePage.setTabOrder(self.autoLoadImagesCheckBox, self.styleSheetPicker)
        HelpAppearancePage.setTabOrder(self.styleSheetPicker, self.tabsCloseButtonCheckBox)
        HelpAppearancePage.setTabOrder(self.tabsCloseButtonCheckBox, self.warnOnMultipleCloseCheckBox)

    def retranslateUi(self, HelpAppearancePage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("HelpAppearancePage", "<b>Configure help viewer appearance</b>"))
        self.groupBox_5.setTitle(_translate("HelpAppearancePage", "Fonts"))
        self.standardFontButton.setToolTip(_translate("HelpAppearancePage", "Press to select the standard font"))
        self.standardFontButton.setText(_translate("HelpAppearancePage", "Standard Font"))
        self.standardFontSample.setText(_translate("HelpAppearancePage", "Times 16"))
        self.fixedFontButton.setToolTip(_translate("HelpAppearancePage", "Press to select the fixed-width font"))
        self.fixedFontButton.setText(_translate("HelpAppearancePage", "Fixed-Width Font"))
        self.fixedFontSample.setText(_translate("HelpAppearancePage", "Courier 13"))
        self.groupBox_3.setTitle(_translate("HelpAppearancePage", "Colours"))
        self.textLabel1_3.setText(_translate("HelpAppearancePage", "Background colour of secure URLs:"))
        self.secureURLsColourButton.setToolTip(_translate("HelpAppearancePage", "Select the background colour for secure URLs."))
        self.groupBox.setTitle(_translate("HelpAppearancePage", "Images"))
        self.autoLoadImagesCheckBox.setToolTip(_translate("HelpAppearancePage", "Select to load images"))
        self.autoLoadImagesCheckBox.setText(_translate("HelpAppearancePage", "Load images"))
        self.groupBox_2.setTitle(_translate("HelpAppearancePage", "Style Sheet"))
        self.label.setText(_translate("HelpAppearancePage", "User Style Sheet:"))
        self.styleSheetPicker.setToolTip(_translate("HelpAppearancePage", "Enter the file name of a user style sheet"))
        self.tabsGroupBox.setTitle(_translate("HelpAppearancePage", "Tabs"))
        self.tabsCloseButtonCheckBox.setText(_translate("HelpAppearancePage", "Show only one close button instead of one for each tab"))
        self.warnOnMultipleCloseCheckBox.setToolTip(_translate("HelpAppearancePage", "Select to issue a warning, if multiple tabs are about to be closed"))
        self.warnOnMultipleCloseCheckBox.setText(_translate("HelpAppearancePage", "Warn, if multiple tabs are about to be closed"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpAppearancePage = QtWidgets.QWidget()
    ui = Ui_HelpAppearancePage()
    ui.setupUi(HelpAppearancePage)
    HelpAppearancePage.show()
    sys.exit(app.exec_())

