# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\HelpWebBrowserPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpWebBrowserPage(object):
    def setupUi(self, HelpWebBrowserPage):
        HelpWebBrowserPage.setObjectName("HelpWebBrowserPage")
        HelpWebBrowserPage.resize(616, 1329)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(HelpWebBrowserPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.headerLabel = QtWidgets.QLabel(HelpWebBrowserPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_5.addWidget(self.headerLabel)
        self.line17 = QtWidgets.QFrame(HelpWebBrowserPage)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setObjectName("line17")
        self.verticalLayout_5.addWidget(self.line17)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.singleHelpWindowCheckBox = QtWidgets.QCheckBox(HelpWebBrowserPage)
        self.singleHelpWindowCheckBox.setObjectName("singleHelpWindowCheckBox")
        self.gridLayout_5.addWidget(self.singleHelpWindowCheckBox, 0, 0, 1, 1)
        self.webSuggestionsCheckBox = QtWidgets.QCheckBox(HelpWebBrowserPage)
        self.webSuggestionsCheckBox.setObjectName("webSuggestionsCheckBox")
        self.gridLayout_5.addWidget(self.webSuggestionsCheckBox, 0, 1, 1, 1)
        self.saveGeometryCheckBox = QtWidgets.QCheckBox(HelpWebBrowserPage)
        self.saveGeometryCheckBox.setObjectName("saveGeometryCheckBox")
        self.gridLayout_5.addWidget(self.saveGeometryCheckBox, 1, 0, 1, 1)
        self.showTabPreviews = QtWidgets.QCheckBox(HelpWebBrowserPage)
        self.showTabPreviews.setObjectName("showTabPreviews")
        self.gridLayout_5.addWidget(self.showTabPreviews, 1, 1, 1, 1)
        self.quirksCheckBox = QtWidgets.QCheckBox(HelpWebBrowserPage)
        self.quirksCheckBox.setObjectName("quirksCheckBox")
        self.gridLayout_5.addWidget(self.quirksCheckBox, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.startupGroupBox = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.startupGroupBox.setObjectName("startupGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.startupGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.startupGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.startupCombo = QtWidgets.QComboBox(self.startupGroupBox)
        self.startupCombo.setObjectName("startupCombo")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.gridLayout_3.addWidget(self.startupCombo, 0, 1, 1, 3)
        self.homePageLabel = QtWidgets.QLabel(self.startupGroupBox)
        self.homePageLabel.setObjectName("homePageLabel")
        self.gridLayout_3.addWidget(self.homePageLabel, 1, 0, 1, 1)
        self.homePageEdit = QtWidgets.QLineEdit(self.startupGroupBox)
        self.homePageEdit.setObjectName("homePageEdit")
        self.gridLayout_3.addWidget(self.homePageEdit, 1, 1, 1, 3)
        self.setCurrentPageButton = QtWidgets.QPushButton(self.startupGroupBox)
        self.setCurrentPageButton.setObjectName("setCurrentPageButton")
        self.gridLayout_3.addWidget(self.setCurrentPageButton, 2, 1, 1, 1)
        self.defaultHomeButton = QtWidgets.QPushButton(self.startupGroupBox)
        self.defaultHomeButton.setObjectName("defaultHomeButton")
        self.gridLayout_3.addWidget(self.defaultHomeButton, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.startupGroupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.defaultSchemeCombo = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultSchemeCombo.sizePolicy().hasHeightForWidth())
        self.defaultSchemeCombo.setSizePolicy(sizePolicy)
        self.defaultSchemeCombo.setEditable(False)
        self.defaultSchemeCombo.setObjectName("defaultSchemeCombo")
        self.gridLayout_4.addWidget(self.defaultSchemeCombo, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.privacyGroup = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.privacyGroup.setObjectName("privacyGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.privacyGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.javaCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.javaCheckBox.setObjectName("javaCheckBox")
        self.verticalLayout_4.addWidget(self.javaCheckBox)
        self.javaScriptGroup = QtWidgets.QGroupBox(self.privacyGroup)
        self.javaScriptGroup.setCheckable(True)
        self.javaScriptGroup.setChecked(False)
        self.javaScriptGroup.setObjectName("javaScriptGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.javaScriptGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.jsOpenWindowsCheckBox = QtWidgets.QCheckBox(self.javaScriptGroup)
        self.jsOpenWindowsCheckBox.setObjectName("jsOpenWindowsCheckBox")
        self.gridLayout.addWidget(self.jsOpenWindowsCheckBox, 0, 0, 1, 1)
        self.jsCloseWindowsCheckBox = QtWidgets.QCheckBox(self.javaScriptGroup)
        self.jsCloseWindowsCheckBox.setObjectName("jsCloseWindowsCheckBox")
        self.gridLayout.addWidget(self.jsCloseWindowsCheckBox, 0, 1, 1, 1)
        self.jsClipboardCheckBox = QtWidgets.QCheckBox(self.javaScriptGroup)
        self.jsClipboardCheckBox.setObjectName("jsClipboardCheckBox")
        self.gridLayout.addWidget(self.jsClipboardCheckBox, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.javaScriptGroup)
        self.pluginsGroup = QtWidgets.QGroupBox(self.privacyGroup)
        self.pluginsGroup.setCheckable(True)
        self.pluginsGroup.setChecked(False)
        self.pluginsGroup.setObjectName("pluginsGroup")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pluginsGroup)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.clickToFlashCheckBox = QtWidgets.QCheckBox(self.pluginsGroup)
        self.clickToFlashCheckBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clickToFlashCheckBox.sizePolicy().hasHeightForWidth())
        self.clickToFlashCheckBox.setSizePolicy(sizePolicy)
        self.clickToFlashCheckBox.setObjectName("clickToFlashCheckBox")
        self.gridLayout_7.addWidget(self.clickToFlashCheckBox, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.pluginsGroup)
        self.line = QtWidgets.QFrame(self.privacyGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.doNotTrackCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.doNotTrackCheckBox.setObjectName("doNotTrackCheckBox")
        self.verticalLayout_4.addWidget(self.doNotTrackCheckBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendRefererCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.sendRefererCheckBox.setObjectName("sendRefererCheckBox")
        self.horizontalLayout_4.addWidget(self.sendRefererCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.refererWhitelistButton = QtWidgets.QPushButton(self.privacyGroup)
        self.refererWhitelistButton.setObjectName("refererWhitelistButton")
        self.horizontalLayout_4.addWidget(self.refererWhitelistButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.privacyGroup)
        self.groupBox_6 = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.xssAuditingCheckBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.xssAuditingCheckBox.setObjectName("xssAuditingCheckBox")
        self.verticalLayout_2.addWidget(self.xssAuditingCheckBox)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.expireHistory = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expireHistory.sizePolicy().hasHeightForWidth())
        self.expireHistory.setSizePolicy(sizePolicy)
        self.expireHistory.setObjectName("expireHistory")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.horizontalLayout.addWidget(self.expireHistory)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.cacheGroup = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.cacheGroup.setObjectName("cacheGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cacheGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.diskCacheCheckBox = QtWidgets.QCheckBox(self.cacheGroup)
        self.diskCacheCheckBox.setObjectName("diskCacheCheckBox")
        self.horizontalLayout_5.addWidget(self.diskCacheCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.noCacheHostsButton = QtWidgets.QPushButton(self.cacheGroup)
        self.noCacheHostsButton.setObjectName("noCacheHostsButton")
        self.horizontalLayout_5.addWidget(self.noCacheHostsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.cacheGroup)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cacheKeepButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.cacheKeepButton.setObjectName("cacheKeepButton")
        self.verticalLayout_3.addWidget(self.cacheKeepButton)
        self.cachePreferButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.cachePreferButton.setObjectName("cachePreferButton")
        self.verticalLayout_3.addWidget(self.cachePreferButton)
        self.cacheOfflineButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.cacheOfflineButton.setObjectName("cacheOfflineButton")
        self.verticalLayout_3.addWidget(self.cacheOfflineButton)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.cacheGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.cacheSizeSpinBox = QtWidgets.QSpinBox(self.cacheGroup)
        self.cacheSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cacheSizeSpinBox.setMinimum(1)
        self.cacheSizeSpinBox.setMaximum(999)
        self.cacheSizeSpinBox.setObjectName("cacheSizeSpinBox")
        self.gridLayout_2.addWidget(self.cacheSizeSpinBox, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(410, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.cacheGroup)
        self.groupBox_5 = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.languageCombo = QtWidgets.QComboBox(self.groupBox_5)
        self.languageCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.languageCombo.setObjectName("languageCombo")
        self.horizontalLayout_2.addWidget(self.languageCombo)
        spacerItem4 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.printGroup = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.printGroup.setObjectName("printGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.printGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.printBackgroundsCheckBox = QtWidgets.QCheckBox(self.printGroup)
        self.printBackgroundsCheckBox.setObjectName("printBackgroundsCheckBox")
        self.verticalLayout.addWidget(self.printBackgroundsCheckBox)
        self.verticalLayout_5.addWidget(self.printGroup)
        self.groupBox_3 = QtWidgets.QGroupBox(HelpWebBrowserPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.spatialCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.spatialCheckBox.setObjectName("spatialCheckBox")
        self.gridLayout_6.addWidget(self.spatialCheckBox, 0, 0, 1, 1)
        self.linksInFocusChainCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.linksInFocusChainCheckBox.setObjectName("linksInFocusChainCheckBox")
        self.gridLayout_6.addWidget(self.linksInFocusChainCheckBox, 0, 1, 1, 1)
        self.accessKeysCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.accessKeysCheckBox.setObjectName("accessKeysCheckBox")
        self.gridLayout_6.addWidget(self.accessKeysCheckBox, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(479, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)

        self.retranslateUi(HelpWebBrowserPage)
        QtCore.QMetaObject.connectSlotsByName(HelpWebBrowserPage)
        HelpWebBrowserPage.setTabOrder(self.singleHelpWindowCheckBox, self.webSuggestionsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.webSuggestionsCheckBox, self.saveGeometryCheckBox)
        HelpWebBrowserPage.setTabOrder(self.saveGeometryCheckBox, self.showTabPreviews)
        HelpWebBrowserPage.setTabOrder(self.showTabPreviews, self.quirksCheckBox)
        HelpWebBrowserPage.setTabOrder(self.quirksCheckBox, self.startupCombo)
        HelpWebBrowserPage.setTabOrder(self.startupCombo, self.homePageEdit)
        HelpWebBrowserPage.setTabOrder(self.homePageEdit, self.setCurrentPageButton)
        HelpWebBrowserPage.setTabOrder(self.setCurrentPageButton, self.defaultHomeButton)
        HelpWebBrowserPage.setTabOrder(self.defaultHomeButton, self.defaultSchemeCombo)
        HelpWebBrowserPage.setTabOrder(self.defaultSchemeCombo, self.javaCheckBox)
        HelpWebBrowserPage.setTabOrder(self.javaCheckBox, self.javaScriptGroup)
        HelpWebBrowserPage.setTabOrder(self.javaScriptGroup, self.jsOpenWindowsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.jsOpenWindowsCheckBox, self.jsCloseWindowsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.jsCloseWindowsCheckBox, self.jsClipboardCheckBox)
        HelpWebBrowserPage.setTabOrder(self.jsClipboardCheckBox, self.pluginsGroup)
        HelpWebBrowserPage.setTabOrder(self.pluginsGroup, self.clickToFlashCheckBox)
        HelpWebBrowserPage.setTabOrder(self.clickToFlashCheckBox, self.doNotTrackCheckBox)
        HelpWebBrowserPage.setTabOrder(self.doNotTrackCheckBox, self.sendRefererCheckBox)
        HelpWebBrowserPage.setTabOrder(self.sendRefererCheckBox, self.refererWhitelistButton)
        HelpWebBrowserPage.setTabOrder(self.refererWhitelistButton, self.xssAuditingCheckBox)
        HelpWebBrowserPage.setTabOrder(self.xssAuditingCheckBox, self.expireHistory)
        HelpWebBrowserPage.setTabOrder(self.expireHistory, self.diskCacheCheckBox)
        HelpWebBrowserPage.setTabOrder(self.diskCacheCheckBox, self.noCacheHostsButton)
        HelpWebBrowserPage.setTabOrder(self.noCacheHostsButton, self.cacheKeepButton)
        HelpWebBrowserPage.setTabOrder(self.cacheKeepButton, self.cachePreferButton)
        HelpWebBrowserPage.setTabOrder(self.cachePreferButton, self.cacheOfflineButton)
        HelpWebBrowserPage.setTabOrder(self.cacheOfflineButton, self.cacheSizeSpinBox)
        HelpWebBrowserPage.setTabOrder(self.cacheSizeSpinBox, self.languageCombo)
        HelpWebBrowserPage.setTabOrder(self.languageCombo, self.printBackgroundsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.printBackgroundsCheckBox, self.spatialCheckBox)
        HelpWebBrowserPage.setTabOrder(self.spatialCheckBox, self.linksInFocusChainCheckBox)
        HelpWebBrowserPage.setTabOrder(self.linksInFocusChainCheckBox, self.accessKeysCheckBox)

    def retranslateUi(self, HelpWebBrowserPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("HelpWebBrowserPage", "<b>Configure web browser</b>"))
        self.singleHelpWindowCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to use a single help browser window only"))
        self.singleHelpWindowCheckBox.setText(_translate("HelpWebBrowserPage", "Use single web browser window"))
        self.webSuggestionsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable suggestions for web searches"))
        self.webSuggestionsCheckBox.setText(_translate("HelpWebBrowserPage", "Show suggestions for web searches"))
        self.saveGeometryCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to save the window size and position"))
        self.saveGeometryCheckBox.setText(_translate("HelpWebBrowserPage", "Save size and position upon exit"))
        self.showTabPreviews.setToolTip(_translate("HelpWebBrowserPage", "Select to show a page preview when the mouse hovers over the tab"))
        self.showTabPreviews.setText(_translate("HelpWebBrowserPage", "Show preview when hovering tab"))
        self.quirksCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable the browser\'s workaround for broken sites"))
        self.quirksCheckBox.setText(_translate("HelpWebBrowserPage", "Enable workaround for broken sites"))
        self.startupGroupBox.setTitle(_translate("HelpWebBrowserPage", "Startup"))
        self.label.setText(_translate("HelpWebBrowserPage", "On startup:"))
        self.startupCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the startup behavior"))
        self.startupCombo.setItemText(0, _translate("HelpWebBrowserPage", "Show Home Page"))
        self.startupCombo.setItemText(1, _translate("HelpWebBrowserPage", "Show Speed Dial"))
        self.startupCombo.setItemText(2, _translate("HelpWebBrowserPage", "Show Empty Page"))
        self.homePageLabel.setText(_translate("HelpWebBrowserPage", "Home Page:"))
        self.homePageEdit.setToolTip(_translate("HelpWebBrowserPage", "Enter the desired home page"))
        self.setCurrentPageButton.setToolTip(_translate("HelpWebBrowserPage", "Press to set the current page as the home page"))
        self.setCurrentPageButton.setText(_translate("HelpWebBrowserPage", "Set to current page"))
        self.defaultHomeButton.setToolTip(_translate("HelpWebBrowserPage", "Press to set the default home page"))
        self.defaultHomeButton.setText(_translate("HelpWebBrowserPage", "Set to default home page"))
        self.groupBox_2.setTitle(_translate("HelpWebBrowserPage", "Scheme"))
        self.label_3.setText(_translate("HelpWebBrowserPage", "Default Scheme:"))
        self.defaultSchemeCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the default scheme"))
        self.defaultSchemeCombo.setWhatsThis(_translate("HelpWebBrowserPage", "<b>Default Scheme</b><p>Select the default scheme. This scheme is prepended to URLs, that don\'t contain one.</p>"))
        self.privacyGroup.setTitle(_translate("HelpWebBrowserPage", "Privacy"))
        self.javaCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable Java"))
        self.javaCheckBox.setText(_translate("HelpWebBrowserPage", "Enable Java"))
        self.javaScriptGroup.setToolTip(_translate("HelpWebBrowserPage", "Select to enable JavaScript"))
        self.javaScriptGroup.setTitle(_translate("HelpWebBrowserPage", "Enable JavaScript"))
        self.jsOpenWindowsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to allow JavaScript to open windows"))
        self.jsOpenWindowsCheckBox.setText(_translate("HelpWebBrowserPage", "JavaScript can open windows"))
        self.jsCloseWindowsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to allow JavaScript to close windows"))
        self.jsCloseWindowsCheckBox.setText(_translate("HelpWebBrowserPage", "JavaScript can close windows"))
        self.jsClipboardCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to allow JavaScript to access the clipboard"))
        self.jsClipboardCheckBox.setText(_translate("HelpWebBrowserPage", "JavaScript can access clipboard"))
        self.pluginsGroup.setToolTip(_translate("HelpWebBrowserPage", "Select to enable plugins in web pages"))
        self.pluginsGroup.setTitle(_translate("HelpWebBrowserPage", "Enable Plug-ins"))
        self.clickToFlashCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to activate the Flash blocker"))
        self.clickToFlashCheckBox.setText(_translate("HelpWebBrowserPage", "Use ClickToFlash on Flash plugins"))
        self.doNotTrackCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enabled the \"Do Not Track\" feature"))
        self.doNotTrackCheckBox.setText(_translate("HelpWebBrowserPage", "Tell web sites I do not want to be tracked"))
        self.sendRefererCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to send referer headers to the server"))
        self.sendRefererCheckBox.setText(_translate("HelpWebBrowserPage", "Send Referer header to servers"))
        self.refererWhitelistButton.setToolTip(_translate("HelpWebBrowserPage", "Press to edit the list of whitelisted hosts"))
        self.refererWhitelistButton.setText(_translate("HelpWebBrowserPage", "Edit Referer Whitelist ..."))
        self.groupBox_6.setTitle(_translate("HelpWebBrowserPage", "Security"))
        self.xssAuditingCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable XSS auditing"))
        self.xssAuditingCheckBox.setWhatsThis(_translate("HelpWebBrowserPage", "<b>Enable XSS Auditing</b>\n"
"<p>This selects whether load requests should be monitored for cross-site scripting attempts. Suspicious scripts will be blocked. These will be reported in theWeb Inspector\'s JavaScript console. Enabling this feature might have an impact on performance.</p>"))
        self.xssAuditingCheckBox.setText(_translate("HelpWebBrowserPage", "Enable XSS Auditing"))
        self.groupBox.setTitle(_translate("HelpWebBrowserPage", "History"))
        self.label_4.setText(_translate("HelpWebBrowserPage", "Remove history items:"))
        self.expireHistory.setToolTip(_translate("HelpWebBrowserPage", "Select the period for expiration of history entries"))
        self.expireHistory.setItemText(0, _translate("HelpWebBrowserPage", "After one day"))
        self.expireHistory.setItemText(1, _translate("HelpWebBrowserPage", "After one week"))
        self.expireHistory.setItemText(2, _translate("HelpWebBrowserPage", "After two weeks"))
        self.expireHistory.setItemText(3, _translate("HelpWebBrowserPage", "After one month"))
        self.expireHistory.setItemText(4, _translate("HelpWebBrowserPage", "After one year"))
        self.expireHistory.setItemText(5, _translate("HelpWebBrowserPage", "Manually"))
        self.expireHistory.setItemText(6, _translate("HelpWebBrowserPage", "On application exit"))
        self.cacheGroup.setTitle(_translate("HelpWebBrowserPage", "Browser Cache"))
        self.diskCacheCheckBox.setText(_translate("HelpWebBrowserPage", "Enable disk cache"))
        self.noCacheHostsButton.setToolTip(_translate("HelpWebBrowserPage", "Press to edit the list of hosts exempted from caching"))
        self.noCacheHostsButton.setText(_translate("HelpWebBrowserPage", "Edit Exempted Hosts ..."))
        self.groupBox_4.setTitle(_translate("HelpWebBrowserPage", "Policy"))
        self.cacheKeepButton.setToolTip(_translate("HelpWebBrowserPage", "Select to prefer the network"))
        self.cacheKeepButton.setText(_translate("HelpWebBrowserPage", "Keep cache in sync"))
        self.cachePreferButton.setToolTip(_translate("HelpWebBrowserPage", "Select to prefer cached data"))
        self.cachePreferButton.setText(_translate("HelpWebBrowserPage", "Use cache whenever possible"))
        self.cacheOfflineButton.setToolTip(_translate("HelpWebBrowserPage", "Select to use cached data only"))
        self.cacheOfflineButton.setText(_translate("HelpWebBrowserPage", "Offline browsing mode"))
        self.label_7.setText(_translate("HelpWebBrowserPage", "Cache size:"))
        self.cacheSizeSpinBox.setToolTip(_translate("HelpWebBrowserPage", "Enter the maximum size of the disk cache"))
        self.cacheSizeSpinBox.setSuffix(_translate("HelpWebBrowserPage", " MB"))
        self.groupBox_5.setTitle(_translate("HelpWebBrowserPage", "Web Search"))
        self.label_5.setText(_translate("HelpWebBrowserPage", "Language:"))
        self.languageCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the language to be used for web searches"))
        self.printGroup.setTitle(_translate("HelpWebBrowserPage", "Printing"))
        self.printBackgroundsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to print background colours and images"))
        self.printBackgroundsCheckBox.setText(_translate("HelpWebBrowserPage", "Print background colours and images"))
        self.groupBox_3.setTitle(_translate("HelpWebBrowserPage", "Navigation"))
        self.spatialCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable the spatial navigation feature"))
        self.spatialCheckBox.setWhatsThis(_translate("HelpWebBrowserPage", "<b>Enable Spatial Navigation</b>\n"
"<p>This enables or disables the Spatial Navigation feature, which consists in the ability to navigate between focusable elements in a Web page, such as hyperlinks and form controls, by using Left, Right, Up and Down arrow keys. For example, if a user presses the Right key, heuristics determine whether there is an element he might be trying to reach towards the right and which element he probably wants.</p>"))
        self.spatialCheckBox.setText(_translate("HelpWebBrowserPage", "Enable Spatial Navigation"))
        self.linksInFocusChainCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to include links in focus chain"))
        self.linksInFocusChainCheckBox.setWhatsThis(_translate("HelpWebBrowserPage", "<b>Include Links in Focus Chain</b>\n"
"<p>This selects whether hyperlinks should be included in the keyboard focus chain.</p>"))
        self.linksInFocusChainCheckBox.setText(_translate("HelpWebBrowserPage", "Include Links in Focus Chain"))
        self.accessKeysCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable support for access keys"))
        self.accessKeysCheckBox.setText(_translate("HelpWebBrowserPage", "Enable access keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpWebBrowserPage = QtWidgets.QWidget()
    ui = Ui_HelpWebBrowserPage()
    ui.setupUi(HelpWebBrowserPage)
    HelpWebBrowserPage.show()
    sys.exit(app.exec_())

