# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\HelpDocumentationPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpDocumentationPage(object):
    def setupUi(self, HelpDocumentationPage):
        HelpDocumentationPage.setObjectName("HelpDocumentationPage")
        HelpDocumentationPage.resize(526, 894)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpDocumentationPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(HelpDocumentationPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line17 = QtWidgets.QFrame(HelpDocumentationPage)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setObjectName("line17")
        self.verticalLayout.addWidget(self.line17)
        self.groupBox_9 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ericDocDirPicker = E5PathPicker(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ericDocDirPicker.sizePolicy().hasHeightForWidth())
        self.ericDocDirPicker.setSizePolicy(sizePolicy)
        self.ericDocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ericDocDirPicker.setObjectName("ericDocDirPicker")
        self.verticalLayout_9.addWidget(self.ericDocDirPicker)
        self.textLabel1_8_2_2_6 = QtWidgets.QLabel(self.groupBox_9)
        self.textLabel1_8_2_2_6.setWordWrap(True)
        self.textLabel1_8_2_2_6.setObjectName("textLabel1_8_2_2_6")
        self.verticalLayout_9.addWidget(self.textLabel1_8_2_2_6)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_5 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.python2DocDirPicker = E5PathPicker(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.python2DocDirPicker.sizePolicy().hasHeightForWidth())
        self.python2DocDirPicker.setSizePolicy(sizePolicy)
        self.python2DocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.python2DocDirPicker.setObjectName("python2DocDirPicker")
        self.verticalLayout_2.addWidget(self.python2DocDirPicker)
        self.textLabel1_8_3 = QtWidgets.QLabel(self.groupBox_5)
        self.textLabel1_8_3.setWordWrap(True)
        self.textLabel1_8_3.setObjectName("textLabel1_8_3")
        self.verticalLayout_2.addWidget(self.textLabel1_8_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pythonDocDirPicker = E5PathPicker(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pythonDocDirPicker.sizePolicy().hasHeightForWidth())
        self.pythonDocDirPicker.setSizePolicy(sizePolicy)
        self.pythonDocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pythonDocDirPicker.setObjectName("pythonDocDirPicker")
        self.verticalLayout_3.addWidget(self.pythonDocDirPicker)
        self.textLabel1_8_2 = QtWidgets.QLabel(self.groupBox_4)
        self.textLabel1_8_2.setWordWrap(True)
        self.textLabel1_8_2.setObjectName("textLabel1_8_2")
        self.verticalLayout_3.addWidget(self.textLabel1_8_2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qt4DocDirPicker = E5PathPicker(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt4DocDirPicker.sizePolicy().hasHeightForWidth())
        self.qt4DocDirPicker.setSizePolicy(sizePolicy)
        self.qt4DocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qt4DocDirPicker.setObjectName("qt4DocDirPicker")
        self.verticalLayout_4.addWidget(self.qt4DocDirPicker)
        self.textLabel1_8_2_2_2 = QtWidgets.QLabel(self.groupBox_6)
        self.textLabel1_8_2_2_2.setWordWrap(True)
        self.textLabel1_8_2_2_2.setObjectName("textLabel1_8_2_2_2")
        self.verticalLayout_4.addWidget(self.textLabel1_8_2_2_2)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.qt5DocDirPicker = E5PathPicker(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt5DocDirPicker.sizePolicy().hasHeightForWidth())
        self.qt5DocDirPicker.setSizePolicy(sizePolicy)
        self.qt5DocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qt5DocDirPicker.setObjectName("qt5DocDirPicker")
        self.verticalLayout_5.addWidget(self.qt5DocDirPicker)
        self.textLabel1_8_2_2_4 = QtWidgets.QLabel(self.groupBox_8)
        self.textLabel1_8_2_2_4.setWordWrap(True)
        self.textLabel1_8_2_2_4.setObjectName("textLabel1_8_2_2_4")
        self.verticalLayout_5.addWidget(self.textLabel1_8_2_2_4)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pyqt4DocDirPicker = E5PathPicker(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqt4DocDirPicker.sizePolicy().hasHeightForWidth())
        self.pyqt4DocDirPicker.setSizePolicy(sizePolicy)
        self.pyqt4DocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pyqt4DocDirPicker.setObjectName("pyqt4DocDirPicker")
        self.verticalLayout_6.addWidget(self.pyqt4DocDirPicker)
        self.textLabel1_8_2_2_3 = QtWidgets.QLabel(self.groupBox_7)
        self.textLabel1_8_2_2_3.setWordWrap(True)
        self.textLabel1_8_2_2_3.setObjectName("textLabel1_8_2_2_3")
        self.verticalLayout_6.addWidget(self.textLabel1_8_2_2_3)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.pyqt5Group = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.pyqt5Group.setObjectName("pyqt5Group")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pyqt5Group)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pyqt5DocDirPicker = E5PathPicker(self.pyqt5Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqt5DocDirPicker.sizePolicy().hasHeightForWidth())
        self.pyqt5DocDirPicker.setSizePolicy(sizePolicy)
        self.pyqt5DocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pyqt5DocDirPicker.setObjectName("pyqt5DocDirPicker")
        self.verticalLayout_7.addWidget(self.pyqt5DocDirPicker)
        self.textLabel1_8_2_2_5 = QtWidgets.QLabel(self.pyqt5Group)
        self.textLabel1_8_2_2_5.setWordWrap(True)
        self.textLabel1_8_2_2_5.setObjectName("textLabel1_8_2_2_5")
        self.verticalLayout_7.addWidget(self.textLabel1_8_2_2_5)
        self.verticalLayout.addWidget(self.pyqt5Group)
        self.pysideGroup = QtWidgets.QGroupBox(HelpDocumentationPage)
        self.pysideGroup.setObjectName("pysideGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pysideGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pysideDocDirPicker = E5PathPicker(self.pysideGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pysideDocDirPicker.sizePolicy().hasHeightForWidth())
        self.pysideDocDirPicker.setSizePolicy(sizePolicy)
        self.pysideDocDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pysideDocDirPicker.setObjectName("pysideDocDirPicker")
        self.verticalLayout_8.addWidget(self.pysideDocDirPicker)
        self.textLabel1_8_2_2 = QtWidgets.QLabel(self.pysideGroup)
        self.textLabel1_8_2_2.setWordWrap(True)
        self.textLabel1_8_2_2.setObjectName("textLabel1_8_2_2")
        self.verticalLayout_8.addWidget(self.textLabel1_8_2_2)
        self.verticalLayout.addWidget(self.pysideGroup)
        spacerItem = QtWidgets.QSpacerItem(479, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(HelpDocumentationPage)
        QtCore.QMetaObject.connectSlotsByName(HelpDocumentationPage)
        HelpDocumentationPage.setTabOrder(self.ericDocDirPicker, self.python2DocDirPicker)
        HelpDocumentationPage.setTabOrder(self.python2DocDirPicker, self.pythonDocDirPicker)
        HelpDocumentationPage.setTabOrder(self.pythonDocDirPicker, self.qt4DocDirPicker)
        HelpDocumentationPage.setTabOrder(self.qt4DocDirPicker, self.qt5DocDirPicker)
        HelpDocumentationPage.setTabOrder(self.qt5DocDirPicker, self.pyqt4DocDirPicker)
        HelpDocumentationPage.setTabOrder(self.pyqt4DocDirPicker, self.pyqt5DocDirPicker)
        HelpDocumentationPage.setTabOrder(self.pyqt5DocDirPicker, self.pysideDocDirPicker)

    def retranslateUi(self, HelpDocumentationPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("HelpDocumentationPage", "<b>Configure help documentation</b>"))
        self.groupBox_9.setTitle(_translate("HelpDocumentationPage", "eric API Documentation"))
        self.ericDocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the eric documentation directory"))
        self.textLabel1_8_2_2_6.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the default location."))
        self.groupBox_5.setTitle(_translate("HelpDocumentationPage", "Python 2 Documentation"))
        self.python2DocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the Python 2 documentation directory"))
        self.textLabel1_8_3.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the PYTHON2DOCDIR environment variable, if set."))
        self.groupBox_4.setTitle(_translate("HelpDocumentationPage", "Python 3 Documentation"))
        self.pythonDocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the Python 3 documentation directory"))
        self.textLabel1_8_2.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the PYTHON3DOCDIR environment variable, if set."))
        self.groupBox_6.setTitle(_translate("HelpDocumentationPage", "Qt4 Documentation"))
        self.qt4DocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the Qt4 documentation directory"))
        self.textLabel1_8_2_2_2.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the QT4DOCDIR environment variable, if set."))
        self.groupBox_8.setTitle(_translate("HelpDocumentationPage", "Qt5 Documentation"))
        self.qt5DocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the Qt5 documentation directory"))
        self.textLabel1_8_2_2_4.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the QT5DOCDIR environment variable, if set."))
        self.groupBox_7.setTitle(_translate("HelpDocumentationPage", "PyQt4 Documentation"))
        self.pyqt4DocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the PyQt4 documentation directory"))
        self.textLabel1_8_2_2_3.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the PYQT4DOCDIR environment variable, if set."))
        self.pyqt5Group.setTitle(_translate("HelpDocumentationPage", "PyQt5 Documentation"))
        self.pyqt5DocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the PyQt5 documentation directory"))
        self.textLabel1_8_2_2_5.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the PYQT5DOCDIR environment variable, if set."))
        self.pysideGroup.setTitle(_translate("HelpDocumentationPage", "PySide Documentation"))
        self.pysideDocDirPicker.setToolTip(_translate("HelpDocumentationPage", "Enter the PySide documentation directory"))
        self.textLabel1_8_2_2.setText(_translate("HelpDocumentationPage", "<b>Note</b>: Leave empty to use the PYSIDEDOCDIR environment variable, if set."))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpDocumentationPage = QtWidgets.QWidget()
    ui = Ui_HelpDocumentationPage()
    ui.setupUi(HelpDocumentationPage)
    HelpDocumentationPage.show()
    sys.exit(app.exec_())

