# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\HelpFlashCookieManagerPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpFlashCookieManagerPage(object):
    def setupUi(self, HelpFlashCookieManagerPage):
        HelpFlashCookieManagerPage.setObjectName("HelpFlashCookieManagerPage")
        HelpFlashCookieManagerPage.resize(588, 419)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpFlashCookieManagerPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(HelpFlashCookieManagerPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line9 = QtWidgets.QFrame(HelpFlashCookieManagerPage)
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setObjectName("line9")
        self.verticalLayout.addWidget(self.line9)
        self.groupBox = QtWidgets.QGroupBox(HelpFlashCookieManagerPage)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.flashDataPathPicker = E5PathPicker(self.groupBox)
        self.flashDataPathPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.flashDataPathPicker.setObjectName("flashDataPathPicker")
        self.verticalLayout_2.addWidget(self.flashDataPathPicker)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.groupBox)
        self.autoModeGroup = QtWidgets.QGroupBox(HelpFlashCookieManagerPage)
        self.autoModeGroup.setCheckable(True)
        self.autoModeGroup.setChecked(False)
        self.autoModeGroup.setObjectName("autoModeGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.autoModeGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.autoModeLabel = QtWidgets.QLabel(self.autoModeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoModeLabel.sizePolicy().hasHeightForWidth())
        self.autoModeLabel.setSizePolicy(sizePolicy)
        self.autoModeLabel.setWordWrap(True)
        self.autoModeLabel.setObjectName("autoModeLabel")
        self.horizontalLayout.addWidget(self.autoModeLabel)
        self.verticalLayout.addWidget(self.autoModeGroup)
        self.notificationGroup = QtWidgets.QGroupBox(HelpFlashCookieManagerPage)
        self.notificationGroup.setFlat(False)
        self.notificationGroup.setCheckable(True)
        self.notificationGroup.setChecked(False)
        self.notificationGroup.setObjectName("notificationGroup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.notificationGroup)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.notificationLabel = QtWidgets.QLabel(self.notificationGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationLabel.sizePolicy().hasHeightForWidth())
        self.notificationLabel.setSizePolicy(sizePolicy)
        self.notificationLabel.setWordWrap(True)
        self.notificationLabel.setObjectName("notificationLabel")
        self.horizontalLayout_2.addWidget(self.notificationLabel)
        self.verticalLayout.addWidget(self.notificationGroup)
        self.deleteGroup = QtWidgets.QGroupBox(HelpFlashCookieManagerPage)
        self.deleteGroup.setCheckable(True)
        self.deleteGroup.setChecked(False)
        self.deleteGroup.setObjectName("deleteGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.deleteGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deleteLabel = QtWidgets.QLabel(self.deleteGroup)
        self.deleteLabel.setWordWrap(True)
        self.deleteLabel.setObjectName("deleteLabel")
        self.horizontalLayout_3.addWidget(self.deleteLabel)
        self.verticalLayout.addWidget(self.deleteGroup)
        self.label_19 = QtWidgets.QLabel(HelpFlashCookieManagerPage)
        self.label_19.setWordWrap(True)
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        spacerItem = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(HelpFlashCookieManagerPage)
        QtCore.QMetaObject.connectSlotsByName(HelpFlashCookieManagerPage)
        HelpFlashCookieManagerPage.setTabOrder(self.flashDataPathPicker, self.autoModeGroup)
        HelpFlashCookieManagerPage.setTabOrder(self.autoModeGroup, self.notificationGroup)
        HelpFlashCookieManagerPage.setTabOrder(self.notificationGroup, self.deleteGroup)

    def retranslateUi(self, HelpFlashCookieManagerPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("HelpFlashCookieManagerPage", "<b>Configure Flash Cookies Manager</b>"))
        self.groupBox.setTitle(_translate("HelpFlashCookieManagerPage", "Flash Data Path"))
        self.label.setText(_translate("HelpFlashCookieManagerPage", "<b>Note</b>: You should select the directory that contains #SharedObject as a subfolder."))
        self.autoModeGroup.setToolTip(_translate("HelpFlashCookieManagerPage", "Select to activate auto mode"))
        self.autoModeGroup.setTitle(_translate("HelpFlashCookieManagerPage", "Auto Mode Enabled"))
        self.autoModeLabel.setText(_translate("HelpFlashCookieManagerPage", "The flash data directory will be checked regularly and flash cookies in the blacklist will be deleted automatically."))
        self.notificationGroup.setToolTip(_translate("HelpFlashCookieManagerPage", "Select to show a notification upon detection of new flash cookies"))
        self.notificationGroup.setTitle(_translate("HelpFlashCookieManagerPage", "Notifications enabled"))
        self.notificationLabel.setText(_translate("HelpFlashCookieManagerPage", "User will be notified for every new flash cookie that is not in blacklist and whitelist."))
        self.deleteGroup.setToolTip(_translate("HelpFlashCookieManagerPage", "Select to delete all flash cookies on startup and shutdown"))
        self.deleteGroup.setTitle(_translate("HelpFlashCookieManagerPage", "Delete"))
        self.deleteLabel.setText(_translate("HelpFlashCookieManagerPage", "Delete all flash cookies on exit/start (except those are in whitelist)"))
        self.label_19.setText(_translate("HelpFlashCookieManagerPage", "<p><b>Note:</b> These settings are just applied to flash cookies.</p>"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpFlashCookieManagerPage = QtWidgets.QWidget()
    ui = Ui_HelpFlashCookieManagerPage()
    ui.setupUi(HelpFlashCookieManagerPage)
    HelpFlashCookieManagerPage.show()
    sys.exit(app.exec_())

