# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\InterfacePage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterfacePage(object):
    def setupUi(self, InterfacePage):
        InterfacePage.setObjectName("InterfacePage")
        InterfacePage.resize(557, 1121)
        self.verticalLayout = QtWidgets.QVBoxLayout(InterfacePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(InterfacePage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line9 = QtWidgets.QFrame(InterfacePage)
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9.setObjectName("line9")
        self.verticalLayout.addWidget(self.line9)
        self.groupBox_4 = QtWidgets.QGroupBox(InterfacePage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uiBrowsersListFoldersFirstCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.uiBrowsersListFoldersFirstCheckBox.setObjectName("uiBrowsersListFoldersFirstCheckBox")
        self.gridLayout_2.addWidget(self.uiBrowsersListFoldersFirstCheckBox, 0, 0, 1, 1)
        self.uiBrowsersHideNonPublicCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.uiBrowsersHideNonPublicCheckBox.setObjectName("uiBrowsersHideNonPublicCheckBox")
        self.gridLayout_2.addWidget(self.uiBrowsersHideNonPublicCheckBox, 0, 1, 1, 1)
        self.uiBrowsersSortByOccurrenceCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.uiBrowsersSortByOccurrenceCheckBox.setObjectName("uiBrowsersSortByOccurrenceCheckBox")
        self.gridLayout_2.addWidget(self.uiBrowsersSortByOccurrenceCheckBox, 1, 0, 1, 1)
        self.uiBrowsersShowHiddenCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.uiBrowsersShowHiddenCheckBox.setObjectName("uiBrowsersShowHiddenCheckBox")
        self.gridLayout_2.addWidget(self.uiBrowsersShowHiddenCheckBox, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.fileFiltersEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.fileFiltersEdit.setObjectName("fileFiltersEdit")
        self.horizontalLayout_2.addWidget(self.fileFiltersEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.uiCaptionShowsFilenameGroupBox = QtWidgets.QGroupBox(InterfacePage)
        self.uiCaptionShowsFilenameGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.uiCaptionShowsFilenameGroupBox.setCheckable(True)
        self.uiCaptionShowsFilenameGroupBox.setObjectName("uiCaptionShowsFilenameGroupBox")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.uiCaptionShowsFilenameGroupBox)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(self.uiCaptionShowsFilenameGroupBox)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.filenameLengthSpinBox = QtWidgets.QSpinBox(self.uiCaptionShowsFilenameGroupBox)
        self.filenameLengthSpinBox.setMinimum(10)
        self.filenameLengthSpinBox.setMaximum(999)
        self.filenameLengthSpinBox.setSingleStep(10)
        self.filenameLengthSpinBox.setProperty("value", 100)
        self.filenameLengthSpinBox.setObjectName("filenameLengthSpinBox")
        self.hboxlayout.addWidget(self.filenameLengthSpinBox)
        spacerItem = QtWidgets.QSpacerItem(31, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.uiCaptionShowsFilenameGroupBox)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(InterfacePage)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.styleComboBox = QtWidgets.QComboBox(InterfacePage)
        self.styleComboBox.setObjectName("styleComboBox")
        self.gridLayout_3.addWidget(self.styleComboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(InterfacePage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.styleSheetPicker = E5PathPicker(InterfacePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleSheetPicker.sizePolicy().hasHeightForWidth())
        self.styleSheetPicker.setSizePolicy(sizePolicy)
        self.styleSheetPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.styleSheetPicker.setObjectName("styleSheetPicker")
        self.gridLayout_3.addWidget(self.styleSheetPicker, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.groupBox = QtWidgets.QGroupBox(InterfacePage)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName("gridlayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tlTopButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.tlTopButton.setObjectName("tlTopButton")
        self.vboxlayout.addWidget(self.tlTopButton)
        self.tlLeftButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.tlLeftButton.setObjectName("tlLeftButton")
        self.vboxlayout.addWidget(self.tlLeftButton)
        self.gridlayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.trTopButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.trTopButton.setObjectName("trTopButton")
        self.vboxlayout1.addWidget(self.trTopButton)
        self.trRightButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.trRightButton.setObjectName("trRightButton")
        self.vboxlayout1.addWidget(self.trRightButton)
        self.gridlayout.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.blBottomButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.blBottomButton.setObjectName("blBottomButton")
        self.vboxlayout2.addWidget(self.blBottomButton)
        self.blLeftButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.blLeftButton.setObjectName("blLeftButton")
        self.vboxlayout2.addWidget(self.blLeftButton)
        self.gridlayout.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.brTopButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.brTopButton.setObjectName("brTopButton")
        self.vboxlayout3.addWidget(self.brTopButton)
        self.brRightButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.brRightButton.setObjectName("brRightButton")
        self.vboxlayout3.addWidget(self.brRightButton)
        self.gridlayout.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(InterfacePage)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.delaySpinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.delaySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.delaySpinBox.setMaximum(2000)
        self.delaySpinBox.setSingleStep(100)
        self.delaySpinBox.setProperty("value", 200)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.horizontalLayout_3.addWidget(self.delaySpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.line9_2 = QtWidgets.QFrame(InterfacePage)
        self.line9_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_2.setObjectName("line9_2")
        self.verticalLayout.addWidget(self.line9_2)
        self.TextLabel1_2_2_2 = QtWidgets.QLabel(InterfacePage)
        self.TextLabel1_2_2_2.setObjectName("TextLabel1_2_2_2")
        self.verticalLayout.addWidget(self.TextLabel1_2_2_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.languageLabel = QtWidgets.QLabel(InterfacePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageLabel.sizePolicy().hasHeightForWidth())
        self.languageLabel.setSizePolicy(sizePolicy)
        self.languageLabel.setObjectName("languageLabel")
        self.gridLayout.addWidget(self.languageLabel, 0, 0, 1, 1)
        self.languageComboBox = QtWidgets.QComboBox(InterfacePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageComboBox.sizePolicy().hasHeightForWidth())
        self.languageComboBox.setSizePolicy(sizePolicy)
        self.languageComboBox.setObjectName("languageComboBox")
        self.gridLayout.addWidget(self.languageComboBox, 0, 1, 1, 1)
        self.layoutLabel = QtWidgets.QLabel(InterfacePage)
        self.layoutLabel.setObjectName("layoutLabel")
        self.gridLayout.addWidget(self.layoutLabel, 1, 0, 1, 1)
        self.layoutComboBox = QtWidgets.QComboBox(InterfacePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutComboBox.sizePolicy().hasHeightForWidth())
        self.layoutComboBox.setSizePolicy(sizePolicy)
        self.layoutComboBox.setObjectName("layoutComboBox")
        self.layoutComboBox.addItem("")
        self.layoutComboBox.addItem("")
        self.gridLayout.addWidget(self.layoutComboBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(InterfacePage)
        self.groupBox_9.setObjectName("groupBox_9")
        self._8 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self._8.setObjectName("_8")
        self.separateShellButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.separateShellButton.setObjectName("separateShellButton")
        self._8.addWidget(self.separateShellButton)
        self.debugEmbeddedShellButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.debugEmbeddedShellButton.setObjectName("debugEmbeddedShellButton")
        self._8.addWidget(self.debugEmbeddedShellButton)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(InterfacePage)
        self.groupBox_10.setObjectName("groupBox_10")
        self._9 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self._9.setObjectName("_9")
        self.separateFileBrowserButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.separateFileBrowserButton.setObjectName("separateFileBrowserButton")
        self._9.addWidget(self.separateFileBrowserButton)
        self.debugEmbeddedFileBrowserButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.debugEmbeddedFileBrowserButton.setObjectName("debugEmbeddedFileBrowserButton")
        self._9.addWidget(self.debugEmbeddedFileBrowserButton)
        self.projectEmbeddedFileBrowserButton = QtWidgets.QRadioButton(self.groupBox_10)
        self.projectEmbeddedFileBrowserButton.setObjectName("projectEmbeddedFileBrowserButton")
        self._9.addWidget(self.projectEmbeddedFileBrowserButton)
        self.horizontalLayout.addWidget(self.groupBox_10)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabsGroupBox = QtWidgets.QGroupBox(InterfacePage)
        self.tabsGroupBox.setObjectName("tabsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabsCloseButtonCheckBox = QtWidgets.QCheckBox(self.tabsGroupBox)
        self.tabsCloseButtonCheckBox.setObjectName("tabsCloseButtonCheckBox")
        self.verticalLayout_2.addWidget(self.tabsCloseButtonCheckBox)
        self.verticalLayout.addWidget(self.tabsGroupBox)
        spacerItem2 = QtWidgets.QSpacerItem(537, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.resetLayoutButton = QtWidgets.QPushButton(InterfacePage)
        self.resetLayoutButton.setObjectName("resetLayoutButton")
        self.verticalLayout.addWidget(self.resetLayoutButton)
        self.languageLabel.setBuddy(self.languageComboBox)

        self.retranslateUi(InterfacePage)
        QtCore.QMetaObject.connectSlotsByName(InterfacePage)
        InterfacePage.setTabOrder(self.uiBrowsersListFoldersFirstCheckBox, self.uiBrowsersHideNonPublicCheckBox)
        InterfacePage.setTabOrder(self.uiBrowsersHideNonPublicCheckBox, self.uiBrowsersSortByOccurrenceCheckBox)
        InterfacePage.setTabOrder(self.uiBrowsersSortByOccurrenceCheckBox, self.uiBrowsersShowHiddenCheckBox)
        InterfacePage.setTabOrder(self.uiBrowsersShowHiddenCheckBox, self.fileFiltersEdit)
        InterfacePage.setTabOrder(self.fileFiltersEdit, self.uiCaptionShowsFilenameGroupBox)
        InterfacePage.setTabOrder(self.uiCaptionShowsFilenameGroupBox, self.filenameLengthSpinBox)
        InterfacePage.setTabOrder(self.filenameLengthSpinBox, self.styleComboBox)
        InterfacePage.setTabOrder(self.styleComboBox, self.styleSheetPicker)
        InterfacePage.setTabOrder(self.styleSheetPicker, self.tlTopButton)
        InterfacePage.setTabOrder(self.tlTopButton, self.tlLeftButton)
        InterfacePage.setTabOrder(self.tlLeftButton, self.trTopButton)
        InterfacePage.setTabOrder(self.trTopButton, self.trRightButton)
        InterfacePage.setTabOrder(self.trRightButton, self.blBottomButton)
        InterfacePage.setTabOrder(self.blBottomButton, self.blLeftButton)
        InterfacePage.setTabOrder(self.blLeftButton, self.brTopButton)
        InterfacePage.setTabOrder(self.brTopButton, self.brRightButton)
        InterfacePage.setTabOrder(self.brRightButton, self.delaySpinBox)
        InterfacePage.setTabOrder(self.delaySpinBox, self.languageComboBox)
        InterfacePage.setTabOrder(self.languageComboBox, self.layoutComboBox)
        InterfacePage.setTabOrder(self.layoutComboBox, self.separateShellButton)
        InterfacePage.setTabOrder(self.separateShellButton, self.debugEmbeddedShellButton)
        InterfacePage.setTabOrder(self.debugEmbeddedShellButton, self.separateFileBrowserButton)
        InterfacePage.setTabOrder(self.separateFileBrowserButton, self.debugEmbeddedFileBrowserButton)
        InterfacePage.setTabOrder(self.debugEmbeddedFileBrowserButton, self.projectEmbeddedFileBrowserButton)
        InterfacePage.setTabOrder(self.projectEmbeddedFileBrowserButton, self.tabsCloseButtonCheckBox)
        InterfacePage.setTabOrder(self.tabsCloseButtonCheckBox, self.resetLayoutButton)

    def retranslateUi(self, InterfacePage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("InterfacePage", "<b>Configure User Interface</b>"))
        self.groupBox_4.setTitle(_translate("InterfacePage", "Browsers"))
        self.uiBrowsersListFoldersFirstCheckBox.setToolTip(_translate("InterfacePage", "Select, if folders should be listed first in the various browsers"))
        self.uiBrowsersListFoldersFirstCheckBox.setText(_translate("InterfacePage", "List folders first in Browsers"))
        self.uiBrowsersHideNonPublicCheckBox.setToolTip(_translate("InterfacePage", "Select to hide non public classes, methods and attributes in the browsers."))
        self.uiBrowsersHideNonPublicCheckBox.setText(_translate("InterfacePage", "Hide non public members in Browsers"))
        self.uiBrowsersSortByOccurrenceCheckBox.setToolTip(_translate("InterfacePage", "Select to sort file contents by occurrence"))
        self.uiBrowsersSortByOccurrenceCheckBox.setText(_translate("InterfacePage", "Sort contents by occurrence"))
        self.uiBrowsersShowHiddenCheckBox.setToolTip(_translate("InterfacePage", "Select to show hidden files in the various browsers"))
        self.uiBrowsersShowHiddenCheckBox.setText(_translate("InterfacePage", "Show hidden files"))
        self.label_4.setText(_translate("InterfacePage", "Filter out files:"))
        self.fileFiltersEdit.setToolTip(_translate("InterfacePage", "Enter wildcard file patterns separated by semicolon. Files matching these patterns will not be shown by the file browsers."))
        self.uiCaptionShowsFilenameGroupBox.setToolTip(_translate("InterfacePage", "Select, if the caption of the main window should show the filename of the current editor"))
        self.uiCaptionShowsFilenameGroupBox.setTitle(_translate("InterfacePage", "Caption shows filename"))
        self.label.setText(_translate("InterfacePage", "Filename Length"))
        self.filenameLengthSpinBox.setToolTip(_translate("InterfacePage", "Enter the number of characters to be shown in the main window title."))
        self.label_2.setText(_translate("InterfacePage", "Style:"))
        self.styleComboBox.setToolTip(_translate("InterfacePage", "Select the interface style"))
        self.label_3.setText(_translate("InterfacePage", "Style Sheet:"))
        self.styleSheetPicker.setToolTip(_translate("InterfacePage", "Enter the path of the style sheet file"))
        self.groupBox.setTitle(_translate("InterfacePage", "Dockarea Corner Usage"))
        self.groupBox_2.setTitle(_translate("InterfacePage", "Top Left Corner"))
        self.tlTopButton.setToolTip(_translate("InterfacePage", "Select to assign the top left corner to the top dockarea"))
        self.tlTopButton.setText(_translate("InterfacePage", "Top dockarea"))
        self.tlLeftButton.setToolTip(_translate("InterfacePage", "Select to assign the top left corner to the left dockarea"))
        self.tlLeftButton.setText(_translate("InterfacePage", "Left dockarea"))
        self.groupBox_5.setTitle(_translate("InterfacePage", "Top Right Corner"))
        self.trTopButton.setToolTip(_translate("InterfacePage", "Select to assign the top right corner to the top dockarea"))
        self.trTopButton.setText(_translate("InterfacePage", "Top dockarea"))
        self.trRightButton.setToolTip(_translate("InterfacePage", "Select to assign the top right corner to the right dockarea"))
        self.trRightButton.setText(_translate("InterfacePage", "Right dockarea"))
        self.groupBox_6.setTitle(_translate("InterfacePage", "Bottom Left Corner"))
        self.blBottomButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom left corner to the bottom dockarea"))
        self.blBottomButton.setText(_translate("InterfacePage", "Bottom dockarea"))
        self.blLeftButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom left corner to the left dockarea"))
        self.blLeftButton.setText(_translate("InterfacePage", "Left dockarea"))
        self.groupBox_7.setTitle(_translate("InterfacePage", "Bottom Right Corner"))
        self.brTopButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom right corner to the bottom dockarea"))
        self.brTopButton.setText(_translate("InterfacePage", "Bottom dockarea"))
        self.brRightButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom right corner to the right dockarea"))
        self.brRightButton.setText(_translate("InterfacePage", "Right dockarea"))
        self.groupBox_8.setTitle(_translate("InterfacePage", "Sidebars"))
        self.label_5.setText(_translate("InterfacePage", "Delay:"))
        self.delaySpinBox.setSuffix(_translate("InterfacePage", " ms"))
        self.TextLabel1_2_2_2.setText(_translate("InterfacePage", "<font color=\"#FF0000\"><b>Note:</b> All settings below are activated at the next startup of the application.</font>"))
        self.languageLabel.setText(_translate("InterfacePage", "Language:"))
        self.languageComboBox.setToolTip(_translate("InterfacePage", "Select the interface language."))
        self.languageComboBox.setWhatsThis(_translate("InterfacePage", "The interface language can be selected from this list. If \"system\" is selected, the interface language is determined by the system. The selection of \"none\" means, that the default language will be used."))
        self.layoutLabel.setText(_translate("InterfacePage", "Layout:"))
        self.layoutComboBox.setToolTip(_translate("InterfacePage", "Select the layout type."))
        self.layoutComboBox.setItemText(0, _translate("InterfacePage", "Sidebars"))
        self.layoutComboBox.setItemText(1, _translate("InterfacePage", "Toolboxes"))
        self.groupBox_9.setTitle(_translate("InterfacePage", "Shell"))
        self.separateShellButton.setToolTip(_translate("InterfacePage", "Select to get a separate shell window"))
        self.separateShellButton.setText(_translate("InterfacePage", "separate window"))
        self.debugEmbeddedShellButton.setToolTip(_translate("InterfacePage", "Select to embed the shell in the Debug-Viewer"))
        self.debugEmbeddedShellButton.setText(_translate("InterfacePage", "embed in Debug-Viewer"))
        self.groupBox_10.setTitle(_translate("InterfacePage", "File-Browser"))
        self.separateFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to get a separate file browser window"))
        self.separateFileBrowserButton.setText(_translate("InterfacePage", "separate window"))
        self.debugEmbeddedFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to embed the file browser in the Debug-Viewer"))
        self.debugEmbeddedFileBrowserButton.setText(_translate("InterfacePage", "embed in Debug-Viewer"))
        self.projectEmbeddedFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to embed the file browser in the Project-Viewer"))
        self.projectEmbeddedFileBrowserButton.setText(_translate("InterfacePage", "embed in Project-Viewer"))
        self.tabsGroupBox.setTitle(_translate("InterfacePage", "Tabs"))
        self.tabsCloseButtonCheckBox.setText(_translate("InterfacePage", "Show only one close button instead of one for each tab"))
        self.resetLayoutButton.setText(_translate("InterfacePage", "Reset layout to factory defaults"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InterfacePage = QtWidgets.QWidget()
    ui = Ui_InterfacePage()
    ui.setupUi(InterfacePage)
    InterfacePage.show()
    sys.exit(app.exec_())

