# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\ProjectBrowserPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjectBrowserPage(object):
    def setupUi(self, ProjectBrowserPage):
        ProjectBrowserPage.setObjectName("ProjectBrowserPage")
        ProjectBrowserPage.resize(617, 497)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectBrowserPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(ProjectBrowserPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line8 = QtWidgets.QFrame(ProjectBrowserPage)
        self.line8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line8.setObjectName("line8")
        self.verticalLayout.addWidget(self.line8)
        self.groupBox = QtWidgets.QGroupBox(ProjectBrowserPage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pbHighlightedButton = QtWidgets.QPushButton(self.groupBox)
        self.pbHighlightedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbHighlightedButton.setText("")
        self.pbHighlightedButton.setObjectName("pbHighlightedButton")
        self.horizontalLayout.addWidget(self.pbHighlightedButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.pbGroup = QtWidgets.QGroupBox(ProjectBrowserPage)
        self.pbGroup.setObjectName("pbGroup")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.pbGroup)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_6 = QtWidgets.QLabel(self.pbGroup)
        self.label_6.setObjectName("label_6")
        self.hboxlayout.addWidget(self.label_6)
        self.projectTypeCombo = QtWidgets.QComboBox(self.pbGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectTypeCombo.sizePolicy().hasHeightForWidth())
        self.projectTypeCombo.setSizePolicy(sizePolicy)
        self.projectTypeCombo.setObjectName("projectTypeCombo")
        self.hboxlayout.addWidget(self.projectTypeCombo)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.sourcesBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.sourcesBrowserCheckBox.setObjectName("sourcesBrowserCheckBox")
        self.gridlayout.addWidget(self.sourcesBrowserCheckBox, 0, 0, 1, 1)
        self.translationsBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.translationsBrowserCheckBox.setObjectName("translationsBrowserCheckBox")
        self.gridlayout.addWidget(self.translationsBrowserCheckBox, 0, 1, 1, 1)
        self.formsBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.formsBrowserCheckBox.setObjectName("formsBrowserCheckBox")
        self.gridlayout.addWidget(self.formsBrowserCheckBox, 1, 0, 1, 1)
        self.interfacesBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.interfacesBrowserCheckBox.setObjectName("interfacesBrowserCheckBox")
        self.gridlayout.addWidget(self.interfacesBrowserCheckBox, 1, 1, 1, 1)
        self.resourcesBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.resourcesBrowserCheckBox.setObjectName("resourcesBrowserCheckBox")
        self.gridlayout.addWidget(self.resourcesBrowserCheckBox, 2, 0, 1, 1)
        self.othersBrowserCheckBox = QtWidgets.QCheckBox(self.pbGroup)
        self.othersBrowserCheckBox.setObjectName("othersBrowserCheckBox")
        self.gridlayout.addWidget(self.othersBrowserCheckBox, 2, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.verticalLayout.addWidget(self.pbGroup)
        self.followEditorCheckBox = QtWidgets.QCheckBox(ProjectBrowserPage)
        self.followEditorCheckBox.setObjectName("followEditorCheckBox")
        self.verticalLayout.addWidget(self.followEditorCheckBox)
        self.followCursorLineCheckBox = QtWidgets.QCheckBox(ProjectBrowserPage)
        self.followCursorLineCheckBox.setObjectName("followCursorLineCheckBox")
        self.verticalLayout.addWidget(self.followCursorLineCheckBox)
        self.autoPopulateCheckBox = QtWidgets.QCheckBox(ProjectBrowserPage)
        self.autoPopulateCheckBox.setObjectName("autoPopulateCheckBox")
        self.verticalLayout.addWidget(self.autoPopulateCheckBox)
        self.hideGeneratedCheckBox = QtWidgets.QCheckBox(ProjectBrowserPage)
        self.hideGeneratedCheckBox.setObjectName("hideGeneratedCheckBox")
        self.verticalLayout.addWidget(self.hideGeneratedCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(599, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ProjectBrowserPage)
        QtCore.QMetaObject.connectSlotsByName(ProjectBrowserPage)
        ProjectBrowserPage.setTabOrder(self.pbHighlightedButton, self.projectTypeCombo)
        ProjectBrowserPage.setTabOrder(self.projectTypeCombo, self.sourcesBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.sourcesBrowserCheckBox, self.formsBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.formsBrowserCheckBox, self.resourcesBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.resourcesBrowserCheckBox, self.translationsBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.translationsBrowserCheckBox, self.interfacesBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.interfacesBrowserCheckBox, self.othersBrowserCheckBox)
        ProjectBrowserPage.setTabOrder(self.othersBrowserCheckBox, self.followEditorCheckBox)
        ProjectBrowserPage.setTabOrder(self.followEditorCheckBox, self.followCursorLineCheckBox)
        ProjectBrowserPage.setTabOrder(self.followCursorLineCheckBox, self.autoPopulateCheckBox)
        ProjectBrowserPage.setTabOrder(self.autoPopulateCheckBox, self.hideGeneratedCheckBox)

    def retranslateUi(self, ProjectBrowserPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("ProjectBrowserPage", "<b>Configure project viewer settings</b>"))
        self.groupBox.setTitle(_translate("ProjectBrowserPage", "Colours"))
        self.label.setText(_translate("ProjectBrowserPage", "Highlighted entries (Others):"))
        self.pbHighlightedButton.setToolTip(_translate("ProjectBrowserPage", "Select the colour for highlighted entries in the Others viewer."))
        self.pbGroup.setTitle(_translate("ProjectBrowserPage", "Visible Project Browsers"))
        self.label_6.setText(_translate("ProjectBrowserPage", "Projecttype:"))
        self.projectTypeCombo.setToolTip(_translate("ProjectBrowserPage", "Select the project type to be configured"))
        self.sourcesBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the sources browser"))
        self.sourcesBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Sources Browser"))
        self.translationsBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the translations browser"))
        self.translationsBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Translations Browser"))
        self.formsBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the forms browser"))
        self.formsBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Forms Browser"))
        self.interfacesBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the interfaces (IDL) browser"))
        self.interfacesBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Interfaces (IDL) Browser"))
        self.resourcesBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the resources browser"))
        self.resourcesBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Resources Browser"))
        self.othersBrowserCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to show the browser for other files"))
        self.othersBrowserCheckBox.setText(_translate("ProjectBrowserPage", "Others Browser"))
        self.followEditorCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to make the project browsers highlight the file of the current editor."))
        self.followEditorCheckBox.setText(_translate("ProjectBrowserPage", "Highlight file of current editor"))
        self.followCursorLineCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to follow the cursor line of the current editor"))
        self.followCursorLineCheckBox.setText(_translate("ProjectBrowserPage", "Follow cursor line of current editor"))
        self.autoPopulateCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to populate entries automatically when following the cursor line of the current editor"))
        self.autoPopulateCheckBox.setText(_translate("ProjectBrowserPage", "Populate entry when following the cursor line"))
        self.hideGeneratedCheckBox.setToolTip(_translate("ProjectBrowserPage", "Select to hide sources generated from form files"))
        self.hideGeneratedCheckBox.setText(_translate("ProjectBrowserPage", "Hide generated form sources"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectBrowserPage = QtWidgets.QWidget()
    ui = Ui_ProjectBrowserPage()
    ui.setupUi(ProjectBrowserPage)
    ProjectBrowserPage.show()
    sys.exit(app.exec_())

