# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\QtPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QtPage(object):
    def setupUi(self, QtPage):
        QtPage.setObjectName("QtPage")
        QtPage.resize(642, 614)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(QtPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerLabel = QtWidgets.QLabel(QtPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line12 = QtWidgets.QFrame(QtPage)
        self.line12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line12.setObjectName("line12")
        self.verticalLayout_3.addWidget(self.line12)
        self.groupBox_3 = QtWidgets.QGroupBox(QtPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextLabel1_2_2_5 = QtWidgets.QLabel(self.groupBox_3)
        self.TextLabel1_2_2_5.setObjectName("TextLabel1_2_2_5")
        self.verticalLayout.addWidget(self.TextLabel1_2_2_5)
        self.qt4TransPicker = E5PathPicker(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt4TransPicker.sizePolicy().hasHeightForWidth())
        self.qt4TransPicker.setSizePolicy(sizePolicy)
        self.qt4TransPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qt4TransPicker.setObjectName("qt4TransPicker")
        self.verticalLayout.addWidget(self.qt4TransPicker)
        self.textLabel1_2_4 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel1_2_4.setWordWrap(True)
        self.textLabel1_2_4.setObjectName("textLabel1_2_4")
        self.verticalLayout.addWidget(self.textLabel1_2_4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(QtPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.qtToolsDirPicker = E5PathPicker(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qtToolsDirPicker.sizePolicy().hasHeightForWidth())
        self.qtToolsDirPicker.setSizePolicy(sizePolicy)
        self.qtToolsDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.qtToolsDirPicker.setObjectName("qtToolsDirPicker")
        self.horizontalLayout.addWidget(self.qtToolsDirPicker)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.qt4PrefixEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.qt4PrefixEdit.setObjectName("qt4PrefixEdit")
        self.horizontalLayout_2.addWidget(self.qt4PrefixEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.qt4PostfixEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.qt4PostfixEdit.setObjectName("qt4PostfixEdit")
        self.horizontalLayout_2.addWidget(self.qt4PostfixEdit)
        self.qt4SampleLabel = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qt4SampleLabel.sizePolicy().hasHeightForWidth())
        self.qt4SampleLabel.setSizePolicy(sizePolicy)
        self.qt4SampleLabel.setObjectName("qt4SampleLabel")
        self.horizontalLayout_2.addWidget(self.qt4SampleLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(QtPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pyqtToolsDirPicker = E5PathPicker(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pyqtToolsDirPicker.sizePolicy().hasHeightForWidth())
        self.pyqtToolsDirPicker.setSizePolicy(sizePolicy)
        self.pyqtToolsDirPicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pyqtToolsDirPicker.setObjectName("pyqtToolsDirPicker")
        self.horizontalLayout_3.addWidget(self.pyqtToolsDirPicker)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(QtPage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pyuicIndentSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.pyuicIndentSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pyuicIndentSpinBox.setMinimum(2)
        self.pyuicIndentSpinBox.setMaximum(16)
        self.pyuicIndentSpinBox.setProperty("value", 4)
        self.pyuicIndentSpinBox.setObjectName("pyuicIndentSpinBox")
        self.gridLayout.addWidget(self.pyuicIndentSpinBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(448, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pyuicImportsCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.pyuicImportsCheckBox.setObjectName("pyuicImportsCheckBox")
        self.gridLayout.addWidget(self.pyuicImportsCheckBox, 1, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(496, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(QtPage)
        QtCore.QMetaObject.connectSlotsByName(QtPage)
        QtPage.setTabOrder(self.qt4TransPicker, self.qtToolsDirPicker)
        QtPage.setTabOrder(self.qtToolsDirPicker, self.qt4PrefixEdit)
        QtPage.setTabOrder(self.qt4PrefixEdit, self.qt4PostfixEdit)
        QtPage.setTabOrder(self.qt4PostfixEdit, self.pyqtToolsDirPicker)
        QtPage.setTabOrder(self.pyqtToolsDirPicker, self.pyuicIndentSpinBox)
        QtPage.setTabOrder(self.pyuicIndentSpinBox, self.pyuicImportsCheckBox)

    def retranslateUi(self, QtPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("QtPage", "<b>Configure Qt</b>"))
        self.groupBox_3.setTitle(_translate("QtPage", "Qt Translations Directory"))
        self.TextLabel1_2_2_5.setText(_translate("QtPage", "<font color=\"#FF0000\"><b>Note:</b> This setting is activated at the next startup of the application.</font>"))
        self.qt4TransPicker.setToolTip(_translate("QtPage", "Enter the path of the Qt translations directory."))
        self.textLabel1_2_4.setText(_translate("QtPage", "<b>Note:</b> Leave this entry empty to use an environment variable or the path compiled into the Qt library. Environment variables supported are\n"
"<ul>\n"
"<li>QT4TRANSLATIONSDIR for Qt4</li>\n"
"<li>QT5TRANSLATIONSDIR for Qt5</li>\n"
"<li>QTTRANSLATIONSDIR for any Qt variant</li>\n"
"</ul>"))
        self.groupBox_4.setTitle(_translate("QtPage", "Qt Tools"))
        self.label_4.setText(_translate("QtPage", "Tools Directory:"))
        self.qtToolsDirPicker.setToolTip(_translate("QtPage", "Enter the path of the Qt tools directory, if they are not found."))
        self.label.setText(_translate("QtPage", "The tool executable is composed of the prefix, the tool name and the postfix. For win, the extension is added automatically."))
        self.label_3.setText(_translate("QtPage", "Qt-Prefix:"))
        self.qt4PrefixEdit.setToolTip(_translate("QtPage", "Enter the prefix for the Qt tools name"))
        self.label_5.setText(_translate("QtPage", "Qt-Postfix:"))
        self.qt4PostfixEdit.setToolTip(_translate("QtPage", "Enter the postfix for the Qt tools name"))
        self.qt4SampleLabel.setToolTip(_translate("QtPage", "This gives an example of the complete tool name"))
        self.qt4SampleLabel.setText(_translate("QtPage", "designer"))
        self.groupBox_2.setTitle(_translate("QtPage", "PyQt Tools"))
        self.label_6.setText(_translate("QtPage", "Tools Directory:"))
        self.pyqtToolsDirPicker.setToolTip(_translate("QtPage", "Enter the path of the PyQt tools directory, if they are not found."))
        self.groupBox.setTitle(_translate("QtPage", "pyuic / pyside-uic Options"))
        self.label_2.setText(_translate("QtPage", "Indent Width:"))
        self.pyuicIndentSpinBox.setToolTip(_translate("QtPage", "Select the indent width (default: 4)"))
        self.pyuicImportsCheckBox.setText(_translate("QtPage", "Generate imports relative to \'.\'"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtPage = QtWidgets.QWidget()
    ui = Ui_QtPage()
    ui.setupUi(QtPage)
    QtPage.show()
    sys.exit(app.exec_())

