# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\TasksPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TasksPage(object):
    def setupUi(self, TasksPage):
        TasksPage.setObjectName("TasksPage")
        TasksPage.resize(586, 475)
        self.verticalLayout = QtWidgets.QVBoxLayout(TasksPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(TasksPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line11_2_2_2 = QtWidgets.QFrame(TasksPage)
        self.line11_2_2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line11_2_2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line11_2_2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line11_2_2_2.setObjectName("line11_2_2_2")
        self.verticalLayout.addWidget(self.line11_2_2_2)
        self.groupBox = QtWidgets.QGroupBox(TasksPage)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.textLabel5_3 = QtWidgets.QLabel(self.groupBox)
        self.textLabel5_3.setObjectName("textLabel5_3")
        self.gridLayout.addWidget(self.textLabel5_3, 0, 0, 1, 1)
        self.tasksMarkerFixmeEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tasksMarkerFixmeEdit.setText("")
        self.tasksMarkerFixmeEdit.setObjectName("tasksMarkerFixmeEdit")
        self.gridLayout.addWidget(self.tasksMarkerFixmeEdit, 0, 1, 1, 1)
        self.textLabel4_4 = QtWidgets.QLabel(self.groupBox)
        self.textLabel4_4.setObjectName("textLabel4_4")
        self.gridLayout.addWidget(self.textLabel4_4, 1, 0, 1, 1)
        self.tasksMarkerWarningEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tasksMarkerWarningEdit.setObjectName("tasksMarkerWarningEdit")
        self.gridLayout.addWidget(self.tasksMarkerWarningEdit, 1, 1, 1, 1)
        self.textLabel4_3 = QtWidgets.QLabel(self.groupBox)
        self.textLabel4_3.setObjectName("textLabel4_3")
        self.gridLayout.addWidget(self.textLabel4_3, 2, 0, 1, 1)
        self.tasksMarkerTodoEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tasksMarkerTodoEdit.setObjectName("tasksMarkerTodoEdit")
        self.gridLayout.addWidget(self.tasksMarkerTodoEdit, 2, 1, 1, 1)
        self.textLabel4_5 = QtWidgets.QLabel(self.groupBox)
        self.textLabel4_5.setObjectName("textLabel4_5")
        self.gridLayout.addWidget(self.textLabel4_5, 3, 0, 1, 1)
        self.tasksMarkerNoteEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tasksMarkerNoteEdit.setObjectName("tasksMarkerNoteEdit")
        self.gridLayout.addWidget(self.tasksMarkerNoteEdit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(TasksPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textLabel2_8 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel2_8.setObjectName("textLabel2_8")
        self.gridLayout_2.addWidget(self.textLabel2_8, 0, 0, 1, 1)
        self.tasksFixmeColourButton = QtWidgets.QPushButton(self.groupBox_2)
        self.tasksFixmeColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.tasksFixmeColourButton.setText("")
        self.tasksFixmeColourButton.setObjectName("tasksFixmeColourButton")
        self.gridLayout_2.addWidget(self.tasksFixmeColourButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.textLabel6_3 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel6_3.setObjectName("textLabel6_3")
        self.gridLayout_2.addWidget(self.textLabel6_3, 1, 0, 1, 1)
        self.tasksWarningColourButton = QtWidgets.QPushButton(self.groupBox_2)
        self.tasksWarningColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.tasksWarningColourButton.setText("")
        self.tasksWarningColourButton.setObjectName("tasksWarningColourButton")
        self.gridLayout_2.addWidget(self.tasksWarningColourButton, 1, 1, 1, 1)
        self.textLabel1_3 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.gridLayout_2.addWidget(self.textLabel1_3, 2, 0, 1, 1)
        self.tasksTodoColourButton = QtWidgets.QPushButton(self.groupBox_2)
        self.tasksTodoColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.tasksTodoColourButton.setText("")
        self.tasksTodoColourButton.setObjectName("tasksTodoColourButton")
        self.gridLayout_2.addWidget(self.tasksTodoColourButton, 2, 1, 1, 1)
        self.textLabel3_4 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel3_4.setObjectName("textLabel3_4")
        self.gridLayout_2.addWidget(self.textLabel3_4, 3, 0, 1, 1)
        self.tasksNoteColourButton = QtWidgets.QPushButton(self.groupBox_2)
        self.tasksNoteColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.tasksNoteColourButton.setText("")
        self.tasksNoteColourButton.setObjectName("tasksNoteColourButton")
        self.gridLayout_2.addWidget(self.tasksNoteColourButton, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(TasksPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.clearCheckBox.setObjectName("clearCheckBox")
        self.horizontalLayout.addWidget(self.clearCheckBox)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(TasksPage)
        QtCore.QMetaObject.connectSlotsByName(TasksPage)
        TasksPage.setTabOrder(self.tasksMarkerFixmeEdit, self.tasksMarkerWarningEdit)
        TasksPage.setTabOrder(self.tasksMarkerWarningEdit, self.tasksMarkerTodoEdit)
        TasksPage.setTabOrder(self.tasksMarkerTodoEdit, self.tasksMarkerNoteEdit)
        TasksPage.setTabOrder(self.tasksMarkerNoteEdit, self.tasksFixmeColourButton)
        TasksPage.setTabOrder(self.tasksFixmeColourButton, self.tasksWarningColourButton)
        TasksPage.setTabOrder(self.tasksWarningColourButton, self.tasksTodoColourButton)
        TasksPage.setTabOrder(self.tasksTodoColourButton, self.tasksNoteColourButton)
        TasksPage.setTabOrder(self.tasksNoteColourButton, self.clearCheckBox)

    def retranslateUi(self, TasksPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("TasksPage", "<b>Configure Tasks</b>"))
        self.groupBox.setTitle(_translate("TasksPage", "Tasks Markers"))
        self.textLabel5_3.setText(_translate("TasksPage", "Bugfix tasks:"))
        self.tasksMarkerFixmeEdit.setToolTip(_translate("TasksPage", "Enter the tasks markers separated by a space character."))
        self.textLabel4_4.setText(_translate("TasksPage", "Warning tasks:"))
        self.tasksMarkerWarningEdit.setToolTip(_translate("TasksPage", "Enter the tasks markers separated by a space character."))
        self.textLabel4_3.setText(_translate("TasksPage", "Todo tasks:"))
        self.tasksMarkerTodoEdit.setToolTip(_translate("TasksPage", "Enter the tasks markers separated by a space character."))
        self.textLabel4_5.setText(_translate("TasksPage", "Note tasks:"))
        self.tasksMarkerNoteEdit.setToolTip(_translate("TasksPage", "Enter the tasks markers separated by a space character."))
        self.groupBox_2.setTitle(_translate("TasksPage", "Tasks Background Colours"))
        self.textLabel2_8.setText(_translate("TasksPage", "Bugfix tasks:"))
        self.tasksFixmeColourButton.setToolTip(_translate("TasksPage", "Select the background colour for these tasks."))
        self.textLabel6_3.setText(_translate("TasksPage", "Warning tasks:"))
        self.tasksWarningColourButton.setToolTip(_translate("TasksPage", "Select the background colour for these tasks."))
        self.textLabel1_3.setText(_translate("TasksPage", "Todo tasks:"))
        self.tasksTodoColourButton.setToolTip(_translate("TasksPage", "Select the background colour for these tasks."))
        self.textLabel3_4.setText(_translate("TasksPage", "Note tasks:"))
        self.tasksNoteColourButton.setToolTip(_translate("TasksPage", "Select the background colour for these tasks."))
        self.groupBox_3.setTitle(_translate("TasksPage", "Tasks Handling"))
        self.clearCheckBox.setToolTip(_translate("TasksPage", "Select to clear global file tasks when the file is closed"))
        self.clearCheckBox.setText(_translate("TasksPage", "Clear global file task when file is closed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TasksPage = QtWidgets.QWidget()
    ui = Ui_TasksPage()
    ui.setupUi(TasksPage)
    TasksPage.show()
    sys.exit(app.exec_())

