# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\VcsPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VcsPage(object):
    def setupUi(self, VcsPage):
        VcsPage.setObjectName("VcsPage")
        VcsPage.resize(619, 572)
        self.verticalLayout = QtWidgets.QVBoxLayout(VcsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(VcsPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line9_3_2_2 = QtWidgets.QFrame(VcsPage)
        self.line9_3_2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_3_2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line9_3_2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line9_3_2_2.setObjectName("line9_3_2_2")
        self.verticalLayout.addWidget(self.line9_3_2_2)
        self.vcsAutoCloseCheckBox = QtWidgets.QCheckBox(VcsPage)
        self.vcsAutoCloseCheckBox.setObjectName("vcsAutoCloseCheckBox")
        self.verticalLayout.addWidget(self.vcsAutoCloseCheckBox)
        self.groupBox = QtWidgets.QGroupBox(VcsPage)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vcsAutoSaveCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.vcsAutoSaveCheckBox.setObjectName("vcsAutoSaveCheckBox")
        self.vboxlayout.addWidget(self.vcsAutoSaveCheckBox)
        self.vcsAutoSaveProjectCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.vcsAutoSaveProjectCheckBox.setObjectName("vcsAutoSaveProjectCheckBox")
        self.vboxlayout.addWidget(self.vcsAutoSaveProjectCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(VcsPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vcsStatusMonitorIntervalSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.vcsStatusMonitorIntervalSpinBox.setMaximum(3600)
        self.vcsStatusMonitorIntervalSpinBox.setObjectName("vcsStatusMonitorIntervalSpinBox")
        self.gridLayout_2.addWidget(self.vcsStatusMonitorIntervalSpinBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.vcsMonitorLocalStatusCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.vcsMonitorLocalStatusCheckBox.setObjectName("vcsMonitorLocalStatusCheckBox")
        self.gridLayout_2.addWidget(self.vcsMonitorLocalStatusCheckBox, 1, 0, 1, 2)
        self.autoUpdateCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.autoUpdateCheckBox.setObjectName("autoUpdateCheckBox")
        self.gridLayout_2.addWidget(self.autoUpdateCheckBox, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(VcsPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.pbVcsAddedButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsAddedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsAddedButton.setText("")
        self.pbVcsAddedButton.setObjectName("pbVcsAddedButton")
        self.gridLayout.addWidget(self.pbVcsAddedButton, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.pbVcsConflictButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsConflictButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsConflictButton.setText("")
        self.pbVcsConflictButton.setObjectName("pbVcsConflictButton")
        self.gridLayout.addWidget(self.pbVcsConflictButton, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pbVcsModifiedButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsModifiedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsModifiedButton.setText("")
        self.pbVcsModifiedButton.setObjectName("pbVcsModifiedButton")
        self.gridLayout.addWidget(self.pbVcsModifiedButton, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.pbVcsReplacedButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsReplacedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsReplacedButton.setText("")
        self.pbVcsReplacedButton.setObjectName("pbVcsReplacedButton")
        self.gridLayout.addWidget(self.pbVcsReplacedButton, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pbVcsUpdateButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsUpdateButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsUpdateButton.setText("")
        self.pbVcsUpdateButton.setObjectName("pbVcsUpdateButton")
        self.gridLayout.addWidget(self.pbVcsUpdateButton, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.pbVcsRemovedButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pbVcsRemovedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsRemovedButton.setText("")
        self.pbVcsRemovedButton.setObjectName("pbVcsRemovedButton")
        self.gridLayout.addWidget(self.pbVcsRemovedButton, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(512, 81, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(VcsPage)
        QtCore.QMetaObject.connectSlotsByName(VcsPage)
        VcsPage.setTabOrder(self.vcsAutoCloseCheckBox, self.vcsAutoSaveCheckBox)
        VcsPage.setTabOrder(self.vcsAutoSaveCheckBox, self.vcsAutoSaveProjectCheckBox)
        VcsPage.setTabOrder(self.vcsAutoSaveProjectCheckBox, self.vcsStatusMonitorIntervalSpinBox)
        VcsPage.setTabOrder(self.vcsStatusMonitorIntervalSpinBox, self.vcsMonitorLocalStatusCheckBox)
        VcsPage.setTabOrder(self.vcsMonitorLocalStatusCheckBox, self.autoUpdateCheckBox)
        VcsPage.setTabOrder(self.autoUpdateCheckBox, self.pbVcsAddedButton)
        VcsPage.setTabOrder(self.pbVcsAddedButton, self.pbVcsModifiedButton)
        VcsPage.setTabOrder(self.pbVcsModifiedButton, self.pbVcsUpdateButton)
        VcsPage.setTabOrder(self.pbVcsUpdateButton, self.pbVcsConflictButton)
        VcsPage.setTabOrder(self.pbVcsConflictButton, self.pbVcsReplacedButton)

    def retranslateUi(self, VcsPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("VcsPage", "<b>Configure Version Control Systems</b>"))
        self.vcsAutoCloseCheckBox.setText(_translate("VcsPage", "Close VCS dialog automatically, if no error occured"))
        self.groupBox.setTitle(_translate("VcsPage", "Commit"))
        self.vcsAutoSaveCheckBox.setToolTip(_translate("VcsPage", "Select, if files should be saved before a commit"))
        self.vcsAutoSaveCheckBox.setText(_translate("VcsPage", "Save files upon commit"))
        self.vcsAutoSaveProjectCheckBox.setToolTip(_translate("VcsPage", "Select, if project should be saved before a commit"))
        self.vcsAutoSaveProjectCheckBox.setText(_translate("VcsPage", "Save project upon commit"))
        self.groupBox_2.setTitle(_translate("VcsPage", "Status Monitor"))
        self.vcsStatusMonitorIntervalSpinBox.setToolTip(_translate("VcsPage", "Select the interval in seconds for VCS status updates (0 to disable)"))
        self.vcsStatusMonitorIntervalSpinBox.setSuffix(_translate("VcsPage", " sec"))
        self.vcsMonitorLocalStatusCheckBox.setToolTip(_translate("VcsPage", "Select to monitor local status only (if supported by VCS)"))
        self.vcsMonitorLocalStatusCheckBox.setText(_translate("VcsPage", "Monitor local status only"))
        self.autoUpdateCheckBox.setToolTip(_translate("VcsPage", "Select to enable automatic updates"))
        self.autoUpdateCheckBox.setText(_translate("VcsPage", "Automatic updates enabled"))
        self.groupBox_3.setTitle(_translate("VcsPage", "Colours"))
        self.label_4.setText(_translate("VcsPage", "VCS status \"added\":"))
        self.pbVcsAddedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"added\"."))
        self.label_5.setText(_translate("VcsPage", "VCS status \"conflict\":"))
        self.pbVcsConflictButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"conflict\"."))
        self.label_2.setText(_translate("VcsPage", "VCS status \"modified\":"))
        self.pbVcsModifiedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"modified\"."))
        self.label_6.setText(_translate("VcsPage", "VCS status \"replaced\":"))
        self.pbVcsReplacedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"replaced\"."))
        self.label_3.setText(_translate("VcsPage", "VCS status \"needs update\":"))
        self.pbVcsUpdateButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"needs update\"."))
        self.label_7.setText(_translate("VcsPage", "VCS status \"removed\":"))
        self.pbVcsRemovedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"removed\"."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VcsPage = QtWidgets.QWidget()
    ui = Ui_VcsPage()
    ui.setupUi(VcsPage)
    VcsPage.show()
    sys.exit(app.exec_())

