# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Preferences\ConfigurationPages\WebBrowserPage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WebBrowserPage(object):
    def setupUi(self, WebBrowserPage):
        WebBrowserPage.setObjectName("WebBrowserPage")
        WebBrowserPage.resize(616, 1610)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WebBrowserPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerLabel = QtWidgets.QLabel(WebBrowserPage)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout_2.addWidget(self.headerLabel)
        self.line17 = QtWidgets.QFrame(WebBrowserPage)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setObjectName("line17")
        self.verticalLayout_2.addWidget(self.line17)
        self.groupBox_4 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.singleHelpWindowCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.singleHelpWindowCheckBox.setObjectName("singleHelpWindowCheckBox")
        self.gridLayout_5.addWidget(self.singleHelpWindowCheckBox, 0, 0, 1, 1)
        self.webSuggestionsCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.webSuggestionsCheckBox.setObjectName("webSuggestionsCheckBox")
        self.gridLayout_5.addWidget(self.webSuggestionsCheckBox, 0, 1, 1, 1)
        self.saveGeometryCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.saveGeometryCheckBox.setObjectName("saveGeometryCheckBox")
        self.gridLayout_5.addWidget(self.saveGeometryCheckBox, 1, 0, 1, 1)
        self.showTabPreviews = QtWidgets.QCheckBox(self.groupBox_4)
        self.showTabPreviews.setObjectName("showTabPreviews")
        self.gridLayout_5.addWidget(self.showTabPreviews, 1, 1, 1, 1)
        self.errorPageCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.errorPageCheckBox.setObjectName("errorPageCheckBox")
        self.gridLayout_5.addWidget(self.errorPageCheckBox, 2, 0, 1, 1)
        self.scrollingCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.scrollingCheckBox.setObjectName("scrollingCheckBox")
        self.gridLayout_5.addWidget(self.scrollingCheckBox, 2, 1, 1, 1)
        self.fullscreenCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.fullscreenCheckBox.setObjectName("fullscreenCheckBox")
        self.gridLayout_5.addWidget(self.fullscreenCheckBox, 3, 0, 1, 1)
        self.screenCaptureCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.screenCaptureCheckBox.setObjectName("screenCaptureCheckBox")
        self.gridLayout_5.addWidget(self.screenCaptureCheckBox, 3, 1, 1, 1)
        self.webGLCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.webGLCheckBox.setObjectName("webGLCheckBox")
        self.gridLayout_5.addWidget(self.webGLCheckBox, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.startupGroupBox = QtWidgets.QGroupBox(WebBrowserPage)
        self.startupGroupBox.setObjectName("startupGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.startupGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.startupGroupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.startupCombo = QtWidgets.QComboBox(self.startupGroupBox)
        self.startupCombo.setObjectName("startupCombo")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.startupCombo.addItem("")
        self.gridLayout_3.addWidget(self.startupCombo, 0, 1, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.startupGroupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.newTabCombo = QtWidgets.QComboBox(self.startupGroupBox)
        self.newTabCombo.setObjectName("newTabCombo")
        self.newTabCombo.addItem("")
        self.newTabCombo.addItem("")
        self.newTabCombo.addItem("")
        self.gridLayout_3.addWidget(self.newTabCombo, 1, 1, 1, 3)
        self.homePageLabel = QtWidgets.QLabel(self.startupGroupBox)
        self.homePageLabel.setObjectName("homePageLabel")
        self.gridLayout_3.addWidget(self.homePageLabel, 2, 0, 1, 1)
        self.homePageEdit = QtWidgets.QLineEdit(self.startupGroupBox)
        self.homePageEdit.setObjectName("homePageEdit")
        self.gridLayout_3.addWidget(self.homePageEdit, 2, 1, 1, 3)
        self.setCurrentPageButton = QtWidgets.QPushButton(self.startupGroupBox)
        self.setCurrentPageButton.setObjectName("setCurrentPageButton")
        self.gridLayout_3.addWidget(self.setCurrentPageButton, 3, 1, 1, 1)
        self.defaultHomeButton = QtWidgets.QPushButton(self.startupGroupBox)
        self.defaultHomeButton.setObjectName("defaultHomeButton")
        self.gridLayout_3.addWidget(self.defaultHomeButton, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 3, 1, 1)
        self.loadTabOnActivationCheckBox = QtWidgets.QCheckBox(self.startupGroupBox)
        self.loadTabOnActivationCheckBox.setObjectName("loadTabOnActivationCheckBox")
        self.gridLayout_3.addWidget(self.loadTabOnActivationCheckBox, 4, 0, 1, 4)
        self.label.raise_()
        self.startupCombo.raise_()
        self.homePageLabel.raise_()
        self.homePageEdit.raise_()
        self.setCurrentPageButton.raise_()
        self.defaultHomeButton.raise_()
        self.label_12.raise_()
        self.newTabCombo.raise_()
        self.loadTabOnActivationCheckBox.raise_()
        self.verticalLayout_2.addWidget(self.startupGroupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.saveSessionCheckBox = QtWidgets.QCheckBox(self.groupBox_8)
        self.saveSessionCheckBox.setObjectName("saveSessionCheckBox")
        self.gridLayout_6.addWidget(self.saveSessionCheckBox, 0, 0, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.sessionTimerSpinBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.sessionTimerSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sessionTimerSpinBox.setMinimum(10)
        self.sessionTimerSpinBox.setMaximum(180)
        self.sessionTimerSpinBox.setSingleStep(1)
        self.sessionTimerSpinBox.setObjectName("sessionTimerSpinBox")
        self.gridLayout_6.addWidget(self.sessionTimerSpinBox, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(443, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_2 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.defaultSchemeCombo = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultSchemeCombo.sizePolicy().hasHeightForWidth())
        self.defaultSchemeCombo.setSizePolicy(sizePolicy)
        self.defaultSchemeCombo.setEditable(False)
        self.defaultSchemeCombo.setObjectName("defaultSchemeCombo")
        self.gridLayout_4.addWidget(self.defaultSchemeCombo, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.privacyGroup = QtWidgets.QGroupBox(WebBrowserPage)
        self.privacyGroup.setObjectName("privacyGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.privacyGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.javaScriptGroup = QtWidgets.QGroupBox(self.privacyGroup)
        self.javaScriptGroup.setToolTip("")
        self.javaScriptGroup.setObjectName("javaScriptGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.javaScriptGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.jsOpenWindowsCheckBox = QtWidgets.QCheckBox(self.javaScriptGroup)
        self.jsOpenWindowsCheckBox.setObjectName("jsOpenWindowsCheckBox")
        self.verticalLayout_5.addWidget(self.jsOpenWindowsCheckBox)
        self.jsClipboardCheckBox = QtWidgets.QCheckBox(self.javaScriptGroup)
        self.jsClipboardCheckBox.setObjectName("jsClipboardCheckBox")
        self.verticalLayout_5.addWidget(self.jsClipboardCheckBox)
        self.verticalLayout_4.addWidget(self.javaScriptGroup)
        self.pluginsCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.pluginsCheckBox.setObjectName("pluginsCheckBox")
        self.verticalLayout_4.addWidget(self.pluginsCheckBox)
        self.line = QtWidgets.QFrame(self.privacyGroup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.doNotTrackCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.doNotTrackCheckBox.setObjectName("doNotTrackCheckBox")
        self.verticalLayout_4.addWidget(self.doNotTrackCheckBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendRefererCheckBox = QtWidgets.QCheckBox(self.privacyGroup)
        self.sendRefererCheckBox.setObjectName("sendRefererCheckBox")
        self.horizontalLayout_4.addWidget(self.sendRefererCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.refererWhitelistButton = QtWidgets.QPushButton(self.privacyGroup)
        self.refererWhitelistButton.setObjectName("refererWhitelistButton")
        self.horizontalLayout_4.addWidget(self.refererWhitelistButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.privacyGroup)
        self.groupBox_6 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.xssAuditingCheckBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.xssAuditingCheckBox.setObjectName("xssAuditingCheckBox")
        self.horizontalLayout_7.addWidget(self.xssAuditingCheckBox)
        self.insecureContentsCheckBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.insecureContentsCheckBox.setObjectName("insecureContentsCheckBox")
        self.horizontalLayout_7.addWidget(self.insecureContentsCheckBox)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.expireHistory = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expireHistory.sizePolicy().hasHeightForWidth())
        self.expireHistory.setSizePolicy(sizePolicy)
        self.expireHistory.setObjectName("expireHistory")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.expireHistory.addItem("")
        self.horizontalLayout.addWidget(self.expireHistory)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.cacheGroup = QtWidgets.QGroupBox(WebBrowserPage)
        self.cacheGroup.setObjectName("cacheGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cacheGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.diskCacheCheckBox = QtWidgets.QCheckBox(self.cacheGroup)
        self.diskCacheCheckBox.setObjectName("diskCacheCheckBox")
        self.gridLayout_2.addWidget(self.diskCacheCheckBox, 0, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.cacheGroup)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.cacheSizeSpinBox = QtWidgets.QSpinBox(self.cacheGroup)
        self.cacheSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cacheSizeSpinBox.setMinimum(1)
        self.cacheSizeSpinBox.setMaximum(999)
        self.cacheSizeSpinBox.setObjectName("cacheSizeSpinBox")
        self.gridLayout_2.addWidget(self.cacheSizeSpinBox, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(410, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.cacheGroup)
        self.groupBox_5 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.languageCombo = QtWidgets.QComboBox(self.groupBox_5)
        self.languageCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.languageCombo.setObjectName("languageCombo")
        self.horizontalLayout_2.addWidget(self.languageCombo)
        spacerItem4 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.imageSearchGroup = QtWidgets.QGroupBox(WebBrowserPage)
        self.imageSearchGroup.setObjectName("imageSearchGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imageSearchGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.imageSearchGroup)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.imageSearchComboBox = QtWidgets.QComboBox(self.imageSearchGroup)
        self.imageSearchComboBox.setObjectName("imageSearchComboBox")
        self.horizontalLayout_3.addWidget(self.imageSearchComboBox)
        spacerItem5 = QtWidgets.QSpacerItem(383, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.imageSearchGroup)
        self.groupBox_3 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.spatialCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.spatialCheckBox.setObjectName("spatialCheckBox")
        self.gridLayout.addWidget(self.spatialCheckBox, 0, 0, 1, 1)
        self.linksInFocusChainCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.linksInFocusChainCheckBox.setObjectName("linksInFocusChainCheckBox")
        self.gridLayout.addWidget(self.linksInFocusChainCheckBox, 0, 1, 1, 1)
        self.focusOnNavigationCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.focusOnNavigationCheckBox.setObjectName("focusOnNavigationCheckBox")
        self.gridLayout.addWidget(self.focusOnNavigationCheckBox, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_7 = QtWidgets.QGroupBox(WebBrowserPage)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.printBackgroundCheckBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.printBackgroundCheckBox.setObjectName("printBackgroundCheckBox")
        self.horizontalLayout_6.addWidget(self.printBackgroundCheckBox)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.autoScrollGroupBox = QtWidgets.QGroupBox(WebBrowserPage)
        self.autoScrollGroupBox.setCheckable(True)
        self.autoScrollGroupBox.setObjectName("autoScrollGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.autoScrollGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.autoScrollGroupBox)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.autoScrollGroupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.autoScrollDividerSpinBox = QtWidgets.QDoubleSpinBox(self.autoScrollGroupBox)
        self.autoScrollDividerSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoScrollDividerSpinBox.setDecimals(1)
        self.autoScrollDividerSpinBox.setMinimum(1.0)
        self.autoScrollDividerSpinBox.setMaximum(99.9)
        self.autoScrollDividerSpinBox.setObjectName("autoScrollDividerSpinBox")
        self.horizontalLayout_5.addWidget(self.autoScrollDividerSpinBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_10 = QtWidgets.QLabel(self.autoScrollGroupBox)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.verticalLayout_2.addWidget(self.autoScrollGroupBox)
        self.webInspectorGroup = QtWidgets.QGroupBox(WebBrowserPage)
        self.webInspectorGroup.setCheckable(True)
        self.webInspectorGroup.setChecked(False)
        self.webInspectorGroup.setObjectName("webInspectorGroup")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.webInspectorGroup)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.webInspectorGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.webInspectorPortSpinBox = QtWidgets.QSpinBox(self.webInspectorGroup)
        self.webInspectorPortSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.webInspectorPortSpinBox.setMinimum(1025)
        self.webInspectorPortSpinBox.setMaximum(65535)
        self.webInspectorPortSpinBox.setObjectName("webInspectorPortSpinBox")
        self.gridLayout_8.addWidget(self.webInspectorPortSpinBox, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(372, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.webInspectorGroup)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 1, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.webInspectorGroup)
        spacerItem8 = QtWidgets.QSpacerItem(479, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)

        self.retranslateUi(WebBrowserPage)
        QtCore.QMetaObject.connectSlotsByName(WebBrowserPage)
        WebBrowserPage.setTabOrder(self.singleHelpWindowCheckBox, self.webSuggestionsCheckBox)
        WebBrowserPage.setTabOrder(self.webSuggestionsCheckBox, self.saveGeometryCheckBox)
        WebBrowserPage.setTabOrder(self.saveGeometryCheckBox, self.showTabPreviews)
        WebBrowserPage.setTabOrder(self.showTabPreviews, self.errorPageCheckBox)
        WebBrowserPage.setTabOrder(self.errorPageCheckBox, self.scrollingCheckBox)
        WebBrowserPage.setTabOrder(self.scrollingCheckBox, self.fullscreenCheckBox)
        WebBrowserPage.setTabOrder(self.fullscreenCheckBox, self.screenCaptureCheckBox)
        WebBrowserPage.setTabOrder(self.screenCaptureCheckBox, self.webGLCheckBox)
        WebBrowserPage.setTabOrder(self.webGLCheckBox, self.startupCombo)
        WebBrowserPage.setTabOrder(self.startupCombo, self.newTabCombo)
        WebBrowserPage.setTabOrder(self.newTabCombo, self.homePageEdit)
        WebBrowserPage.setTabOrder(self.homePageEdit, self.setCurrentPageButton)
        WebBrowserPage.setTabOrder(self.setCurrentPageButton, self.defaultHomeButton)
        WebBrowserPage.setTabOrder(self.defaultHomeButton, self.loadTabOnActivationCheckBox)
        WebBrowserPage.setTabOrder(self.loadTabOnActivationCheckBox, self.saveSessionCheckBox)
        WebBrowserPage.setTabOrder(self.saveSessionCheckBox, self.sessionTimerSpinBox)
        WebBrowserPage.setTabOrder(self.sessionTimerSpinBox, self.defaultSchemeCombo)
        WebBrowserPage.setTabOrder(self.defaultSchemeCombo, self.jsOpenWindowsCheckBox)
        WebBrowserPage.setTabOrder(self.jsOpenWindowsCheckBox, self.jsClipboardCheckBox)
        WebBrowserPage.setTabOrder(self.jsClipboardCheckBox, self.pluginsCheckBox)
        WebBrowserPage.setTabOrder(self.pluginsCheckBox, self.doNotTrackCheckBox)
        WebBrowserPage.setTabOrder(self.doNotTrackCheckBox, self.sendRefererCheckBox)
        WebBrowserPage.setTabOrder(self.sendRefererCheckBox, self.refererWhitelistButton)
        WebBrowserPage.setTabOrder(self.refererWhitelistButton, self.xssAuditingCheckBox)
        WebBrowserPage.setTabOrder(self.xssAuditingCheckBox, self.insecureContentsCheckBox)
        WebBrowserPage.setTabOrder(self.insecureContentsCheckBox, self.expireHistory)
        WebBrowserPage.setTabOrder(self.expireHistory, self.diskCacheCheckBox)
        WebBrowserPage.setTabOrder(self.diskCacheCheckBox, self.cacheSizeSpinBox)
        WebBrowserPage.setTabOrder(self.cacheSizeSpinBox, self.languageCombo)
        WebBrowserPage.setTabOrder(self.languageCombo, self.imageSearchComboBox)
        WebBrowserPage.setTabOrder(self.imageSearchComboBox, self.spatialCheckBox)
        WebBrowserPage.setTabOrder(self.spatialCheckBox, self.linksInFocusChainCheckBox)
        WebBrowserPage.setTabOrder(self.linksInFocusChainCheckBox, self.focusOnNavigationCheckBox)
        WebBrowserPage.setTabOrder(self.focusOnNavigationCheckBox, self.printBackgroundCheckBox)
        WebBrowserPage.setTabOrder(self.printBackgroundCheckBox, self.autoScrollGroupBox)
        WebBrowserPage.setTabOrder(self.autoScrollGroupBox, self.autoScrollDividerSpinBox)
        WebBrowserPage.setTabOrder(self.autoScrollDividerSpinBox, self.webInspectorGroup)
        WebBrowserPage.setTabOrder(self.webInspectorGroup, self.webInspectorPortSpinBox)

    def retranslateUi(self, WebBrowserPage):
        _translate = QtCore.QCoreApplication.translate
        self.headerLabel.setText(_translate("WebBrowserPage", "<b>Configure Web Browser</b>"))
        self.groupBox_4.setTitle(_translate("WebBrowserPage", "General"))
        self.singleHelpWindowCheckBox.setToolTip(_translate("WebBrowserPage", "Select to use a single web browser window only"))
        self.singleHelpWindowCheckBox.setText(_translate("WebBrowserPage", "Use single web browser window"))
        self.webSuggestionsCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable suggestions for web searches"))
        self.webSuggestionsCheckBox.setText(_translate("WebBrowserPage", "Show suggestions for web searches"))
        self.saveGeometryCheckBox.setToolTip(_translate("WebBrowserPage", "Select to save the window size and position"))
        self.saveGeometryCheckBox.setText(_translate("WebBrowserPage", "Save size and position upon exit"))
        self.showTabPreviews.setToolTip(_translate("WebBrowserPage", "Select to show a page preview when the mouse hovers over the tab"))
        self.showTabPreviews.setText(_translate("WebBrowserPage", "Show preview when hovering tab"))
        self.errorPageCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable displaying the built-in Chromium error pages."))
        self.errorPageCheckBox.setText(_translate("WebBrowserPage", "Use built-in Chromium error page"))
        self.scrollingCheckBox.setToolTip(_translate("WebBrowserPage", "Select to activate animated scrolling"))
        self.scrollingCheckBox.setText(_translate("WebBrowserPage", "Enable animated scrolling"))
        self.fullscreenCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable fullscreen support"))
        self.fullscreenCheckBox.setText(_translate("WebBrowserPage", "Enable Fullscreen Support"))
        self.screenCaptureCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable screen capture support"))
        self.screenCaptureCheckBox.setText(_translate("WebBrowserPage", "Enable Screen Capture Support"))
        self.webGLCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable support for WebGL"))
        self.webGLCheckBox.setText(_translate("WebBrowserPage", "Enable WebGL support"))
        self.startupGroupBox.setTitle(_translate("WebBrowserPage", "Startup"))
        self.label.setText(_translate("WebBrowserPage", "On startup:"))
        self.startupCombo.setToolTip(_translate("WebBrowserPage", "Select the startup behavior"))
        self.startupCombo.setItemText(0, _translate("WebBrowserPage", "Show Empty Page"))
        self.startupCombo.setItemText(1, _translate("WebBrowserPage", "Show Home Page"))
        self.startupCombo.setItemText(2, _translate("WebBrowserPage", "Show Speed Dial"))
        self.startupCombo.setItemText(3, _translate("WebBrowserPage", "Restore Session"))
        self.startupCombo.setItemText(4, _translate("WebBrowserPage", "Select Session"))
        self.label_12.setText(_translate("WebBrowserPage", "On new tab:"))
        self.newTabCombo.setToolTip(_translate("WebBrowserPage", "Select the behavior of new tabs"))
        self.newTabCombo.setItemText(0, _translate("WebBrowserPage", "Show Empty Page"))
        self.newTabCombo.setItemText(1, _translate("WebBrowserPage", "Show Home Page"))
        self.newTabCombo.setItemText(2, _translate("WebBrowserPage", "Show Speed Dial"))
        self.homePageLabel.setText(_translate("WebBrowserPage", "Home Page:"))
        self.homePageEdit.setToolTip(_translate("WebBrowserPage", "Enter the desired home page"))
        self.setCurrentPageButton.setToolTip(_translate("WebBrowserPage", "Press to set the current page as the home page"))
        self.setCurrentPageButton.setText(_translate("WebBrowserPage", "Set to current page"))
        self.defaultHomeButton.setToolTip(_translate("WebBrowserPage", "Press to set the default home page"))
        self.defaultHomeButton.setText(_translate("WebBrowserPage", "Set to default home page"))
        self.loadTabOnActivationCheckBox.setToolTip(_translate("WebBrowserPage", "Select to load restored tabs when they are activated"))
        self.loadTabOnActivationCheckBox.setText(_translate("WebBrowserPage", "Load tabs when activated"))
        self.groupBox_8.setTitle(_translate("WebBrowserPage", "Sessions"))
        self.saveSessionCheckBox.setToolTip(_translate("WebBrowserPage", "Select to save sessions automatically"))
        self.saveSessionCheckBox.setText(_translate("WebBrowserPage", "Save sessions automatically"))
        self.label_13.setText(_translate("WebBrowserPage", "Session Timer:"))
        self.sessionTimerSpinBox.setToolTip(_translate("WebBrowserPage", "Enter the time to save sessions"))
        self.sessionTimerSpinBox.setSuffix(_translate("WebBrowserPage", " s"))
        self.groupBox_2.setTitle(_translate("WebBrowserPage", "Scheme"))
        self.label_3.setText(_translate("WebBrowserPage", "Default Scheme:"))
        self.defaultSchemeCombo.setToolTip(_translate("WebBrowserPage", "Select the default scheme"))
        self.defaultSchemeCombo.setWhatsThis(_translate("WebBrowserPage", "<b>Default Scheme</b><p>Select the default scheme. This scheme is prepended to URLs, that don\'t contain one.</p>"))
        self.privacyGroup.setTitle(_translate("WebBrowserPage", "Privacy"))
        self.javaScriptGroup.setTitle(_translate("WebBrowserPage", "JavaScript"))
        self.jsOpenWindowsCheckBox.setToolTip(_translate("WebBrowserPage", "Select to allow JavaScript to open windows"))
        self.jsOpenWindowsCheckBox.setText(_translate("WebBrowserPage", "JavaScript can open windows"))
        self.jsClipboardCheckBox.setToolTip(_translate("WebBrowserPage", "Select to allow JavaScript to access the clipboard"))
        self.jsClipboardCheckBox.setText(_translate("WebBrowserPage", "JavaScript can access clipboard"))
        self.pluginsCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable plugins in web pages"))
        self.pluginsCheckBox.setText(_translate("WebBrowserPage", "Enable Plug-ins"))
        self.doNotTrackCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enabled the \"Do Not Track\" feature"))
        self.doNotTrackCheckBox.setText(_translate("WebBrowserPage", "Tell web sites I do not want to be tracked"))
        self.sendRefererCheckBox.setToolTip(_translate("WebBrowserPage", "Select to send referer headers to the server"))
        self.sendRefererCheckBox.setText(_translate("WebBrowserPage", "Send Referer header to servers"))
        self.refererWhitelistButton.setToolTip(_translate("WebBrowserPage", "Press to edit the list of whitelisted hosts"))
        self.refererWhitelistButton.setText(_translate("WebBrowserPage", "Edit Referer Whitelist ..."))
        self.groupBox_6.setTitle(_translate("WebBrowserPage", "Security"))
        self.xssAuditingCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable XSS auditing"))
        self.xssAuditingCheckBox.setWhatsThis(_translate("WebBrowserPage", "<b>Enable XSS Auditing</b>\n"
"<p>This selects whether load requests should be monitored for cross-site scripting attempts. Suspicious scripts will be blocked. These will be reported in the JavaScript console. Enabling this feature might have an impact on performance.</p>"))
        self.xssAuditingCheckBox.setText(_translate("WebBrowserPage", "Enable XSS Auditing"))
        self.insecureContentsCheckBox.setToolTip(_translate("WebBrowserPage", "Select to allow HTTPS pages to run JavaScript, CSS, plugins or web-sockets from HTTP URLs"))
        self.insecureContentsCheckBox.setText(_translate("WebBrowserPage", "Allow to run insecure contents"))
        self.groupBox.setTitle(_translate("WebBrowserPage", "History"))
        self.label_4.setText(_translate("WebBrowserPage", "Remove history items:"))
        self.expireHistory.setToolTip(_translate("WebBrowserPage", "Select the period for expiration of history entries"))
        self.expireHistory.setItemText(0, _translate("WebBrowserPage", "After one day"))
        self.expireHistory.setItemText(1, _translate("WebBrowserPage", "After one week"))
        self.expireHistory.setItemText(2, _translate("WebBrowserPage", "After two weeks"))
        self.expireHistory.setItemText(3, _translate("WebBrowserPage", "After one month"))
        self.expireHistory.setItemText(4, _translate("WebBrowserPage", "After one year"))
        self.expireHistory.setItemText(5, _translate("WebBrowserPage", "Manually"))
        self.expireHistory.setItemText(6, _translate("WebBrowserPage", "On application exit"))
        self.cacheGroup.setTitle(_translate("WebBrowserPage", "Browser Cache"))
        self.diskCacheCheckBox.setText(_translate("WebBrowserPage", "Enable disk cache"))
        self.label_7.setText(_translate("WebBrowserPage", "Cache size:"))
        self.cacheSizeSpinBox.setToolTip(_translate("WebBrowserPage", "Enter the maximum size of the disk cache"))
        self.cacheSizeSpinBox.setSuffix(_translate("WebBrowserPage", " MB"))
        self.groupBox_5.setTitle(_translate("WebBrowserPage", "Web Search"))
        self.label_5.setText(_translate("WebBrowserPage", "Language:"))
        self.languageCombo.setToolTip(_translate("WebBrowserPage", "Select the language to be used for web searches"))
        self.imageSearchGroup.setTitle(_translate("WebBrowserPage", "Image Search"))
        self.label_8.setText(_translate("WebBrowserPage", "Default Search Engine:"))
        self.imageSearchComboBox.setToolTip(_translate("WebBrowserPage", "Select the default search engine for image searches"))
        self.groupBox_3.setTitle(_translate("WebBrowserPage", "Navigation"))
        self.spatialCheckBox.setToolTip(_translate("WebBrowserPage", "Select to enable the spatial navigation feature"))
        self.spatialCheckBox.setWhatsThis(_translate("WebBrowserPage", "<b>Enable Spatial Navigation</b>\n"
"<p>This enables or disables the Spatial Navigation feature, which consists in the ability to navigate between focusable elements in a Web page, such as hyperlinks and form controls, by using Left, Right, Up and Down arrow keys. For example, if a user presses the Right key, heuristics determine whether there is an element he might be trying to reach towards the right and which element he probably wants.</p>"))
        self.spatialCheckBox.setText(_translate("WebBrowserPage", "Enable Spatial Navigation"))
        self.linksInFocusChainCheckBox.setToolTip(_translate("WebBrowserPage", "Select to include links in focus chain"))
        self.linksInFocusChainCheckBox.setWhatsThis(_translate("WebBrowserPage", "<b>Include Links in Focus Chain</b>\n"
"<p>This selects whether hyperlinks should be included in the keyboard focus chain.</p>"))
        self.linksInFocusChainCheckBox.setText(_translate("WebBrowserPage", "Include Links in Focus Chain"))
        self.focusOnNavigationCheckBox.setToolTip(_translate("WebBrowserPage", "Select to give the focus to the view whenever a navigation event occurs"))
        self.focusOnNavigationCheckBox.setText(_translate("WebBrowserPage", "Enable Focus on Navigation"))
        self.groupBox_7.setTitle(_translate("WebBrowserPage", "Printing"))
        self.printBackgroundCheckBox.setToolTip(_translate("WebBrowserPage", "Select to print the background of page elements as well"))
        self.printBackgroundCheckBox.setText(_translate("WebBrowserPage", "Print Element Backgrounds"))
        self.autoScrollGroupBox.setToolTip(_translate("WebBrowserPage", "Select to enable the auto-scroller"))
        self.autoScrollGroupBox.setTitle(_translate("WebBrowserPage", "Automatic Scrolling"))
        self.label_11.setText(_translate("WebBrowserPage", "This function is activated by a Mouse Middle Click."))
        self.label_9.setText(_translate("WebBrowserPage", "Scroll Divider:"))
        self.autoScrollDividerSpinBox.setToolTip(_translate("WebBrowserPage", "Enter the auto-scroll divider value"))
        self.label_10.setText(_translate("WebBrowserPage", "<b>Note:</b> Setting higher divider will slow down scrolling."))
        self.webInspectorGroup.setToolTip(_translate("WebBrowserPage", "Select to enable the Web Inspector tool"))
        self.webInspectorGroup.setTitle(_translate("WebBrowserPage", "Enable Web Development (Web Inspector)"))
        self.label_2.setText(_translate("WebBrowserPage", "Web Inspector Port:"))
        self.webInspectorPortSpinBox.setToolTip(_translate("WebBrowserPage", "Enter the port to be used by the web inspector"))
        self.label_6.setText(_translate("WebBrowserPage", "<font color=\"red\"><b>Note:</b> Web Inspector settings are activated after a restart of the application.</font>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WebBrowserPage = QtWidgets.QWidget()
    ui = Ui_WebBrowserPage()
    ui.setupUi(WebBrowserPage)
    WebBrowserPage.show()
    sys.exit(app.exec_())

