# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\VcsPlugins\vcsMercurial\QueuesExtension\HgQueuesDefineGuardsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HgQueuesDefineGuardsDialog(object):
    def setupUi(self, HgQueuesDefineGuardsDialog):
        HgQueuesDefineGuardsDialog.setObjectName("HgQueuesDefineGuardsDialog")
        HgQueuesDefineGuardsDialog.resize(400, 434)
        HgQueuesDefineGuardsDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(HgQueuesDefineGuardsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(HgQueuesDefineGuardsDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.patchSelector = QtWidgets.QComboBox(HgQueuesDefineGuardsDialog)
        self.patchSelector.setObjectName("patchSelector")
        self.verticalLayout.addWidget(self.patchSelector)
        self.line = QtWidgets.QFrame(HgQueuesDefineGuardsDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(HgQueuesDefineGuardsDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.patchNameLabel = QtWidgets.QLabel(HgQueuesDefineGuardsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patchNameLabel.sizePolicy().hasHeightForWidth())
        self.patchNameLabel.setSizePolicy(sizePolicy)
        self.patchNameLabel.setText("")
        self.patchNameLabel.setObjectName("patchNameLabel")
        self.horizontalLayout_3.addWidget(self.patchNameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.guardsList = QtWidgets.QListWidget(HgQueuesDefineGuardsDialog)
        self.guardsList.setAlternatingRowColors(True)
        self.guardsList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.guardsList.setObjectName("guardsList")
        self.verticalLayout.addWidget(self.guardsList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plusButton = QtWidgets.QRadioButton(HgQueuesDefineGuardsDialog)
        self.plusButton.setText("")
        self.plusButton.setChecked(True)
        self.plusButton.setObjectName("plusButton")
        self.horizontalLayout.addWidget(self.plusButton)
        self.minusButton = QtWidgets.QRadioButton(HgQueuesDefineGuardsDialog)
        self.minusButton.setText("")
        self.minusButton.setObjectName("minusButton")
        self.horizontalLayout.addWidget(self.minusButton)
        self.guardCombo = QtWidgets.QComboBox(HgQueuesDefineGuardsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guardCombo.sizePolicy().hasHeightForWidth())
        self.guardCombo.setSizePolicy(sizePolicy)
        self.guardCombo.setEditable(True)
        self.guardCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.guardCombo.setObjectName("guardCombo")
        self.horizontalLayout.addWidget(self.guardCombo)
        self.addButton = QtWidgets.QPushButton(HgQueuesDefineGuardsDialog)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.removeButton = QtWidgets.QPushButton(HgQueuesDefineGuardsDialog)
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout.addWidget(self.removeButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(HgQueuesDefineGuardsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HgQueuesDefineGuardsDialog)
        self.buttonBox.accepted.connect(HgQueuesDefineGuardsDialog.accept)
        self.buttonBox.rejected.connect(HgQueuesDefineGuardsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(HgQueuesDefineGuardsDialog)
        HgQueuesDefineGuardsDialog.setTabOrder(self.patchSelector, self.guardsList)
        HgQueuesDefineGuardsDialog.setTabOrder(self.guardsList, self.plusButton)
        HgQueuesDefineGuardsDialog.setTabOrder(self.plusButton, self.minusButton)
        HgQueuesDefineGuardsDialog.setTabOrder(self.minusButton, self.guardCombo)
        HgQueuesDefineGuardsDialog.setTabOrder(self.guardCombo, self.addButton)
        HgQueuesDefineGuardsDialog.setTabOrder(self.addButton, self.removeButton)
        HgQueuesDefineGuardsDialog.setTabOrder(self.removeButton, self.buttonBox)

    def retranslateUi(self, HgQueuesDefineGuardsDialog):
        _translate = QtCore.QCoreApplication.translate
        HgQueuesDefineGuardsDialog.setWindowTitle(_translate("HgQueuesDefineGuardsDialog", "Define Guards"))
        self.label.setText(_translate("HgQueuesDefineGuardsDialog", "Select patch (leave empty for current patch):"))
        self.patchSelector.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Select the patch to show the guards of"))
        self.label_3.setText(_translate("HgQueuesDefineGuardsDialog", "Patch:"))
        self.patchNameLabel.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Shows the name of the patch"))
        self.guardsList.setToolTip(_translate("HgQueuesDefineGuardsDialog", "This shows the list of guards to be defined for the selected patch"))
        self.plusButton.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Select to define a positive guard"))
        self.minusButton.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Select to define a negative guard"))
        self.guardCombo.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Enter the guard name"))
        self.addButton.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Press to add the guard to the list or change it"))
        self.addButton.setText(_translate("HgQueuesDefineGuardsDialog", "Add/Change"))
        self.removeButton.setToolTip(_translate("HgQueuesDefineGuardsDialog", "Press to remove the selected guards from the list"))
        self.removeButton.setText(_translate("HgQueuesDefineGuardsDialog", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HgQueuesDefineGuardsDialog = QtWidgets.QDialog()
    ui = Ui_HgQueuesDefineGuardsDialog()
    ui.setupUi(HgQueuesDefineGuardsDialog)
    HgQueuesDefineGuardsDialog.show()
    sys.exit(app.exec_())

