# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\CheckerPlugins\CodeStyleChecker\CodeStyleCheckerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CodeStyleCheckerDialog(object):
    def setupUi(self, CodeStyleCheckerDialog):
        CodeStyleCheckerDialog.setObjectName("CodeStyleCheckerDialog")
        CodeStyleCheckerDialog.resize(700, 750)
        CodeStyleCheckerDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(CodeStyleCheckerDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filterFrame = QtWidgets.QFrame(CodeStyleCheckerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.filterFrame.sizePolicy().hasHeightForWidth())
        self.filterFrame.setSizePolicy(sizePolicy)
        self.filterFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filterFrame.setObjectName("filterFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.filterFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.optionsTabWidget = QtWidgets.QTabWidget(self.filterFrame)
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.excludeFilesEdit = E5ClearableLineEdit(self.tab_1)
        self.excludeFilesEdit.setObjectName("excludeFilesEdit")
        self.gridLayout_2.addWidget(self.excludeFilesEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.excludeMessagesEdit = E5ClearableLineEdit(self.tab_1)
        self.excludeMessagesEdit.setObjectName("excludeMessagesEdit")
        self.gridLayout_2.addWidget(self.excludeMessagesEdit, 1, 1, 1, 1)
        self.excludeMessagesSelectButton = QtWidgets.QToolButton(self.tab_1)
        self.excludeMessagesSelectButton.setObjectName("excludeMessagesSelectButton")
        self.gridLayout_2.addWidget(self.excludeMessagesSelectButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.includeMessagesEdit = E5ClearableLineEdit(self.tab_1)
        self.includeMessagesEdit.setObjectName("includeMessagesEdit")
        self.gridLayout_2.addWidget(self.includeMessagesEdit, 2, 1, 1, 1)
        self.includeMessagesSelectButton = QtWidgets.QToolButton(self.tab_1)
        self.includeMessagesSelectButton.setObjectName("includeMessagesSelectButton")
        self.gridLayout_2.addWidget(self.includeMessagesSelectButton, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.fixIssuesEdit = E5ClearableLineEdit(self.tab_1)
        self.fixIssuesEdit.setObjectName("fixIssuesEdit")
        self.gridLayout_2.addWidget(self.fixIssuesEdit, 3, 1, 1, 1)
        self.fixIssuesSelectButton = QtWidgets.QToolButton(self.tab_1)
        self.fixIssuesSelectButton.setObjectName("fixIssuesSelectButton")
        self.gridLayout_2.addWidget(self.fixIssuesSelectButton, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.noFixIssuesEdit = E5ClearableLineEdit(self.tab_1)
        self.noFixIssuesEdit.setObjectName("noFixIssuesEdit")
        self.gridLayout_2.addWidget(self.noFixIssuesEdit, 4, 1, 1, 1)
        self.noFixIssuesSelectButton = QtWidgets.QToolButton(self.tab_1)
        self.noFixIssuesSelectButton.setObjectName("noFixIssuesSelectButton")
        self.gridLayout_2.addWidget(self.noFixIssuesSelectButton, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repeatCheckBox = QtWidgets.QCheckBox(self.tab_1)
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.horizontalLayout.addWidget(self.repeatCheckBox)
        self.fixIssuesCheckBox = QtWidgets.QCheckBox(self.tab_1)
        self.fixIssuesCheckBox.setEnabled(False)
        self.fixIssuesCheckBox.setObjectName("fixIssuesCheckBox")
        self.horizontalLayout.addWidget(self.fixIssuesCheckBox)
        self.ignoredCheckBox = QtWidgets.QCheckBox(self.tab_1)
        self.ignoredCheckBox.setEnabled(False)
        self.ignoredCheckBox.setObjectName("ignoredCheckBox")
        self.horizontalLayout.addWidget(self.ignoredCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 2)
        self.optionsTabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -551, 549, 772))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineLengthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.lineLengthSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineLengthSpinBox.setMinimum(60)
        self.lineLengthSpinBox.setMaximum(119)
        self.lineLengthSpinBox.setProperty("value", 79)
        self.lineLengthSpinBox.setObjectName("lineLengthSpinBox")
        self.horizontalLayout_2.addWidget(self.lineLengthSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.hangClosingCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.hangClosingCheckBox.setObjectName("hangClosingCheckBox")
        self.verticalLayout_3.addWidget(self.hangClosingCheckBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.docTypeComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.docTypeComboBox.setObjectName("docTypeComboBox")
        self.horizontalLayout_3.addWidget(self.docTypeComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.encodingsEdit = E5ClearableLineEdit(self.groupBox_4)
        self.encodingsEdit.setObjectName("encodingsEdit")
        self.horizontalLayout_6.addWidget(self.encodingsEdit)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.copyrightFileSizeSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.copyrightFileSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyrightFileSizeSpinBox.setMaximum(4096)
        self.copyrightFileSizeSpinBox.setObjectName("copyrightFileSizeSpinBox")
        self.gridLayout.addWidget(self.copyrightFileSizeSpinBox, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(324, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.copyrightAuthorEdit = E5ClearableLineEdit(self.groupBox_5)
        self.copyrightAuthorEdit.setObjectName("copyrightAuthorEdit")
        self.gridLayout.addWidget(self.copyrightAuthorEdit, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.futuresList = QtWidgets.QListWidget(self.groupBox_6)
        self.futuresList.setAlternatingRowColors(True)
        self.futuresList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.futuresList.setObjectName("futuresList")
        self.horizontalLayout_7.addWidget(self.futuresList)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.builtinsAssignmentList = QtWidgets.QTreeWidget(self.groupBox_7)
        self.builtinsAssignmentList.setAlternatingRowColors(True)
        self.builtinsAssignmentList.setRootIsDecorated(False)
        self.builtinsAssignmentList.setObjectName("builtinsAssignmentList")
        self.horizontalLayout_8.addWidget(self.builtinsAssignmentList)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addBuiltinButton = QtWidgets.QToolButton(self.groupBox_7)
        self.addBuiltinButton.setText("+")
        self.addBuiltinButton.setObjectName("addBuiltinButton")
        self.verticalLayout_5.addWidget(self.addBuiltinButton)
        self.deleteBuiltinButton = QtWidgets.QToolButton(self.groupBox_7)
        self.deleteBuiltinButton.setText("-")
        self.deleteBuiltinButton.setObjectName("deleteBuiltinButton")
        self.verticalLayout_5.addWidget(self.deleteBuiltinButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(313, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.complexitySpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.complexitySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.complexitySpinBox.setMaximum(100)
        self.complexitySpinBox.setProperty("value", 10)
        self.complexitySpinBox.setObjectName("complexitySpinBox")
        self.gridLayout_4.addWidget(self.complexitySpinBox, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineComplexitySpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.lineComplexitySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineComplexitySpinBox.setMaximum(100)
        self.lineComplexitySpinBox.setProperty("value", 15)
        self.lineComplexitySpinBox.setObjectName("lineComplexitySpinBox")
        self.gridLayout_4.addWidget(self.lineComplexitySpinBox, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineComplexityScoreSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.lineComplexityScoreSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineComplexityScoreSpinBox.setMaximum(100)
        self.lineComplexityScoreSpinBox.setProperty("value", 10)
        self.lineComplexityScoreSpinBox.setObjectName("lineComplexityScoreSpinBox")
        self.gridLayout_4.addWidget(self.lineComplexityScoreSpinBox, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.optionsTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.optionsTabWidget)
        self.line = QtWidgets.QFrame(self.filterFrame)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.filterFrame)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.fixButton = QtWidgets.QPushButton(self.filterFrame)
        self.fixButton.setObjectName("fixButton")
        self.verticalLayout.addWidget(self.fixButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.loadDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.loadDefaultButton.setObjectName("loadDefaultButton")
        self.verticalLayout.addWidget(self.loadDefaultButton)
        self.storeDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.storeDefaultButton.setObjectName("storeDefaultButton")
        self.verticalLayout.addWidget(self.storeDefaultButton)
        self.resetDefaultButton = QtWidgets.QPushButton(self.filterFrame)
        self.resetDefaultButton.setObjectName("resetDefaultButton")
        self.verticalLayout.addWidget(self.resetDefaultButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout_3.addWidget(self.filterFrame, 0, 0, 1, 1)
        self.resultList = QtWidgets.QTreeWidget(CodeStyleCheckerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.resultList.sizePolicy().hasHeightForWidth())
        self.resultList.setSizePolicy(sizePolicy)
        self.resultList.setAlternatingRowColors(True)
        self.resultList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.resultList.setObjectName("resultList")
        self.gridLayout_3.addWidget(self.resultList, 1, 0, 1, 1)
        self.checkProgressLabel = E5SqueezeLabelPath(CodeStyleCheckerDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkProgressLabel.sizePolicy().hasHeightForWidth())
        self.checkProgressLabel.setSizePolicy(sizePolicy)
        self.checkProgressLabel.setText("")
        self.checkProgressLabel.setObjectName("checkProgressLabel")
        self.gridLayout_3.addWidget(self.checkProgressLabel, 2, 0, 1, 1)
        self.checkProgress = QtWidgets.QProgressBar(CodeStyleCheckerDialog)
        self.checkProgress.setProperty("value", 0)
        self.checkProgress.setOrientation(QtCore.Qt.Horizontal)
        self.checkProgress.setObjectName("checkProgress")
        self.gridLayout_3.addWidget(self.checkProgress, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CodeStyleCheckerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(CodeStyleCheckerDialog)
        self.optionsTabWidget.setCurrentIndex(0)
        self.repeatCheckBox.toggled['bool'].connect(self.fixIssuesCheckBox.setEnabled)
        self.repeatCheckBox.toggled['bool'].connect(self.ignoredCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(CodeStyleCheckerDialog)
        CodeStyleCheckerDialog.setTabOrder(self.optionsTabWidget, self.excludeFilesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeFilesEdit, self.excludeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesEdit, self.excludeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.excludeMessagesSelectButton, self.includeMessagesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesEdit, self.includeMessagesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.includeMessagesSelectButton, self.fixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesEdit, self.fixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesSelectButton, self.noFixIssuesEdit)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesEdit, self.noFixIssuesSelectButton)
        CodeStyleCheckerDialog.setTabOrder(self.noFixIssuesSelectButton, self.repeatCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.repeatCheckBox, self.fixIssuesCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.fixIssuesCheckBox, self.ignoredCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.ignoredCheckBox, self.scrollArea)
        CodeStyleCheckerDialog.setTabOrder(self.scrollArea, self.lineLengthSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineLengthSpinBox, self.hangClosingCheckBox)
        CodeStyleCheckerDialog.setTabOrder(self.hangClosingCheckBox, self.docTypeComboBox)
        CodeStyleCheckerDialog.setTabOrder(self.docTypeComboBox, self.encodingsEdit)
        CodeStyleCheckerDialog.setTabOrder(self.encodingsEdit, self.copyrightFileSizeSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.copyrightFileSizeSpinBox, self.copyrightAuthorEdit)
        CodeStyleCheckerDialog.setTabOrder(self.copyrightAuthorEdit, self.futuresList)
        CodeStyleCheckerDialog.setTabOrder(self.futuresList, self.builtinsAssignmentList)
        CodeStyleCheckerDialog.setTabOrder(self.builtinsAssignmentList, self.addBuiltinButton)
        CodeStyleCheckerDialog.setTabOrder(self.addBuiltinButton, self.deleteBuiltinButton)
        CodeStyleCheckerDialog.setTabOrder(self.deleteBuiltinButton, self.complexitySpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.complexitySpinBox, self.lineComplexitySpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineComplexitySpinBox, self.lineComplexityScoreSpinBox)
        CodeStyleCheckerDialog.setTabOrder(self.lineComplexityScoreSpinBox, self.startButton)
        CodeStyleCheckerDialog.setTabOrder(self.startButton, self.fixButton)
        CodeStyleCheckerDialog.setTabOrder(self.fixButton, self.loadDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.loadDefaultButton, self.storeDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.storeDefaultButton, self.resetDefaultButton)
        CodeStyleCheckerDialog.setTabOrder(self.resetDefaultButton, self.resultList)

    def retranslateUi(self, CodeStyleCheckerDialog):
        _translate = QtCore.QCoreApplication.translate
        CodeStyleCheckerDialog.setWindowTitle(_translate("CodeStyleCheckerDialog", "Code Style Check Result"))
        CodeStyleCheckerDialog.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Code Style Check Results</b>\n"
"<p>This dialog shows the results of the code style check. Double clicking an\n"
"entry will open an editor window and position the cursor at the respective line and position.</p>"))
        self.label_2.setText(_translate("CodeStyleCheckerDialog", "Exclude Files:"))
        self.excludeFilesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter filename patterns of files to be excluded separated by a comma"))
        self.label.setText(_translate("CodeStyleCheckerDialog", "Exclude Messages:"))
        self.excludeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be excluded separated by a comma"))
        self.excludeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_3.setText(_translate("CodeStyleCheckerDialog", "Included Messages:"))
        self.includeMessagesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes or categories to be included separated by a comma"))
        self.includeMessagesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_4.setText(_translate("CodeStyleCheckerDialog", "Fix Issues:"))
        self.fixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues to be fixed automatically (leave empty to fix all)"))
        self.fixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.label_6.setText(_translate("CodeStyleCheckerDialog", "Don\'t Fix Issues:"))
        self.noFixIssuesEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter message codes of issues not to be fixed automatically"))
        self.noFixIssuesSelectButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to select the message codes from a list"))
        self.repeatCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to repeat each message type"))
        self.repeatCheckBox.setText(_translate("CodeStyleCheckerDialog", "Repeat messages"))
        self.fixIssuesCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to fix some issues"))
        self.fixIssuesCheckBox.setText(_translate("CodeStyleCheckerDialog", "Fix issues automatically"))
        self.ignoredCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to show ignored issues"))
        self.ignoredCheckBox.setText(_translate("CodeStyleCheckerDialog", "Show ignored"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.tab_1), _translate("CodeStyleCheckerDialog", "Global Options"))
        self.groupBox.setTitle(_translate("CodeStyleCheckerDialog", "Source Style"))
        self.label_5.setText(_translate("CodeStyleCheckerDialog", "Max. Line Length:"))
        self.lineLengthSpinBox.setStatusTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed line length (PEP-8: 79 characters)"))
        self.hangClosingCheckBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select to allow hanging closing brackets"))
        self.hangClosingCheckBox.setText(_translate("CodeStyleCheckerDialog", "Allow hanging closing brackets"))
        self.groupBox_2.setTitle(_translate("CodeStyleCheckerDialog", "Documentation Style"))
        self.label_7.setText(_translate("CodeStyleCheckerDialog", "Docstring Type:"))
        self.docTypeComboBox.setToolTip(_translate("CodeStyleCheckerDialog", "Select the rule set for docstrings"))
        self.groupBox_4.setTitle(_translate("CodeStyleCheckerDialog", "Coding Line"))
        self.label_9.setText(_translate("CodeStyleCheckerDialog", "Valid Encodings:"))
        self.encodingsEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter valid encodings separated by a comma (leave empty to use defaults)"))
        self.groupBox_5.setTitle(_translate("CodeStyleCheckerDialog", "Copyright"))
        self.label_10.setText(_translate("CodeStyleCheckerDialog", "Min. File Size:"))
        self.copyrightFileSizeSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the minimum size a file must have to be checked (0 for all files)"))
        self.label_11.setText(_translate("CodeStyleCheckerDialog", "Author:"))
        self.copyrightAuthorEdit.setToolTip(_translate("CodeStyleCheckerDialog", "Enter a copyright author name to check for (leave empty to omit this check)"))
        self.groupBox_6.setTitle(_translate("CodeStyleCheckerDialog", "Future Imports"))
        self.label_12.setText(_translate("CodeStyleCheckerDialog", "Expected Imports:"))
        self.futuresList.setSortingEnabled(True)
        self.groupBox_7.setTitle(_translate("CodeStyleCheckerDialog", "Ignore Built-ins Assignment"))
        self.builtinsAssignmentList.setSortingEnabled(True)
        self.builtinsAssignmentList.headerItem().setText(0, _translate("CodeStyleCheckerDialog", "Left"))
        self.builtinsAssignmentList.headerItem().setText(1, _translate("CodeStyleCheckerDialog", "Right"))
        self.addBuiltinButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to add a built-in assignment to be ignored"))
        self.deleteBuiltinButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to delete the selected entries"))
        self.groupBox_3.setTitle(_translate("CodeStyleCheckerDialog", "Code Complexity"))
        self.label_8.setText(_translate("CodeStyleCheckerDialog", "Max. McCabe Complexity:"))
        self.complexitySpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed code complexity (McCabe: 10)"))
        self.label_13.setText(_translate("CodeStyleCheckerDialog", "Max. Line Complexity:"))
        self.lineComplexitySpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum complexity (number of nodes) for a line of code"))
        self.label_14.setText(_translate("CodeStyleCheckerDialog", "Max. Line Complexity Score:"))
        self.lineComplexityScoreSpinBox.setToolTip(_translate("CodeStyleCheckerDialog", "Enter the maximum allowed median for line complexity"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.tab_2), _translate("CodeStyleCheckerDialog", "Specific Options"))
        self.startButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to start the code style check run"))
        self.startButton.setText(_translate("CodeStyleCheckerDialog", "&Start"))
        self.fixButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to fix the selected issues"))
        self.fixButton.setText(_translate("CodeStyleCheckerDialog", "&Fix Selected"))
        self.loadDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to load the default values"))
        self.loadDefaultButton.setText(_translate("CodeStyleCheckerDialog", "&Load Defaults"))
        self.storeDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to store the current values as defaults"))
        self.storeDefaultButton.setText(_translate("CodeStyleCheckerDialog", "St&ore Defaults"))
        self.resetDefaultButton.setToolTip(_translate("CodeStyleCheckerDialog", "Press to reset the default values"))
        self.resetDefaultButton.setText(_translate("CodeStyleCheckerDialog", "&Reset Defaults"))
        self.resultList.setWhatsThis(_translate("CodeStyleCheckerDialog", "<b>Result List</b>\n"
"<p>This list shows the results of the code style check. Double clicking\n"
"an entry will open this entry in an editor window and position the cursor at\n"
"the respective line and position.</p>"))
        self.resultList.setSortingEnabled(True)
        self.resultList.headerItem().setText(0, _translate("CodeStyleCheckerDialog", "File/Line"))
        self.resultList.headerItem().setText(1, _translate("CodeStyleCheckerDialog", "Code"))
        self.resultList.headerItem().setText(2, _translate("CodeStyleCheckerDialog", "Message"))
        self.checkProgress.setToolTip(_translate("CodeStyleCheckerDialog", "Shows the progress of the code style check"))
        self.checkProgress.setFormat(_translate("CodeStyleCheckerDialog", "%v/%m Files"))

from E5Gui.E5LineEdit import E5ClearableLineEdit
from E5Gui.E5SqueezeLabels import E5SqueezeLabelPath

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CodeStyleCheckerDialog = QtWidgets.QDialog()
    ui = Ui_CodeStyleCheckerDialog()
    ui.setupUi(CodeStyleCheckerDialog)
    CodeStyleCheckerDialog.show()
    sys.exit(app.exec_())

