# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\WizardPlugins\E5MessageBoxWizard\E5MessageBoxWizardDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_E5MessageBoxWizardDialog(object):
    def setupUi(self, E5MessageBoxWizardDialog):
        E5MessageBoxWizardDialog.setObjectName("E5MessageBoxWizardDialog")
        E5MessageBoxWizardDialog.resize(535, 681)
        E5MessageBoxWizardDialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(E5MessageBoxWizardDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.typeBox = QtWidgets.QGroupBox(E5MessageBoxWizardDialog)
        self.typeBox.setObjectName("typeBox")
        self.gridLayout = QtWidgets.QGridLayout(self.typeBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rInformation = QtWidgets.QRadioButton(self.typeBox)
        self.rInformation.setChecked(True)
        self.rInformation.setObjectName("rInformation")
        self.gridLayout.addWidget(self.rInformation, 0, 0, 1, 1)
        self.rQuestion = QtWidgets.QRadioButton(self.typeBox)
        self.rQuestion.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQuestion.setObjectName("rQuestion")
        self.gridLayout.addWidget(self.rQuestion, 0, 1, 1, 1)
        self.rWarning = QtWidgets.QRadioButton(self.typeBox)
        self.rWarning.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rWarning.setObjectName("rWarning")
        self.gridLayout.addWidget(self.rWarning, 0, 2, 1, 1)
        self.rCritical = QtWidgets.QRadioButton(self.typeBox)
        self.rCritical.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rCritical.setObjectName("rCritical")
        self.gridLayout.addWidget(self.rCritical, 0, 3, 1, 1)
        self.rYesNo = QtWidgets.QRadioButton(self.typeBox)
        self.rYesNo.setObjectName("rYesNo")
        self.gridLayout.addWidget(self.rYesNo, 1, 0, 1, 1)
        self.rRetryAbort = QtWidgets.QRadioButton(self.typeBox)
        self.rRetryAbort.setObjectName("rRetryAbort")
        self.gridLayout.addWidget(self.rRetryAbort, 1, 1, 1, 1)
        self.rOkToClearData = QtWidgets.QRadioButton(self.typeBox)
        self.rOkToClearData.setObjectName("rOkToClearData")
        self.gridLayout.addWidget(self.rOkToClearData, 1, 2, 1, 1)
        self.rAbout = QtWidgets.QRadioButton(self.typeBox)
        self.rAbout.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rAbout.setObjectName("rAbout")
        self.gridLayout.addWidget(self.rAbout, 2, 0, 1, 1)
        self.rAboutQt = QtWidgets.QRadioButton(self.typeBox)
        self.rAboutQt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rAboutQt.setObjectName("rAboutQt")
        self.gridLayout.addWidget(self.rAboutQt, 2, 1, 1, 1)
        self.rStandard = QtWidgets.QRadioButton(self.typeBox)
        self.rStandard.setObjectName("rStandard")
        self.gridLayout.addWidget(self.rStandard, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.typeBox)
        self.lResultVar = QtWidgets.QLabel(E5MessageBoxWizardDialog)
        self.lResultVar.setObjectName("lResultVar")
        self.verticalLayout_2.addWidget(self.lResultVar)
        self.eResultVar = QtWidgets.QLineEdit(E5MessageBoxWizardDialog)
        self.eResultVar.setObjectName("eResultVar")
        self.verticalLayout_2.addWidget(self.eResultVar)
        self.textLabel1 = QtWidgets.QLabel(E5MessageBoxWizardDialog)
        self.textLabel1.setObjectName("textLabel1")
        self.verticalLayout_2.addWidget(self.textLabel1)
        self.eCaption = QtWidgets.QLineEdit(E5MessageBoxWizardDialog)
        self.eCaption.setObjectName("eCaption")
        self.verticalLayout_2.addWidget(self.eCaption)
        self.textLabel2 = QtWidgets.QLabel(E5MessageBoxWizardDialog)
        self.textLabel2.setObjectName("textLabel2")
        self.verticalLayout_2.addWidget(self.textLabel2)
        self.eMessage = QtWidgets.QTextEdit(E5MessageBoxWizardDialog)
        self.eMessage.setTabChangesFocus(True)
        self.eMessage.setObjectName("eMessage")
        self.verticalLayout_2.addWidget(self.eMessage)
        self.parentGroup = QtWidgets.QGroupBox(E5MessageBoxWizardDialog)
        self.parentGroup.setObjectName("parentGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.parentGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parentSelf = QtWidgets.QRadioButton(self.parentGroup)
        self.parentSelf.setChecked(True)
        self.parentSelf.setObjectName("parentSelf")
        self.gridLayout_3.addWidget(self.parentSelf, 0, 0, 1, 1)
        self.parentNone = QtWidgets.QRadioButton(self.parentGroup)
        self.parentNone.setObjectName("parentNone")
        self.gridLayout_3.addWidget(self.parentNone, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.parentOther = QtWidgets.QRadioButton(self.parentGroup)
        self.parentOther.setObjectName("parentOther")
        self.horizontalLayout_2.addWidget(self.parentOther)
        self.parentEdit = QtWidgets.QLineEdit(self.parentGroup)
        self.parentEdit.setEnabled(False)
        self.parentEdit.setObjectName("parentEdit")
        self.horizontalLayout_2.addWidget(self.parentEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.parentGroup)
        self.standardButtons = QtWidgets.QGroupBox(E5MessageBoxWizardDialog)
        self.standardButtons.setObjectName("standardButtons")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.standardButtons)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.abortCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.abortCheck.setObjectName("abortCheck")
        self.gridLayout_2.addWidget(self.abortCheck, 0, 0, 1, 1)
        self.applyCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.applyCheck.setObjectName("applyCheck")
        self.gridLayout_2.addWidget(self.applyCheck, 0, 1, 1, 1)
        self.cancelCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.cancelCheck.setObjectName("cancelCheck")
        self.gridLayout_2.addWidget(self.cancelCheck, 0, 2, 1, 1)
        self.closeCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.closeCheck.setObjectName("closeCheck")
        self.gridLayout_2.addWidget(self.closeCheck, 0, 3, 1, 1)
        self.discardCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.discardCheck.setObjectName("discardCheck")
        self.gridLayout_2.addWidget(self.discardCheck, 0, 4, 1, 1)
        self.helpCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.helpCheck.setObjectName("helpCheck")
        self.gridLayout_2.addWidget(self.helpCheck, 1, 0, 1, 1)
        self.ignoreCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.ignoreCheck.setObjectName("ignoreCheck")
        self.gridLayout_2.addWidget(self.ignoreCheck, 1, 1, 1, 1)
        self.noCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.noCheck.setObjectName("noCheck")
        self.gridLayout_2.addWidget(self.noCheck, 1, 2, 1, 1)
        self.notoallCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.notoallCheck.setObjectName("notoallCheck")
        self.gridLayout_2.addWidget(self.notoallCheck, 1, 3, 1, 1)
        self.okCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.okCheck.setObjectName("okCheck")
        self.gridLayout_2.addWidget(self.okCheck, 1, 4, 1, 1)
        self.openCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.openCheck.setObjectName("openCheck")
        self.gridLayout_2.addWidget(self.openCheck, 2, 0, 1, 1)
        self.resetCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.resetCheck.setObjectName("resetCheck")
        self.gridLayout_2.addWidget(self.resetCheck, 2, 1, 1, 1)
        self.restoreCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.restoreCheck.setObjectName("restoreCheck")
        self.gridLayout_2.addWidget(self.restoreCheck, 2, 2, 1, 1)
        self.retryCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.retryCheck.setObjectName("retryCheck")
        self.gridLayout_2.addWidget(self.retryCheck, 2, 3, 1, 1)
        self.saveCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.saveCheck.setObjectName("saveCheck")
        self.gridLayout_2.addWidget(self.saveCheck, 2, 4, 1, 1)
        self.saveallCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.saveallCheck.setObjectName("saveallCheck")
        self.gridLayout_2.addWidget(self.saveallCheck, 3, 0, 1, 1)
        self.yesCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.yesCheck.setObjectName("yesCheck")
        self.gridLayout_2.addWidget(self.yesCheck, 3, 1, 1, 1)
        self.yestoallCheck = QtWidgets.QCheckBox(self.standardButtons)
        self.yestoallCheck.setObjectName("yestoallCheck")
        self.gridLayout_2.addWidget(self.yestoallCheck, 3, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.standardButtons)
        self.defaultButton = QtWidgets.QGroupBox(E5MessageBoxWizardDialog)
        self.defaultButton.setObjectName("defaultButton")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.defaultButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultCombo = QtWidgets.QComboBox(self.defaultButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultCombo.sizePolicy().hasHeightForWidth())
        self.defaultCombo.setSizePolicy(sizePolicy)
        self.defaultCombo.setObjectName("defaultCombo")
        self.verticalLayout.addWidget(self.defaultCombo)
        self.verticalLayout_2.addWidget(self.defaultButton)
        self.iconBox = QtWidgets.QGroupBox(E5MessageBoxWizardDialog)
        self.iconBox.setObjectName("iconBox")
        self._2 = QtWidgets.QHBoxLayout(self.iconBox)
        self._2.setObjectName("_2")
        self.iconInformation = QtWidgets.QRadioButton(self.iconBox)
        self.iconInformation.setChecked(False)
        self.iconInformation.setObjectName("iconInformation")
        self._2.addWidget(self.iconInformation)
        self.iconQuestion = QtWidgets.QRadioButton(self.iconBox)
        self.iconQuestion.setFocusPolicy(QtCore.Qt.TabFocus)
        self.iconQuestion.setChecked(True)
        self.iconQuestion.setObjectName("iconQuestion")
        self._2.addWidget(self.iconQuestion)
        self.iconWarning = QtWidgets.QRadioButton(self.iconBox)
        self.iconWarning.setFocusPolicy(QtCore.Qt.TabFocus)
        self.iconWarning.setObjectName("iconWarning")
        self._2.addWidget(self.iconWarning)
        self.iconCritical = QtWidgets.QRadioButton(self.iconBox)
        self.iconCritical.setFocusPolicy(QtCore.Qt.TabFocus)
        self.iconCritical.setObjectName("iconCritical")
        self._2.addWidget(self.iconCritical)
        self.verticalLayout_2.addWidget(self.iconBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modalCheck = QtWidgets.QCheckBox(E5MessageBoxWizardDialog)
        self.modalCheck.setEnabled(False)
        self.modalCheck.setObjectName("modalCheck")
        self.horizontalLayout.addWidget(self.modalCheck)
        self.yesDefaultCheck = QtWidgets.QCheckBox(E5MessageBoxWizardDialog)
        self.yesDefaultCheck.setEnabled(False)
        self.yesDefaultCheck.setObjectName("yesDefaultCheck")
        self.horizontalLayout.addWidget(self.yesDefaultCheck)
        self.label = QtWidgets.QLabel(E5MessageBoxWizardDialog)
        self.label.setEnabled(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.saveFuncEdit = QtWidgets.QLineEdit(E5MessageBoxWizardDialog)
        self.saveFuncEdit.setEnabled(False)
        self.saveFuncEdit.setObjectName("saveFuncEdit")
        self.horizontalLayout.addWidget(self.saveFuncEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(E5MessageBoxWizardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(E5MessageBoxWizardDialog)
        self.buttonBox.accepted.connect(E5MessageBoxWizardDialog.accept)
        self.buttonBox.rejected.connect(E5MessageBoxWizardDialog.reject)
        self.rStandard.toggled['bool'].connect(self.modalCheck.setEnabled)
        self.rYesNo.toggled['bool'].connect(self.yesDefaultCheck.setEnabled)
        self.rOkToClearData.toggled['bool'].connect(self.label.setEnabled)
        self.rOkToClearData.toggled['bool'].connect(self.saveFuncEdit.setEnabled)
        self.parentOther.toggled['bool'].connect(self.parentEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(E5MessageBoxWizardDialog)
        E5MessageBoxWizardDialog.setTabOrder(self.rInformation, self.rQuestion)
        E5MessageBoxWizardDialog.setTabOrder(self.rQuestion, self.rWarning)
        E5MessageBoxWizardDialog.setTabOrder(self.rWarning, self.rCritical)
        E5MessageBoxWizardDialog.setTabOrder(self.rCritical, self.rYesNo)
        E5MessageBoxWizardDialog.setTabOrder(self.rYesNo, self.rRetryAbort)
        E5MessageBoxWizardDialog.setTabOrder(self.rRetryAbort, self.rOkToClearData)
        E5MessageBoxWizardDialog.setTabOrder(self.rOkToClearData, self.rAbout)
        E5MessageBoxWizardDialog.setTabOrder(self.rAbout, self.rAboutQt)
        E5MessageBoxWizardDialog.setTabOrder(self.rAboutQt, self.rStandard)
        E5MessageBoxWizardDialog.setTabOrder(self.rStandard, self.eResultVar)
        E5MessageBoxWizardDialog.setTabOrder(self.eResultVar, self.eCaption)
        E5MessageBoxWizardDialog.setTabOrder(self.eCaption, self.eMessage)
        E5MessageBoxWizardDialog.setTabOrder(self.eMessage, self.parentSelf)
        E5MessageBoxWizardDialog.setTabOrder(self.parentSelf, self.parentNone)
        E5MessageBoxWizardDialog.setTabOrder(self.parentNone, self.parentOther)
        E5MessageBoxWizardDialog.setTabOrder(self.parentOther, self.parentEdit)
        E5MessageBoxWizardDialog.setTabOrder(self.parentEdit, self.abortCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.abortCheck, self.applyCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.applyCheck, self.cancelCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.cancelCheck, self.closeCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.closeCheck, self.discardCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.discardCheck, self.helpCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.helpCheck, self.ignoreCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.ignoreCheck, self.noCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.noCheck, self.notoallCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.notoallCheck, self.okCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.okCheck, self.openCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.openCheck, self.resetCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.resetCheck, self.restoreCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.restoreCheck, self.retryCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.retryCheck, self.saveCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.saveCheck, self.saveallCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.saveallCheck, self.yesCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.yesCheck, self.yestoallCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.yestoallCheck, self.defaultCombo)
        E5MessageBoxWizardDialog.setTabOrder(self.defaultCombo, self.iconInformation)
        E5MessageBoxWizardDialog.setTabOrder(self.iconInformation, self.iconQuestion)
        E5MessageBoxWizardDialog.setTabOrder(self.iconQuestion, self.iconWarning)
        E5MessageBoxWizardDialog.setTabOrder(self.iconWarning, self.iconCritical)
        E5MessageBoxWizardDialog.setTabOrder(self.iconCritical, self.modalCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.modalCheck, self.yesDefaultCheck)
        E5MessageBoxWizardDialog.setTabOrder(self.yesDefaultCheck, self.saveFuncEdit)
        E5MessageBoxWizardDialog.setTabOrder(self.saveFuncEdit, self.buttonBox)

    def retranslateUi(self, E5MessageBoxWizardDialog):
        _translate = QtCore.QCoreApplication.translate
        E5MessageBoxWizardDialog.setWindowTitle(_translate("E5MessageBoxWizardDialog", "E5MessageBox Wizard"))
        self.typeBox.setTitle(_translate("E5MessageBoxWizardDialog", "Type"))
        self.rInformation.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate an Information message box"))
        self.rInformation.setText(_translate("E5MessageBoxWizardDialog", "Information"))
        self.rQuestion.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a Question message box"))
        self.rQuestion.setText(_translate("E5MessageBoxWizardDialog", "Question"))
        self.rWarning.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a Warning message box"))
        self.rWarning.setText(_translate("E5MessageBoxWizardDialog", "Warning"))
        self.rCritical.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a Critical message box"))
        self.rCritical.setText(_translate("E5MessageBoxWizardDialog", "Critical"))
        self.rYesNo.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a Yes/No message box"))
        self.rYesNo.setText(_translate("E5MessageBoxWizardDialog", "Yes/No"))
        self.rRetryAbort.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a retry/abort message box"))
        self.rRetryAbort.setText(_translate("E5MessageBoxWizardDialog", "Retry/Abort"))
        self.rOkToClearData.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate an \"ok to clear data\" message box"))
        self.rOkToClearData.setText(_translate("E5MessageBoxWizardDialog", "OK to clear data"))
        self.rAbout.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate an About message box"))
        self.rAbout.setText(_translate("E5MessageBoxWizardDialog", "About"))
        self.rAboutQt.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate an AboutQt message box"))
        self.rAboutQt.setText(_translate("E5MessageBoxWizardDialog", "About Qt"))
        self.rStandard.setToolTip(_translate("E5MessageBoxWizardDialog", "Generate a standard message box"))
        self.rStandard.setText(_translate("E5MessageBoxWizardDialog", "Standard message box"))
        self.lResultVar.setText(_translate("E5MessageBoxWizardDialog", "Result:"))
        self.eResultVar.setToolTip(_translate("E5MessageBoxWizardDialog", "Enter the result variable name"))
        self.textLabel1.setText(_translate("E5MessageBoxWizardDialog", "Title"))
        self.eCaption.setToolTip(_translate("E5MessageBoxWizardDialog", "Enter the title for the message box"))
        self.textLabel2.setText(_translate("E5MessageBoxWizardDialog", "Message"))
        self.eMessage.setToolTip(_translate("E5MessageBoxWizardDialog", "Enter the message to be shown in the message box"))
        self.parentGroup.setTitle(_translate("E5MessageBoxWizardDialog", "Parent"))
        self.parentSelf.setToolTip(_translate("E5MessageBoxWizardDialog", "Select \"self\" as parent"))
        self.parentSelf.setText(_translate("E5MessageBoxWizardDialog", "self"))
        self.parentNone.setToolTip(_translate("E5MessageBoxWizardDialog", "Select \"None\" as parent"))
        self.parentNone.setText(_translate("E5MessageBoxWizardDialog", "None"))
        self.parentOther.setToolTip(_translate("E5MessageBoxWizardDialog", "Select to enter a parent expression"))
        self.parentOther.setText(_translate("E5MessageBoxWizardDialog", "Expression:"))
        self.parentEdit.setToolTip(_translate("E5MessageBoxWizardDialog", "Enter the parent expression"))
        self.standardButtons.setTitle(_translate("E5MessageBoxWizardDialog", "Standard Buttons"))
        self.abortCheck.setText(_translate("E5MessageBoxWizardDialog", "Abort"))
        self.applyCheck.setText(_translate("E5MessageBoxWizardDialog", "Apply"))
        self.cancelCheck.setText(_translate("E5MessageBoxWizardDialog", "Cancel"))
        self.closeCheck.setText(_translate("E5MessageBoxWizardDialog", "Close"))
        self.discardCheck.setText(_translate("E5MessageBoxWizardDialog", "Discard"))
        self.helpCheck.setText(_translate("E5MessageBoxWizardDialog", "Help"))
        self.ignoreCheck.setText(_translate("E5MessageBoxWizardDialog", "Ignore"))
        self.noCheck.setText(_translate("E5MessageBoxWizardDialog", "No"))
        self.notoallCheck.setText(_translate("E5MessageBoxWizardDialog", "No to all"))
        self.okCheck.setText(_translate("E5MessageBoxWizardDialog", "Ok"))
        self.openCheck.setText(_translate("E5MessageBoxWizardDialog", "Open"))
        self.resetCheck.setText(_translate("E5MessageBoxWizardDialog", "Reset"))
        self.restoreCheck.setText(_translate("E5MessageBoxWizardDialog", "Restore defaults"))
        self.retryCheck.setText(_translate("E5MessageBoxWizardDialog", "Retry"))
        self.saveCheck.setText(_translate("E5MessageBoxWizardDialog", "Save"))
        self.saveallCheck.setText(_translate("E5MessageBoxWizardDialog", "Save all"))
        self.yesCheck.setText(_translate("E5MessageBoxWizardDialog", "Yes"))
        self.yestoallCheck.setText(_translate("E5MessageBoxWizardDialog", "Yes to all"))
        self.defaultButton.setTitle(_translate("E5MessageBoxWizardDialog", "Default Button"))
        self.defaultCombo.setToolTip(_translate("E5MessageBoxWizardDialog", "Select the default button"))
        self.iconBox.setTitle(_translate("E5MessageBoxWizardDialog", "Icon"))
        self.iconInformation.setToolTip(_translate("E5MessageBoxWizardDialog", "Show an Information icon"))
        self.iconInformation.setText(_translate("E5MessageBoxWizardDialog", "Information"))
        self.iconQuestion.setToolTip(_translate("E5MessageBoxWizardDialog", "Show a Question icon"))
        self.iconQuestion.setText(_translate("E5MessageBoxWizardDialog", "Question"))
        self.iconWarning.setToolTip(_translate("E5MessageBoxWizardDialog", "Show a Warning icon"))
        self.iconWarning.setText(_translate("E5MessageBoxWizardDialog", "Warning"))
        self.iconCritical.setToolTip(_translate("E5MessageBoxWizardDialog", "Show a Critical icon"))
        self.iconCritical.setText(_translate("E5MessageBoxWizardDialog", "Critical"))
        self.modalCheck.setToolTip(_translate("E5MessageBoxWizardDialog", "Select to generate a modal message box"))
        self.modalCheck.setText(_translate("E5MessageBoxWizardDialog", "Modal Message Box"))
        self.yesDefaultCheck.setToolTip(_translate("E5MessageBoxWizardDialog", "Select to make \'Yes\' the default"))
        self.yesDefaultCheck.setText(_translate("E5MessageBoxWizardDialog", "Yes is default"))
        self.label.setText(_translate("E5MessageBoxWizardDialog", "Save function:"))
        self.saveFuncEdit.setToolTip(_translate("E5MessageBoxWizardDialog", "Enter the name of the save function"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    E5MessageBoxWizardDialog = QtWidgets.QDialog()
    ui = Ui_E5MessageBoxWizardDialog()
    ui.setupUi(E5MessageBoxWizardDialog)
    E5MessageBoxWizardDialog.show()
    sys.exit(app.exec_())

