# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\VcsPlugins\vcsMercurial\HgImportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HgImportDialog(object):
    def setupUi(self, HgImportDialog):
        HgImportDialog.setObjectName("HgImportDialog")
        HgImportDialog.resize(500, 400)
        HgImportDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(HgImportDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(HgImportDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.noCommitCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.noCommitCheckBox.setChecked(True)
        self.noCommitCheckBox.setObjectName("noCommitCheckBox")
        self.verticalLayout.addWidget(self.noCommitCheckBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.messageEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.messageEdit.setEnabled(False)
        self.messageEdit.setTabChangesFocus(True)
        self.messageEdit.setObjectName("messageEdit")
        self.verticalLayout.addWidget(self.messageEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setDisplayFormat("yyyy-MM-dd HH:mm")
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.userEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.userEdit.setEnabled(False)
        self.userEdit.setObjectName("userEdit")
        self.gridLayout.addWidget(self.userEdit, 1, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(HgImportDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stripSpinBox = QtWidgets.QSpinBox(HgImportDialog)
        self.stripSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stripSpinBox.setMaximum(9)
        self.stripSpinBox.setProperty("value", 1)
        self.stripSpinBox.setObjectName("stripSpinBox")
        self.horizontalLayout.addWidget(self.stripSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(HgImportDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.patchFilePicker = E5PathPicker(HgImportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patchFilePicker.sizePolicy().hasHeightForWidth())
        self.patchFilePicker.setSizePolicy(sizePolicy)
        self.patchFilePicker.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.patchFilePicker.setObjectName("patchFilePicker")
        self.gridLayout_2.addWidget(self.patchFilePicker, 2, 1, 1, 1)
        self.forceCheckBox = QtWidgets.QCheckBox(HgImportDialog)
        self.forceCheckBox.setObjectName("forceCheckBox")
        self.gridLayout_2.addWidget(self.forceCheckBox, 3, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(HgImportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 2)

        self.retranslateUi(HgImportDialog)
        self.buttonBox.accepted.connect(HgImportDialog.accept)
        self.buttonBox.rejected.connect(HgImportDialog.reject)
        self.noCommitCheckBox.toggled['bool'].connect(self.messageEdit.setDisabled)
        self.noCommitCheckBox.toggled['bool'].connect(self.dateEdit.setDisabled)
        self.noCommitCheckBox.toggled['bool'].connect(self.userEdit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(HgImportDialog)
        HgImportDialog.setTabOrder(self.noCommitCheckBox, self.messageEdit)
        HgImportDialog.setTabOrder(self.messageEdit, self.dateEdit)
        HgImportDialog.setTabOrder(self.dateEdit, self.userEdit)
        HgImportDialog.setTabOrder(self.userEdit, self.stripSpinBox)
        HgImportDialog.setTabOrder(self.stripSpinBox, self.patchFilePicker)
        HgImportDialog.setTabOrder(self.patchFilePicker, self.forceCheckBox)

    def retranslateUi(self, HgImportDialog):
        _translate = QtCore.QCoreApplication.translate
        HgImportDialog.setWindowTitle(_translate("HgImportDialog", "Import Patch"))
        self.groupBox_2.setTitle(_translate("HgImportDialog", "Commit data"))
        self.noCommitCheckBox.setToolTip(_translate("HgImportDialog", "Select to not commit the imported patch"))
        self.noCommitCheckBox.setText(_translate("HgImportDialog", "Do not commit"))
        self.label_3.setText(_translate("HgImportDialog", "Commit message:"))
        self.messageEdit.setToolTip(_translate("HgImportDialog", "Enter the commit message or leave empty to use the default one"))
        self.label.setText(_translate("HgImportDialog", "Commit Date:"))
        self.dateEdit.setToolTip(_translate("HgImportDialog", "Enter optional date for the commit"))
        self.label_2.setText(_translate("HgImportDialog", "Commit User:"))
        self.userEdit.setToolTip(_translate("HgImportDialog", "Enter optional user for the commit"))
        self.label_4.setText(_translate("HgImportDialog", "Strip Count:"))
        self.stripSpinBox.setToolTip(_translate("HgImportDialog", "Enter number of leading directories to strip off (default 1)"))
        self.label_5.setText(_translate("HgImportDialog", "Patch File:"))
        self.patchFilePicker.setToolTip(_translate("HgImportDialog", "Enter the name of the patch file"))
        self.forceCheckBox.setToolTip(_translate("HgImportDialog", "Select to enforce the import"))
        self.forceCheckBox.setText(_translate("HgImportDialog", "Enforce Import"))

from E5Gui.E5PathPicker import E5PathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HgImportDialog = QtWidgets.QDialog()
    ui = Ui_HgImportDialog()
    ui.setupUi(HgImportDialog)
    HgImportDialog.show()
    sys.exit(app.exec_())

