# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Helpviewer\CookieJar\CookiesConfigurationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CookiesConfigurationDialog(object):
    def setupUi(self, CookiesConfigurationDialog):
        CookiesConfigurationDialog.setObjectName("CookiesConfigurationDialog")
        CookiesConfigurationDialog.resize(500, 152)
        CookiesConfigurationDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CookiesConfigurationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(CookiesConfigurationDialog)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.line17 = QtWidgets.QFrame(CookiesConfigurationDialog)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line17.setObjectName("line17")
        self.verticalLayout.addWidget(self.line17)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(CookiesConfigurationDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.acceptCombo = QtWidgets.QComboBox(CookiesConfigurationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptCombo.sizePolicy().hasHeightForWidth())
        self.acceptCombo.setSizePolicy(sizePolicy)
        self.acceptCombo.setObjectName("acceptCombo")
        self.acceptCombo.addItem("")
        self.acceptCombo.addItem("")
        self.acceptCombo.addItem("")
        self.gridLayout.addWidget(self.acceptCombo, 0, 1, 1, 1)
        self.exceptionsButton = QtWidgets.QPushButton(CookiesConfigurationDialog)
        self.exceptionsButton.setObjectName("exceptionsButton")
        self.gridLayout.addWidget(self.exceptionsButton, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(CookiesConfigurationDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.keepUntilCombo = QtWidgets.QComboBox(CookiesConfigurationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keepUntilCombo.sizePolicy().hasHeightForWidth())
        self.keepUntilCombo.setSizePolicy(sizePolicy)
        self.keepUntilCombo.setObjectName("keepUntilCombo")
        self.keepUntilCombo.addItem("")
        self.keepUntilCombo.addItem("")
        self.keepUntilCombo.addItem("")
        self.gridLayout.addWidget(self.keepUntilCombo, 1, 1, 1, 1)
        self.cookiesButton = QtWidgets.QPushButton(CookiesConfigurationDialog)
        self.cookiesButton.setObjectName("cookiesButton")
        self.gridLayout.addWidget(self.cookiesButton, 1, 2, 1, 1)
        self.filterTrackingCookiesCheckbox = QtWidgets.QCheckBox(CookiesConfigurationDialog)
        self.filterTrackingCookiesCheckbox.setObjectName("filterTrackingCookiesCheckbox")
        self.gridLayout.addWidget(self.filterTrackingCookiesCheckbox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CookiesConfigurationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.acceptCombo)
        self.label.setBuddy(self.keepUntilCombo)

        self.retranslateUi(CookiesConfigurationDialog)
        self.buttonBox.accepted.connect(CookiesConfigurationDialog.accept)
        self.buttonBox.rejected.connect(CookiesConfigurationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CookiesConfigurationDialog)
        CookiesConfigurationDialog.setTabOrder(self.acceptCombo, self.exceptionsButton)
        CookiesConfigurationDialog.setTabOrder(self.exceptionsButton, self.keepUntilCombo)
        CookiesConfigurationDialog.setTabOrder(self.keepUntilCombo, self.cookiesButton)
        CookiesConfigurationDialog.setTabOrder(self.cookiesButton, self.filterTrackingCookiesCheckbox)
        CookiesConfigurationDialog.setTabOrder(self.filterTrackingCookiesCheckbox, self.buttonBox)

    def retranslateUi(self, CookiesConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        CookiesConfigurationDialog.setWindowTitle(_translate("CookiesConfigurationDialog", "Configure cookies"))
        self.headerLabel.setText(_translate("CookiesConfigurationDialog", "<b>Configure cookies</b>"))
        self.label_2.setText(_translate("CookiesConfigurationDialog", "&Accept Cookies:"))
        self.acceptCombo.setToolTip(_translate("CookiesConfigurationDialog", "Select the accept policy"))
        self.acceptCombo.setItemText(0, _translate("CookiesConfigurationDialog", "Always"))
        self.acceptCombo.setItemText(1, _translate("CookiesConfigurationDialog", "Never"))
        self.acceptCombo.setItemText(2, _translate("CookiesConfigurationDialog", "Only from sites you navigate to"))
        self.exceptionsButton.setToolTip(_translate("CookiesConfigurationDialog", "Show a dialog to configure exceptions"))
        self.exceptionsButton.setText(_translate("CookiesConfigurationDialog", "&Exceptions..."))
        self.label.setText(_translate("CookiesConfigurationDialog", "&Keep until:"))
        self.keepUntilCombo.setToolTip(_translate("CookiesConfigurationDialog", "Select the keep policy"))
        self.keepUntilCombo.setItemText(0, _translate("CookiesConfigurationDialog", "They expire"))
        self.keepUntilCombo.setItemText(1, _translate("CookiesConfigurationDialog", "I exit the application"))
        self.keepUntilCombo.setItemText(2, _translate("CookiesConfigurationDialog", "At most 90 days"))
        self.cookiesButton.setToolTip(_translate("CookiesConfigurationDialog", "Show a dialog listing all cookies"))
        self.cookiesButton.setText(_translate("CookiesConfigurationDialog", "&Show Cookies..."))
        self.filterTrackingCookiesCheckbox.setToolTip(_translate("CookiesConfigurationDialog", "Select to filter tracking cookies"))
        self.filterTrackingCookiesCheckbox.setText(_translate("CookiesConfigurationDialog", "&Filter Tracking Cookies"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CookiesConfigurationDialog = QtWidgets.QDialog()
    ui = Ui_CookiesConfigurationDialog()
    ui.setupUi(CookiesConfigurationDialog)
    CookiesConfigurationDialog.show()
    sys.exit(app.exec_())

