# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\WizardPlugins\QRegExpWizard\QRegExpWizardCharactersDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QRegExpWizardCharactersDialog(object):
    def setupUi(self, QRegExpWizardCharactersDialog):
        QRegExpWizardCharactersDialog.setObjectName("QRegExpWizardCharactersDialog")
        QRegExpWizardCharactersDialog.resize(850, 500)
        QRegExpWizardCharactersDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(QRegExpWizardCharactersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.negativeCheckBox = QtWidgets.QCheckBox(QRegExpWizardCharactersDialog)
        self.negativeCheckBox.setObjectName("negativeCheckBox")
        self.verticalLayout.addWidget(self.negativeCheckBox)
        self.predefinedBox = QtWidgets.QGroupBox(QRegExpWizardCharactersDialog)
        self.predefinedBox.setObjectName("predefinedBox")
        self.gridLayout = QtWidgets.QGridLayout(self.predefinedBox)
        self.gridLayout.setObjectName("gridLayout")
        self.wordCharCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.wordCharCheckBox.setObjectName("wordCharCheckBox")
        self.gridLayout.addWidget(self.wordCharCheckBox, 0, 0, 1, 1)
        self.digitsCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.digitsCheckBox.setObjectName("digitsCheckBox")
        self.gridLayout.addWidget(self.digitsCheckBox, 0, 1, 2, 1)
        self.whitespaceCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.whitespaceCheckBox.setObjectName("whitespaceCheckBox")
        self.gridLayout.addWidget(self.whitespaceCheckBox, 0, 2, 2, 1)
        self.nonWordCharCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.nonWordCharCheckBox.setObjectName("nonWordCharCheckBox")
        self.gridLayout.addWidget(self.nonWordCharCheckBox, 1, 0, 2, 1)
        self.nonDigitsCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.nonDigitsCheckBox.setObjectName("nonDigitsCheckBox")
        self.gridLayout.addWidget(self.nonDigitsCheckBox, 2, 1, 1, 1)
        self.nonWhitespaceCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.nonWhitespaceCheckBox.setObjectName("nonWhitespaceCheckBox")
        self.gridLayout.addWidget(self.nonWhitespaceCheckBox, 2, 2, 1, 1)
        self.w3cInitialIdentifierCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.w3cInitialIdentifierCheckBox.setObjectName("w3cInitialIdentifierCheckBox")
        self.gridLayout.addWidget(self.w3cInitialIdentifierCheckBox, 3, 0, 1, 1)
        self.w3cNmtokenCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.w3cNmtokenCheckBox.setObjectName("w3cNmtokenCheckBox")
        self.gridLayout.addWidget(self.w3cNmtokenCheckBox, 3, 1, 1, 2)
        self.w3cNonInitialIdentifierCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.w3cNonInitialIdentifierCheckBox.setObjectName("w3cNonInitialIdentifierCheckBox")
        self.gridLayout.addWidget(self.w3cNonInitialIdentifierCheckBox, 4, 0, 1, 1)
        self.w3cNonNmtokenCheckBox = QtWidgets.QCheckBox(self.predefinedBox)
        self.w3cNonNmtokenCheckBox.setObjectName("w3cNonNmtokenCheckBox")
        self.gridLayout.addWidget(self.w3cNonNmtokenCheckBox, 4, 1, 1, 2)
        self.verticalLayout.addWidget(self.predefinedBox)
        self.singlesBox = QtWidgets.QGroupBox(QRegExpWizardCharactersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singlesBox.sizePolicy().hasHeightForWidth())
        self.singlesBox.setSizePolicy(sizePolicy)
        self.singlesBox.setObjectName("singlesBox")
        self.verticalLayout.addWidget(self.singlesBox)
        self.rangesBox = QtWidgets.QGroupBox(QRegExpWizardCharactersDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangesBox.sizePolicy().hasHeightForWidth())
        self.rangesBox.setSizePolicy(sizePolicy)
        self.rangesBox.setObjectName("rangesBox")
        self.verticalLayout.addWidget(self.rangesBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(QRegExpWizardCharactersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(QRegExpWizardCharactersDialog)
        self.buttonBox.accepted.connect(QRegExpWizardCharactersDialog.accept)
        self.buttonBox.rejected.connect(QRegExpWizardCharactersDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(QRegExpWizardCharactersDialog)
        QRegExpWizardCharactersDialog.setTabOrder(self.negativeCheckBox, self.wordCharCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.wordCharCheckBox, self.nonWordCharCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.nonWordCharCheckBox, self.digitsCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.digitsCheckBox, self.nonDigitsCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.nonDigitsCheckBox, self.whitespaceCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.whitespaceCheckBox, self.nonWhitespaceCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.nonWhitespaceCheckBox, self.w3cInitialIdentifierCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.w3cInitialIdentifierCheckBox, self.w3cNonInitialIdentifierCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.w3cNonInitialIdentifierCheckBox, self.w3cNmtokenCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.w3cNmtokenCheckBox, self.w3cNonNmtokenCheckBox)
        QRegExpWizardCharactersDialog.setTabOrder(self.w3cNonNmtokenCheckBox, self.buttonBox)

    def retranslateUi(self, QRegExpWizardCharactersDialog):
        _translate = QtCore.QCoreApplication.translate
        QRegExpWizardCharactersDialog.setWindowTitle(_translate("QRegExpWizardCharactersDialog", "Editor for character sets"))
        self.negativeCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "The defined characters should not match"))
        self.predefinedBox.setTitle(_translate("QRegExpWizardCharactersDialog", "Predefined character ranges"))
        self.wordCharCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Word character"))
        self.digitsCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Digits"))
        self.whitespaceCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Whitespace characters"))
        self.nonWordCharCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Non-word characters"))
        self.nonDigitsCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Non-digits"))
        self.nonWhitespaceCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Non-whitespace characters"))
        self.w3cInitialIdentifierCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Initial name character"))
        self.w3cNmtokenCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Name character"))
        self.w3cNonInitialIdentifierCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Non-initial name character"))
        self.w3cNonNmtokenCheckBox.setText(_translate("QRegExpWizardCharactersDialog", "Non-name character"))
        self.singlesBox.setTitle(_translate("QRegExpWizardCharactersDialog", "Single character"))
        self.rangesBox.setTitle(_translate("QRegExpWizardCharactersDialog", "Character ranges"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QRegExpWizardCharactersDialog = QtWidgets.QDialog()
    ui = Ui_QRegExpWizardCharactersDialog()
    ui.setupUi(QRegExpWizardCharactersDialog)
    QRegExpWizardCharactersDialog.show()
    sys.exit(app.exec_())

