# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Plugins\WizardPlugins\FileDialogWizard\FileDialogWizardDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileDialogWizardDialog(object):
    def setupUi(self, FileDialogWizardDialog):
        FileDialogWizardDialog.setObjectName("FileDialogWizardDialog")
        FileDialogWizardDialog.resize(604, 660)
        FileDialogWizardDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileDialogWizardDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(FileDialogWizardDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pyqtComboBox = QtWidgets.QComboBox(FileDialogWizardDialog)
        self.pyqtComboBox.setObjectName("pyqtComboBox")
        self.horizontalLayout.addWidget(self.pyqtComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.typeGroupBox = QtWidgets.QGroupBox(FileDialogWizardDialog)
        self.typeGroupBox.setObjectName("typeGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.typeGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rOpenFile = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rOpenFile.setChecked(True)
        self.rOpenFile.setObjectName("rOpenFile")
        self.gridLayout.addWidget(self.rOpenFile, 0, 0, 1, 1)
        self.rOpenFiles = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rOpenFiles.setObjectName("rOpenFiles")
        self.gridLayout.addWidget(self.rOpenFiles, 0, 1, 1, 1)
        self.rSaveFile = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rSaveFile.setObjectName("rSaveFile")
        self.gridLayout.addWidget(self.rSaveFile, 0, 2, 1, 1)
        self.rDirectory = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rDirectory.setObjectName("rDirectory")
        self.gridLayout.addWidget(self.rDirectory, 0, 3, 1, 1)
        self.rfOpenFile = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rfOpenFile.setChecked(False)
        self.rfOpenFile.setObjectName("rfOpenFile")
        self.gridLayout.addWidget(self.rfOpenFile, 1, 0, 1, 1)
        self.rfOpenFiles = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rfOpenFiles.setObjectName("rfOpenFiles")
        self.gridLayout.addWidget(self.rfOpenFiles, 1, 1, 1, 1)
        self.rfSaveFile = QtWidgets.QRadioButton(self.typeGroupBox)
        self.rfSaveFile.setObjectName("rfSaveFile")
        self.gridLayout.addWidget(self.rfSaveFile, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.typeGroupBox)
        self.groupBox = QtWidgets.QGroupBox(FileDialogWizardDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.eNameVariable = QtWidgets.QLineEdit(self.groupBox)
        self.eNameVariable.setObjectName("eNameVariable")
        self.gridLayout_4.addWidget(self.eNameVariable, 0, 1, 1, 1)
        self.lFilterVariable = QtWidgets.QLabel(self.groupBox)
        self.lFilterVariable.setObjectName("lFilterVariable")
        self.gridLayout_4.addWidget(self.lFilterVariable, 1, 0, 1, 1)
        self.eFilterVariable = QtWidgets.QLineEdit(self.groupBox)
        self.eFilterVariable.setObjectName("eFilterVariable")
        self.gridLayout_4.addWidget(self.eFilterVariable, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TextLabel1 = QtWidgets.QLabel(FileDialogWizardDialog)
        self.TextLabel1.setObjectName("TextLabel1")
        self.horizontalLayout_3.addWidget(self.TextLabel1)
        self.eCaption = QtWidgets.QLineEdit(FileDialogWizardDialog)
        self.eCaption.setObjectName("eCaption")
        self.horizontalLayout_3.addWidget(self.eCaption)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.cSymlinks = QtWidgets.QCheckBox(FileDialogWizardDialog)
        self.cSymlinks.setChecked(True)
        self.cSymlinks.setObjectName("cSymlinks")
        self.verticalLayout.addWidget(self.cSymlinks)
        self.parentGroup = QtWidgets.QGroupBox(FileDialogWizardDialog)
        self.parentGroup.setObjectName("parentGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.parentGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parentSelf = QtWidgets.QRadioButton(self.parentGroup)
        self.parentSelf.setChecked(True)
        self.parentSelf.setObjectName("parentSelf")
        self.gridLayout_3.addWidget(self.parentSelf, 0, 0, 1, 1)
        self.parentNone = QtWidgets.QRadioButton(self.parentGroup)
        self.parentNone.setObjectName("parentNone")
        self.gridLayout_3.addWidget(self.parentNone, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.parentOther = QtWidgets.QRadioButton(self.parentGroup)
        self.parentOther.setObjectName("parentOther")
        self.horizontalLayout_2.addWidget(self.parentOther)
        self.parentEdit = QtWidgets.QLineEdit(self.parentGroup)
        self.parentEdit.setEnabled(False)
        self.parentEdit.setObjectName("parentEdit")
        self.horizontalLayout_2.addWidget(self.parentEdit)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.parentGroup)
        self.filePropertiesGroup = QtWidgets.QGroupBox(FileDialogWizardDialog)
        self.filePropertiesGroup.setObjectName("filePropertiesGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.filePropertiesGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextLabel3 = QtWidgets.QLabel(self.filePropertiesGroup)
        self.TextLabel3.setObjectName("TextLabel3")
        self.gridLayout_2.addWidget(self.TextLabel3, 0, 0, 1, 2)
        self.eStartWith = QtWidgets.QLineEdit(self.filePropertiesGroup)
        self.eStartWith.setObjectName("eStartWith")
        self.gridLayout_2.addWidget(self.eStartWith, 1, 0, 1, 1)
        self.cStartWith = QtWidgets.QCheckBox(self.filePropertiesGroup)
        self.cStartWith.setObjectName("cStartWith")
        self.gridLayout_2.addWidget(self.cStartWith, 1, 1, 1, 1)
        self.TextLabel2 = QtWidgets.QLabel(self.filePropertiesGroup)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridLayout_2.addWidget(self.TextLabel2, 2, 0, 1, 2)
        self.eFilters = QtWidgets.QLineEdit(self.filePropertiesGroup)
        self.eFilters.setObjectName("eFilters")
        self.gridLayout_2.addWidget(self.eFilters, 3, 0, 1, 1)
        self.cFilters = QtWidgets.QCheckBox(self.filePropertiesGroup)
        self.cFilters.setObjectName("cFilters")
        self.gridLayout_2.addWidget(self.cFilters, 3, 1, 1, 1)
        self.lInitialFilter = QtWidgets.QLabel(self.filePropertiesGroup)
        self.lInitialFilter.setObjectName("lInitialFilter")
        self.gridLayout_2.addWidget(self.lInitialFilter, 4, 0, 1, 2)
        self.eInitialFilter = QtWidgets.QLineEdit(self.filePropertiesGroup)
        self.eInitialFilter.setObjectName("eInitialFilter")
        self.gridLayout_2.addWidget(self.eInitialFilter, 5, 0, 1, 1)
        self.cInitialFilter = QtWidgets.QCheckBox(self.filePropertiesGroup)
        self.cInitialFilter.setObjectName("cInitialFilter")
        self.gridLayout_2.addWidget(self.cInitialFilter, 5, 1, 1, 1)
        self.cConfirmOverwrite = QtWidgets.QCheckBox(self.filePropertiesGroup)
        self.cConfirmOverwrite.setEnabled(False)
        self.cConfirmOverwrite.setObjectName("cConfirmOverwrite")
        self.gridLayout_2.addWidget(self.cConfirmOverwrite, 6, 0, 1, 2)
        self.verticalLayout.addWidget(self.filePropertiesGroup)
        self.dirPropertiesGroup = QtWidgets.QGroupBox(FileDialogWizardDialog)
        self.dirPropertiesGroup.setEnabled(False)
        self.dirPropertiesGroup.setObjectName("dirPropertiesGroup")
        self.gridlayout = QtWidgets.QGridLayout(self.dirPropertiesGroup)
        self.gridlayout.setObjectName("gridlayout")
        self.eWorkDir = QtWidgets.QLineEdit(self.dirPropertiesGroup)
        self.eWorkDir.setObjectName("eWorkDir")
        self.gridlayout.addWidget(self.eWorkDir, 1, 0, 1, 1)
        self.TextLabel4 = QtWidgets.QLabel(self.dirPropertiesGroup)
        self.TextLabel4.setObjectName("TextLabel4")
        self.gridlayout.addWidget(self.TextLabel4, 0, 0, 1, 2)
        self.cWorkDir = QtWidgets.QCheckBox(self.dirPropertiesGroup)
        self.cWorkDir.setObjectName("cWorkDir")
        self.gridlayout.addWidget(self.cWorkDir, 1, 1, 1, 1)
        self.cDirOnly = QtWidgets.QCheckBox(self.dirPropertiesGroup)
        self.cDirOnly.setChecked(True)
        self.cDirOnly.setObjectName("cDirOnly")
        self.gridlayout.addWidget(self.cDirOnly, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.dirPropertiesGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(FileDialogWizardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FileDialogWizardDialog)
        self.buttonBox.accepted.connect(FileDialogWizardDialog.accept)
        self.buttonBox.rejected.connect(FileDialogWizardDialog.reject)
        self.parentOther.toggled['bool'].connect(self.parentEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FileDialogWizardDialog)
        FileDialogWizardDialog.setTabOrder(self.pyqtComboBox, self.rOpenFile)
        FileDialogWizardDialog.setTabOrder(self.rOpenFile, self.rOpenFiles)
        FileDialogWizardDialog.setTabOrder(self.rOpenFiles, self.rSaveFile)
        FileDialogWizardDialog.setTabOrder(self.rSaveFile, self.rDirectory)
        FileDialogWizardDialog.setTabOrder(self.rDirectory, self.rfOpenFile)
        FileDialogWizardDialog.setTabOrder(self.rfOpenFile, self.rfOpenFiles)
        FileDialogWizardDialog.setTabOrder(self.rfOpenFiles, self.rfSaveFile)
        FileDialogWizardDialog.setTabOrder(self.rfSaveFile, self.eNameVariable)
        FileDialogWizardDialog.setTabOrder(self.eNameVariable, self.eFilterVariable)
        FileDialogWizardDialog.setTabOrder(self.eFilterVariable, self.eCaption)
        FileDialogWizardDialog.setTabOrder(self.eCaption, self.cSymlinks)
        FileDialogWizardDialog.setTabOrder(self.cSymlinks, self.parentSelf)
        FileDialogWizardDialog.setTabOrder(self.parentSelf, self.parentNone)
        FileDialogWizardDialog.setTabOrder(self.parentNone, self.parentOther)
        FileDialogWizardDialog.setTabOrder(self.parentOther, self.parentEdit)
        FileDialogWizardDialog.setTabOrder(self.parentEdit, self.eStartWith)
        FileDialogWizardDialog.setTabOrder(self.eStartWith, self.cStartWith)
        FileDialogWizardDialog.setTabOrder(self.cStartWith, self.eFilters)
        FileDialogWizardDialog.setTabOrder(self.eFilters, self.cFilters)
        FileDialogWizardDialog.setTabOrder(self.cFilters, self.eInitialFilter)
        FileDialogWizardDialog.setTabOrder(self.eInitialFilter, self.cInitialFilter)
        FileDialogWizardDialog.setTabOrder(self.cInitialFilter, self.cConfirmOverwrite)
        FileDialogWizardDialog.setTabOrder(self.cConfirmOverwrite, self.eWorkDir)
        FileDialogWizardDialog.setTabOrder(self.eWorkDir, self.cWorkDir)
        FileDialogWizardDialog.setTabOrder(self.cWorkDir, self.cDirOnly)
        FileDialogWizardDialog.setTabOrder(self.cDirOnly, self.buttonBox)

    def retranslateUi(self, FileDialogWizardDialog):
        _translate = QtCore.QCoreApplication.translate
        FileDialogWizardDialog.setWindowTitle(_translate("FileDialogWizardDialog", "QFileDialog Wizard"))
        self.label.setText(_translate("FileDialogWizardDialog", "PyQt Variant:"))
        self.typeGroupBox.setTitle(_translate("FileDialogWizardDialog", "Type"))
        self.rOpenFile.setToolTip(_translate("FileDialogWizardDialog", "Select to create an \'Open File\' dialog"))
        self.rOpenFile.setText(_translate("FileDialogWizardDialog", "Open File"))
        self.rOpenFiles.setToolTip(_translate("FileDialogWizardDialog", "Select to create an \'Open Files\' dialog"))
        self.rOpenFiles.setText(_translate("FileDialogWizardDialog", "Open Files"))
        self.rSaveFile.setToolTip(_translate("FileDialogWizardDialog", "Select to create a \'Save File\' dialog"))
        self.rSaveFile.setText(_translate("FileDialogWizardDialog", "Save File"))
        self.rDirectory.setToolTip(_translate("FileDialogWizardDialog", "Select to create a \'Select Directory\' dialog"))
        self.rDirectory.setText(_translate("FileDialogWizardDialog", "Select Directory"))
        self.rfOpenFile.setToolTip(_translate("FileDialogWizardDialog", "Select to create an \'Open File\' dialog capturing the selected filter"))
        self.rfOpenFile.setText(_translate("FileDialogWizardDialog", "Open File and Filter"))
        self.rfOpenFiles.setToolTip(_translate("FileDialogWizardDialog", "Select to create an \'Open Files\' dialog capturing the selected filter"))
        self.rfOpenFiles.setText(_translate("FileDialogWizardDialog", "Open Files and Filter"))
        self.rfSaveFile.setToolTip(_translate("FileDialogWizardDialog", "Select to create a \'Save File\' dialog capturing the selected filter"))
        self.rfSaveFile.setText(_translate("FileDialogWizardDialog", "Save File and Filter"))
        self.groupBox.setTitle(_translate("FileDialogWizardDialog", "Results"))
        self.label_2.setText(_translate("FileDialogWizardDialog", "Name Variable:"))
        self.lFilterVariable.setText(_translate("FileDialogWizardDialog", "Filter Variable:"))
        self.TextLabel1.setText(_translate("FileDialogWizardDialog", "Title:"))
        self.eCaption.setToolTip(_translate("FileDialogWizardDialog", "Enter the title text"))
        self.cSymlinks.setToolTip(_translate("FileDialogWizardDialog", "Check to resolve symbolic links"))
        self.cSymlinks.setText(_translate("FileDialogWizardDialog", "Resolve Symlinks"))
        self.parentGroup.setTitle(_translate("FileDialogWizardDialog", "Parent"))
        self.parentSelf.setToolTip(_translate("FileDialogWizardDialog", "Select \"self\" as parent"))
        self.parentSelf.setText(_translate("FileDialogWizardDialog", "self"))
        self.parentNone.setToolTip(_translate("FileDialogWizardDialog", "Select \"None\" as parent"))
        self.parentNone.setText(_translate("FileDialogWizardDialog", "None"))
        self.parentOther.setToolTip(_translate("FileDialogWizardDialog", "Select to enter a parent expression"))
        self.parentOther.setText(_translate("FileDialogWizardDialog", "Expression:"))
        self.parentEdit.setToolTip(_translate("FileDialogWizardDialog", "Enter the parent expression"))
        self.filePropertiesGroup.setTitle(_translate("FileDialogWizardDialog", "File Dialog Properties"))
        self.TextLabel3.setText(_translate("FileDialogWizardDialog", "Start With / Working Directory"))
        self.eStartWith.setToolTip(_translate("FileDialogWizardDialog", "Enter the working directory or a filename"))
        self.cStartWith.setToolTip(_translate("FileDialogWizardDialog", "Check this if the contents of the edit names a variable or variable function"))
        self.cStartWith.setText(_translate("FileDialogWizardDialog", "Is Variable"))
        self.TextLabel2.setText(_translate("FileDialogWizardDialog", "Filters"))
        self.eFilters.setToolTip(_translate("FileDialogWizardDialog", "Enter the filter specifications separated by \';;\'"))
        self.cFilters.setToolTip(_translate("FileDialogWizardDialog", "Check this if the contents of the edit names a variable or variable function"))
        self.cFilters.setText(_translate("FileDialogWizardDialog", "Is Variable"))
        self.lInitialFilter.setText(_translate("FileDialogWizardDialog", "Initial Filter"))
        self.eInitialFilter.setToolTip(_translate("FileDialogWizardDialog", "Enter the initial filter"))
        self.cInitialFilter.setToolTip(_translate("FileDialogWizardDialog", "Check this if the contents of the edit names a variable or variable function"))
        self.cInitialFilter.setText(_translate("FileDialogWizardDialog", "Is Variable"))
        self.cConfirmOverwrite.setToolTip(_translate("FileDialogWizardDialog", "Select to show an overwrite confirmation dialog"))
        self.cConfirmOverwrite.setText(_translate("FileDialogWizardDialog", "Show overwrite confirmation"))
        self.dirPropertiesGroup.setTitle(_translate("FileDialogWizardDialog", "Directory Dialog Properties"))
        self.eWorkDir.setToolTip(_translate("FileDialogWizardDialog", "Enter the working directory"))
        self.TextLabel4.setText(_translate("FileDialogWizardDialog", "Working Directory"))
        self.cWorkDir.setToolTip(_translate("FileDialogWizardDialog", "Check this if the contents of the edit names a variable or variable function"))
        self.cWorkDir.setText(_translate("FileDialogWizardDialog", "Is Variable"))
        self.cDirOnly.setToolTip(_translate("FileDialogWizardDialog", "Check to display directories only"))
        self.cDirOnly.setText(_translate("FileDialogWizardDialog", "Show Directories Only"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FileDialogWizardDialog = QtWidgets.QDialog()
    ui = Ui_FileDialogWizardDialog()
    ui.setupUi(FileDialogWizardDialog)
    FileDialogWizardDialog.show()
    sys.exit(app.exec_())

