# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\project\github\eric6-17.08\eric\Debugger\StartRunDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StartRunDialog(object):
    def setupUi(self, StartRunDialog):
        StartRunDialog.setObjectName("StartRunDialog")
        StartRunDialog.resize(488, 257)
        StartRunDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartRunDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextLabel1 = QtWidgets.QLabel(StartRunDialog)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridLayout_2.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.cmdlineCombo = QtWidgets.QComboBox(StartRunDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdlineCombo.sizePolicy().hasHeightForWidth())
        self.cmdlineCombo.setSizePolicy(sizePolicy)
        self.cmdlineCombo.setEditable(True)
        self.cmdlineCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.cmdlineCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.cmdlineCombo.setDuplicatesEnabled(False)
        self.cmdlineCombo.setObjectName("cmdlineCombo")
        self.gridLayout_2.addWidget(self.cmdlineCombo, 0, 1, 1, 1)
        self.TextLabel2 = QtWidgets.QLabel(StartRunDialog)
        self.TextLabel2.setObjectName("TextLabel2")
        self.gridLayout_2.addWidget(self.TextLabel2, 1, 0, 1, 1)
        self.workdirPicker = E5ComboPathPicker(StartRunDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workdirPicker.sizePolicy().hasHeightForWidth())
        self.workdirPicker.setSizePolicy(sizePolicy)
        self.workdirPicker.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.workdirPicker.setObjectName("workdirPicker")
        self.gridLayout_2.addWidget(self.workdirPicker, 1, 1, 1, 1)
        self.textLabel1 = QtWidgets.QLabel(StartRunDialog)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout_2.addWidget(self.textLabel1, 2, 0, 1, 1)
        self.environmentCombo = QtWidgets.QComboBox(StartRunDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.environmentCombo.sizePolicy().hasHeightForWidth())
        self.environmentCombo.setSizePolicy(sizePolicy)
        self.environmentCombo.setEditable(True)
        self.environmentCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.environmentCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.environmentCombo.setDuplicatesEnabled(False)
        self.environmentCombo.setObjectName("environmentCombo")
        self.gridLayout_2.addWidget(self.environmentCombo, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exceptionCheckBox = QtWidgets.QCheckBox(StartRunDialog)
        self.exceptionCheckBox.setChecked(True)
        self.exceptionCheckBox.setObjectName("exceptionCheckBox")
        self.gridLayout.addWidget(self.exceptionCheckBox, 0, 0, 1, 1)
        self.clearShellCheckBox = QtWidgets.QCheckBox(StartRunDialog)
        self.clearShellCheckBox.setChecked(True)
        self.clearShellCheckBox.setObjectName("clearShellCheckBox")
        self.gridLayout.addWidget(self.clearShellCheckBox, 0, 1, 1, 1)
        self.consoleCheckBox = QtWidgets.QCheckBox(StartRunDialog)
        self.consoleCheckBox.setObjectName("consoleCheckBox")
        self.gridLayout.addWidget(self.consoleCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(StartRunDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.forkModeCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.forkModeCheckBox.setObjectName("forkModeCheckBox")
        self.horizontalLayout.addWidget(self.forkModeCheckBox)
        self.forkChildCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.forkChildCheckBox.setEnabled(False)
        self.forkChildCheckBox.setObjectName("forkChildCheckBox")
        self.horizontalLayout.addWidget(self.forkChildCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(StartRunDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.TextLabel1.setBuddy(self.cmdlineCombo)
        self.TextLabel2.setBuddy(self.workdirPicker)
        self.textLabel1.setBuddy(self.environmentCombo)

        self.retranslateUi(StartRunDialog)
        self.buttonBox.accepted.connect(StartRunDialog.accept)
        self.buttonBox.rejected.connect(StartRunDialog.reject)
        self.forkModeCheckBox.toggled['bool'].connect(self.forkChildCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StartRunDialog)
        StartRunDialog.setTabOrder(self.cmdlineCombo, self.workdirPicker)
        StartRunDialog.setTabOrder(self.workdirPicker, self.environmentCombo)
        StartRunDialog.setTabOrder(self.environmentCombo, self.exceptionCheckBox)
        StartRunDialog.setTabOrder(self.exceptionCheckBox, self.clearShellCheckBox)
        StartRunDialog.setTabOrder(self.clearShellCheckBox, self.consoleCheckBox)
        StartRunDialog.setTabOrder(self.consoleCheckBox, self.forkModeCheckBox)
        StartRunDialog.setTabOrder(self.forkModeCheckBox, self.forkChildCheckBox)

    def retranslateUi(self, StartRunDialog):
        _translate = QtCore.QCoreApplication.translate
        StartRunDialog.setWindowTitle(_translate("StartRunDialog", "Start running"))
        self.TextLabel1.setText(_translate("StartRunDialog", "Command&line:"))
        self.cmdlineCombo.setToolTip(_translate("StartRunDialog", "Enter the commandline parameters"))
        self.cmdlineCombo.setWhatsThis(_translate("StartRunDialog", "<b>Commandline</b>\n"
"<p>Enter the commandline parameters in this field.</p>"))
        self.TextLabel2.setText(_translate("StartRunDialog", "&Working directory:"))
        self.workdirPicker.setToolTip(_translate("StartRunDialog", "Enter the working directory"))
        self.workdirPicker.setWhatsThis(_translate("StartRunDialog", "<b>Working directory</b>\n"
"<p>Enter the working directory of the application to be debugged. Leave it empty to set the working directory to the executable directory.</p>"))
        self.textLabel1.setText(_translate("StartRunDialog", "&Environment:"))
        self.environmentCombo.setToolTip(_translate("StartRunDialog", "Enter the environment variables to be set."))
        self.environmentCombo.setWhatsThis(_translate("StartRunDialog", "<b>Environment</b>\n"
"<p>Enter the environment variables to be set for the program. The individual settings must be separated by whitespace and be given in the form \'var=value\'. In order to add to an environment variable, enter it in the form \'var+=value\'.</p>\n"
"<p>Example: var1=1 var2=\"hello world\" var3+=\":/tmp\"</p>"))
        self.exceptionCheckBox.setToolTip(_translate("StartRunDialog", "Uncheck to disable exception reporting"))
        self.exceptionCheckBox.setWhatsThis(_translate("StartRunDialog", "<b>Report exceptions</b>\n"
"<p>Uncheck this in order to disable exception reporting.</p>"))
        self.exceptionCheckBox.setText(_translate("StartRunDialog", "Report &exceptions"))
        self.exceptionCheckBox.setShortcut(_translate("StartRunDialog", "Alt+E"))
        self.clearShellCheckBox.setToolTip(_translate("StartRunDialog", "Select to clear the display of the interpreter window"))
        self.clearShellCheckBox.setWhatsThis(_translate("StartRunDialog", "<b>Clear interpreter window</b><p>This clears the display of the interpreter window before starting the debug client.</p>"))
        self.clearShellCheckBox.setText(_translate("StartRunDialog", "Clear &interpreter window"))
        self.consoleCheckBox.setToolTip(_translate("StartRunDialog", "Select to start the debugger in a console window"))
        self.consoleCheckBox.setWhatsThis(_translate("StartRunDialog", "<b>Start in console</b>\n"
"<p>Select to start the debugger in a console window. The console command has to be configured on the Debugger-&gt;General page</p>"))
        self.consoleCheckBox.setText(_translate("StartRunDialog", "Start in console"))
        self.groupBox.setTitle(_translate("StartRunDialog", "Forking"))
        self.forkModeCheckBox.setToolTip(_translate("StartRunDialog", "Select to go through the fork without asking"))
        self.forkModeCheckBox.setWhatsThis(_translate("StartRunDialog", "<b>Fork without pausing</b>\n"
"<p>Select to go through the fork without asking making the forking decision based on the Parent/Child selection.</p>"))
        self.forkModeCheckBox.setText(_translate("StartRunDialog", "Fork without pausing"))
        self.forkChildCheckBox.setToolTip(_translate("StartRunDialog", "Select to debug the child process after forking"))
        self.forkChildCheckBox.setWhatsThis(_translate("StartRunDialog", "<b>Debug Child Process</b>\n"
"<p>Select to debug the child process after forking. If it is not selected, the parent process will be debugged. This has no effect, if forking without pausing is not selected.</p>"))
        self.forkChildCheckBox.setText(_translate("StartRunDialog", "Follow Child Process"))

from E5Gui.E5PathPicker import E5ComboPathPicker

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartRunDialog = QtWidgets.QDialog()
    ui = Ui_StartRunDialog()
    ui.setupUi(StartRunDialog)
    StartRunDialog.show()
    sys.exit(app.exec_())

